Backend: Vitis
ClockPeriod: 10
ClockUncertainty: 27%
HLSConfig:
  Model:
    BitExact: null
    BramFactor: 1000000000
    Precision:
      default: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: /tmp/h1_mlp_rf1_2c8qhhe8/tb_input_features.dat
InputShapes:
  features:
  - 4
KerasModel: !keras_model '/tmp/h1_mlp_rf1_2c8qhhe8/keras_model.keras'
OutputDir: /tmp/h1_mlp_rf1_2c8qhhe8
OutputPredictions: /tmp/h1_mlp_rf1_2c8qhhe8/tb_output_predictions.dat
OutputShapes:
  layer7_out:
  - 3
Part: xczu7ev-ffvc1156-2-e
ProjectName: mlp_iris
Stamp: bce31d1f
Version: 1.0.0
WriterConfig:
  Namespace: null
  TBOutputStream: both
  WriteEmulationConstants: false
  WriteTar: false
  WriteWeightsTxt: true
