// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module lenet_mnist_cap64_hls_relu_array_ap_fixed_84u_array_ap_fixed_22_12_4_0_0_84u_relu_config12_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer11_out_dout,
        layer11_out_empty_n,
        layer11_out_read,
        layer11_out_num_data_valid,
        layer11_out_fifo_cap,
        layer12_out_din,
        layer12_out_full_n,
        layer12_out_write,
        layer12_out_num_data_valid,
        layer12_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [1847:0] layer11_out_dout;
input   layer11_out_empty_n;
output   layer11_out_read;
input  [1:0] layer11_out_num_data_valid;
input  [1:0] layer11_out_fifo_cap;
output  [1847:0] layer12_out_din;
input   layer12_out_full_n;
output   layer12_out_write;
input  [1:0] layer12_out_num_data_valid;
input  [1:0] layer12_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer11_out_read;
reg layer12_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer11_out_blk_n;
reg    layer12_out_blk_n;
reg    ap_block_state1;
wire   [21:0] trunc_ln44_fu_539_p1;
wire   [0:0] icmp_ln51_fu_2207_p2;
wire   [20:0] trunc_ln44_166_fu_543_p1;
wire   [20:0] select_ln51_fu_2213_p3;
wire   [21:0] trunc_ln44_1_fu_547_p4;
wire   [0:0] icmp_ln51_1_fu_2225_p2;
wire   [20:0] trunc_ln44_s_fu_557_p4;
wire   [20:0] select_ln51_1_fu_2231_p3;
wire   [21:0] trunc_ln44_2_fu_567_p4;
wire   [0:0] icmp_ln51_2_fu_2243_p2;
wire   [20:0] trunc_ln44_84_fu_577_p4;
wire   [20:0] select_ln51_2_fu_2249_p3;
wire   [21:0] trunc_ln44_3_fu_587_p4;
wire   [0:0] icmp_ln51_3_fu_2261_p2;
wire   [20:0] trunc_ln44_85_fu_597_p4;
wire   [20:0] select_ln51_3_fu_2267_p3;
wire   [21:0] trunc_ln44_4_fu_607_p4;
wire   [0:0] icmp_ln51_4_fu_2279_p2;
wire   [20:0] trunc_ln44_86_fu_617_p4;
wire   [20:0] select_ln51_4_fu_2285_p3;
wire   [21:0] trunc_ln44_5_fu_627_p4;
wire   [0:0] icmp_ln51_5_fu_2297_p2;
wire   [20:0] trunc_ln44_87_fu_637_p4;
wire   [20:0] select_ln51_5_fu_2303_p3;
wire   [21:0] trunc_ln44_6_fu_647_p4;
wire   [0:0] icmp_ln51_6_fu_2315_p2;
wire   [20:0] trunc_ln44_88_fu_657_p4;
wire   [20:0] select_ln51_6_fu_2321_p3;
wire   [21:0] trunc_ln44_7_fu_667_p4;
wire   [0:0] icmp_ln51_7_fu_2333_p2;
wire   [20:0] trunc_ln44_89_fu_677_p4;
wire   [20:0] select_ln51_7_fu_2339_p3;
wire   [21:0] trunc_ln44_8_fu_687_p4;
wire   [0:0] icmp_ln51_8_fu_2351_p2;
wire   [20:0] trunc_ln44_90_fu_697_p4;
wire   [20:0] select_ln51_8_fu_2357_p3;
wire   [21:0] trunc_ln44_9_fu_707_p4;
wire   [0:0] icmp_ln51_9_fu_2369_p2;
wire   [20:0] trunc_ln44_91_fu_717_p4;
wire   [20:0] select_ln51_9_fu_2375_p3;
wire   [21:0] trunc_ln44_10_fu_727_p4;
wire   [0:0] icmp_ln51_10_fu_2387_p2;
wire   [20:0] trunc_ln44_92_fu_737_p4;
wire   [20:0] select_ln51_10_fu_2393_p3;
wire   [21:0] trunc_ln44_11_fu_747_p4;
wire   [0:0] icmp_ln51_11_fu_2405_p2;
wire   [20:0] trunc_ln44_93_fu_757_p4;
wire   [20:0] select_ln51_11_fu_2411_p3;
wire   [21:0] trunc_ln44_12_fu_767_p4;
wire   [0:0] icmp_ln51_12_fu_2423_p2;
wire   [20:0] trunc_ln44_94_fu_777_p4;
wire   [20:0] select_ln51_12_fu_2429_p3;
wire   [21:0] trunc_ln44_13_fu_787_p4;
wire   [0:0] icmp_ln51_13_fu_2441_p2;
wire   [20:0] trunc_ln44_95_fu_797_p4;
wire   [20:0] select_ln51_13_fu_2447_p3;
wire   [21:0] trunc_ln44_14_fu_807_p4;
wire   [0:0] icmp_ln51_14_fu_2459_p2;
wire   [20:0] trunc_ln44_96_fu_817_p4;
wire   [20:0] select_ln51_14_fu_2465_p3;
wire   [21:0] trunc_ln44_15_fu_827_p4;
wire   [0:0] icmp_ln51_15_fu_2477_p2;
wire   [20:0] trunc_ln44_97_fu_837_p4;
wire   [20:0] select_ln51_15_fu_2483_p3;
wire   [21:0] trunc_ln44_16_fu_847_p4;
wire   [0:0] icmp_ln51_16_fu_2495_p2;
wire   [20:0] trunc_ln44_98_fu_857_p4;
wire   [20:0] select_ln51_16_fu_2501_p3;
wire   [21:0] trunc_ln44_17_fu_867_p4;
wire   [0:0] icmp_ln51_17_fu_2513_p2;
wire   [20:0] trunc_ln44_99_fu_877_p4;
wire   [20:0] select_ln51_17_fu_2519_p3;
wire   [21:0] trunc_ln44_18_fu_887_p4;
wire   [0:0] icmp_ln51_18_fu_2531_p2;
wire   [20:0] trunc_ln44_100_fu_897_p4;
wire   [20:0] select_ln51_18_fu_2537_p3;
wire   [21:0] trunc_ln44_19_fu_907_p4;
wire   [0:0] icmp_ln51_19_fu_2549_p2;
wire   [20:0] trunc_ln44_101_fu_917_p4;
wire   [20:0] select_ln51_19_fu_2555_p3;
wire   [21:0] trunc_ln44_20_fu_927_p4;
wire   [0:0] icmp_ln51_20_fu_2567_p2;
wire   [20:0] trunc_ln44_102_fu_937_p4;
wire   [20:0] select_ln51_20_fu_2573_p3;
wire   [21:0] trunc_ln44_21_fu_947_p4;
wire   [0:0] icmp_ln51_21_fu_2585_p2;
wire   [20:0] trunc_ln44_103_fu_957_p4;
wire   [20:0] select_ln51_21_fu_2591_p3;
wire   [21:0] trunc_ln44_22_fu_967_p4;
wire   [0:0] icmp_ln51_22_fu_2603_p2;
wire   [20:0] trunc_ln44_104_fu_977_p4;
wire   [20:0] select_ln51_22_fu_2609_p3;
wire   [21:0] trunc_ln44_23_fu_987_p4;
wire   [0:0] icmp_ln51_23_fu_2621_p2;
wire   [20:0] trunc_ln44_105_fu_997_p4;
wire   [20:0] select_ln51_23_fu_2627_p3;
wire   [21:0] trunc_ln44_24_fu_1007_p4;
wire   [0:0] icmp_ln51_24_fu_2639_p2;
wire   [20:0] trunc_ln44_106_fu_1017_p4;
wire   [20:0] select_ln51_24_fu_2645_p3;
wire   [21:0] trunc_ln44_25_fu_1027_p4;
wire   [0:0] icmp_ln51_25_fu_2657_p2;
wire   [20:0] trunc_ln44_107_fu_1037_p4;
wire   [20:0] select_ln51_25_fu_2663_p3;
wire   [21:0] trunc_ln44_26_fu_1047_p4;
wire   [0:0] icmp_ln51_26_fu_2675_p2;
wire   [20:0] trunc_ln44_108_fu_1057_p4;
wire   [20:0] select_ln51_26_fu_2681_p3;
wire   [21:0] trunc_ln44_27_fu_1067_p4;
wire   [0:0] icmp_ln51_27_fu_2693_p2;
wire   [20:0] trunc_ln44_109_fu_1077_p4;
wire   [20:0] select_ln51_27_fu_2699_p3;
wire   [21:0] trunc_ln44_28_fu_1087_p4;
wire   [0:0] icmp_ln51_28_fu_2711_p2;
wire   [20:0] trunc_ln44_110_fu_1097_p4;
wire   [20:0] select_ln51_28_fu_2717_p3;
wire   [21:0] trunc_ln44_29_fu_1107_p4;
wire   [0:0] icmp_ln51_29_fu_2729_p2;
wire   [20:0] trunc_ln44_111_fu_1117_p4;
wire   [20:0] select_ln51_29_fu_2735_p3;
wire   [21:0] trunc_ln44_30_fu_1127_p4;
wire   [0:0] icmp_ln51_30_fu_2747_p2;
wire   [20:0] trunc_ln44_112_fu_1137_p4;
wire   [20:0] select_ln51_30_fu_2753_p3;
wire   [21:0] trunc_ln44_31_fu_1147_p4;
wire   [0:0] icmp_ln51_31_fu_2765_p2;
wire   [20:0] trunc_ln44_113_fu_1157_p4;
wire   [20:0] select_ln51_31_fu_2771_p3;
wire   [21:0] trunc_ln44_32_fu_1167_p4;
wire   [0:0] icmp_ln51_32_fu_2783_p2;
wire   [20:0] trunc_ln44_114_fu_1177_p4;
wire   [20:0] select_ln51_32_fu_2789_p3;
wire   [21:0] trunc_ln44_33_fu_1187_p4;
wire   [0:0] icmp_ln51_33_fu_2801_p2;
wire   [20:0] trunc_ln44_115_fu_1197_p4;
wire   [20:0] select_ln51_33_fu_2807_p3;
wire   [21:0] trunc_ln44_34_fu_1207_p4;
wire   [0:0] icmp_ln51_34_fu_2819_p2;
wire   [20:0] trunc_ln44_116_fu_1217_p4;
wire   [20:0] select_ln51_34_fu_2825_p3;
wire   [21:0] trunc_ln44_35_fu_1227_p4;
wire   [0:0] icmp_ln51_35_fu_2837_p2;
wire   [20:0] trunc_ln44_117_fu_1237_p4;
wire   [20:0] select_ln51_35_fu_2843_p3;
wire   [21:0] trunc_ln44_36_fu_1247_p4;
wire   [0:0] icmp_ln51_36_fu_2855_p2;
wire   [20:0] trunc_ln44_118_fu_1257_p4;
wire   [20:0] select_ln51_36_fu_2861_p3;
wire   [21:0] trunc_ln44_37_fu_1267_p4;
wire   [0:0] icmp_ln51_37_fu_2873_p2;
wire   [20:0] trunc_ln44_119_fu_1277_p4;
wire   [20:0] select_ln51_37_fu_2879_p3;
wire   [21:0] trunc_ln44_38_fu_1287_p4;
wire   [0:0] icmp_ln51_38_fu_2891_p2;
wire   [20:0] trunc_ln44_120_fu_1297_p4;
wire   [20:0] select_ln51_38_fu_2897_p3;
wire   [21:0] trunc_ln44_39_fu_1307_p4;
wire   [0:0] icmp_ln51_39_fu_2909_p2;
wire   [20:0] trunc_ln44_121_fu_1317_p4;
wire   [20:0] select_ln51_39_fu_2915_p3;
wire   [21:0] trunc_ln44_40_fu_1327_p4;
wire   [0:0] icmp_ln51_40_fu_2927_p2;
wire   [20:0] trunc_ln44_122_fu_1337_p4;
wire   [20:0] select_ln51_40_fu_2933_p3;
wire   [21:0] trunc_ln44_41_fu_1347_p4;
wire   [0:0] icmp_ln51_41_fu_2945_p2;
wire   [20:0] trunc_ln44_123_fu_1357_p4;
wire   [20:0] select_ln51_41_fu_2951_p3;
wire   [21:0] trunc_ln44_42_fu_1367_p4;
wire   [0:0] icmp_ln51_42_fu_2963_p2;
wire   [20:0] trunc_ln44_124_fu_1377_p4;
wire   [20:0] select_ln51_42_fu_2969_p3;
wire   [21:0] trunc_ln44_43_fu_1387_p4;
wire   [0:0] icmp_ln51_43_fu_2981_p2;
wire   [20:0] trunc_ln44_125_fu_1397_p4;
wire   [20:0] select_ln51_43_fu_2987_p3;
wire   [21:0] trunc_ln44_44_fu_1407_p4;
wire   [0:0] icmp_ln51_44_fu_2999_p2;
wire   [20:0] trunc_ln44_126_fu_1417_p4;
wire   [20:0] select_ln51_44_fu_3005_p3;
wire   [21:0] trunc_ln44_45_fu_1427_p4;
wire   [0:0] icmp_ln51_45_fu_3017_p2;
wire   [20:0] trunc_ln44_127_fu_1437_p4;
wire   [20:0] select_ln51_45_fu_3023_p3;
wire   [21:0] trunc_ln44_46_fu_1447_p4;
wire   [0:0] icmp_ln51_46_fu_3035_p2;
wire   [20:0] trunc_ln44_128_fu_1457_p4;
wire   [20:0] select_ln51_46_fu_3041_p3;
wire   [21:0] trunc_ln44_47_fu_1467_p4;
wire   [0:0] icmp_ln51_47_fu_3053_p2;
wire   [20:0] trunc_ln44_129_fu_1477_p4;
wire   [20:0] select_ln51_47_fu_3059_p3;
wire   [21:0] trunc_ln44_48_fu_1487_p4;
wire   [0:0] icmp_ln51_48_fu_3071_p2;
wire   [20:0] trunc_ln44_130_fu_1497_p4;
wire   [20:0] select_ln51_48_fu_3077_p3;
wire   [21:0] trunc_ln44_49_fu_1507_p4;
wire   [0:0] icmp_ln51_49_fu_3089_p2;
wire   [20:0] trunc_ln44_131_fu_1517_p4;
wire   [20:0] select_ln51_49_fu_3095_p3;
wire   [21:0] trunc_ln44_50_fu_1527_p4;
wire   [0:0] icmp_ln51_50_fu_3107_p2;
wire   [20:0] trunc_ln44_132_fu_1537_p4;
wire   [20:0] select_ln51_50_fu_3113_p3;
wire   [21:0] trunc_ln44_51_fu_1547_p4;
wire   [0:0] icmp_ln51_51_fu_3125_p2;
wire   [20:0] trunc_ln44_133_fu_1557_p4;
wire   [20:0] select_ln51_51_fu_3131_p3;
wire   [21:0] trunc_ln44_52_fu_1567_p4;
wire   [0:0] icmp_ln51_52_fu_3143_p2;
wire   [20:0] trunc_ln44_134_fu_1577_p4;
wire   [20:0] select_ln51_52_fu_3149_p3;
wire   [21:0] trunc_ln44_53_fu_1587_p4;
wire   [0:0] icmp_ln51_53_fu_3161_p2;
wire   [20:0] trunc_ln44_135_fu_1597_p4;
wire   [20:0] select_ln51_53_fu_3167_p3;
wire   [21:0] trunc_ln44_54_fu_1607_p4;
wire   [0:0] icmp_ln51_54_fu_3179_p2;
wire   [20:0] trunc_ln44_136_fu_1617_p4;
wire   [20:0] select_ln51_54_fu_3185_p3;
wire   [21:0] trunc_ln44_55_fu_1627_p4;
wire   [0:0] icmp_ln51_55_fu_3197_p2;
wire   [20:0] trunc_ln44_137_fu_1637_p4;
wire   [20:0] select_ln51_55_fu_3203_p3;
wire   [21:0] trunc_ln44_56_fu_1647_p4;
wire   [0:0] icmp_ln51_56_fu_3215_p2;
wire   [20:0] trunc_ln44_138_fu_1657_p4;
wire   [20:0] select_ln51_56_fu_3221_p3;
wire   [21:0] trunc_ln44_57_fu_1667_p4;
wire   [0:0] icmp_ln51_57_fu_3233_p2;
wire   [20:0] trunc_ln44_139_fu_1677_p4;
wire   [20:0] select_ln51_57_fu_3239_p3;
wire   [21:0] trunc_ln44_58_fu_1687_p4;
wire   [0:0] icmp_ln51_58_fu_3251_p2;
wire   [20:0] trunc_ln44_140_fu_1697_p4;
wire   [20:0] select_ln51_58_fu_3257_p3;
wire   [21:0] trunc_ln44_59_fu_1707_p4;
wire   [0:0] icmp_ln51_59_fu_3269_p2;
wire   [20:0] trunc_ln44_141_fu_1717_p4;
wire   [20:0] select_ln51_59_fu_3275_p3;
wire   [21:0] trunc_ln44_60_fu_1727_p4;
wire   [0:0] icmp_ln51_60_fu_3287_p2;
wire   [20:0] trunc_ln44_142_fu_1737_p4;
wire   [20:0] select_ln51_60_fu_3293_p3;
wire   [21:0] trunc_ln44_61_fu_1747_p4;
wire   [0:0] icmp_ln51_61_fu_3305_p2;
wire   [20:0] trunc_ln44_143_fu_1757_p4;
wire   [20:0] select_ln51_61_fu_3311_p3;
wire   [21:0] trunc_ln44_62_fu_1767_p4;
wire   [0:0] icmp_ln51_62_fu_3323_p2;
wire   [20:0] trunc_ln44_144_fu_1777_p4;
wire   [20:0] select_ln51_62_fu_3329_p3;
wire   [21:0] trunc_ln44_63_fu_1787_p4;
wire   [0:0] icmp_ln51_63_fu_3341_p2;
wire   [20:0] trunc_ln44_145_fu_1797_p4;
wire   [20:0] select_ln51_63_fu_3347_p3;
wire   [21:0] trunc_ln44_64_fu_1807_p4;
wire   [0:0] icmp_ln51_64_fu_3359_p2;
wire   [20:0] trunc_ln44_146_fu_1817_p4;
wire   [20:0] select_ln51_64_fu_3365_p3;
wire   [21:0] trunc_ln44_65_fu_1827_p4;
wire   [0:0] icmp_ln51_65_fu_3377_p2;
wire   [20:0] trunc_ln44_147_fu_1837_p4;
wire   [20:0] select_ln51_65_fu_3383_p3;
wire   [21:0] trunc_ln44_66_fu_1847_p4;
wire   [0:0] icmp_ln51_66_fu_3395_p2;
wire   [20:0] trunc_ln44_148_fu_1857_p4;
wire   [20:0] select_ln51_66_fu_3401_p3;
wire   [21:0] trunc_ln44_67_fu_1867_p4;
wire   [0:0] icmp_ln51_67_fu_3413_p2;
wire   [20:0] trunc_ln44_149_fu_1877_p4;
wire   [20:0] select_ln51_67_fu_3419_p3;
wire   [21:0] trunc_ln44_68_fu_1887_p4;
wire   [0:0] icmp_ln51_68_fu_3431_p2;
wire   [20:0] trunc_ln44_150_fu_1897_p4;
wire   [20:0] select_ln51_68_fu_3437_p3;
wire   [21:0] trunc_ln44_69_fu_1907_p4;
wire   [0:0] icmp_ln51_69_fu_3449_p2;
wire   [20:0] trunc_ln44_151_fu_1917_p4;
wire   [20:0] select_ln51_69_fu_3455_p3;
wire   [21:0] trunc_ln44_70_fu_1927_p4;
wire   [0:0] icmp_ln51_70_fu_3467_p2;
wire   [20:0] trunc_ln44_152_fu_1937_p4;
wire   [20:0] select_ln51_70_fu_3473_p3;
wire   [21:0] trunc_ln44_71_fu_1947_p4;
wire   [0:0] icmp_ln51_71_fu_3485_p2;
wire   [20:0] trunc_ln44_153_fu_1957_p4;
wire   [20:0] select_ln51_71_fu_3491_p3;
wire   [21:0] trunc_ln44_72_fu_1967_p4;
wire   [0:0] icmp_ln51_72_fu_3503_p2;
wire   [20:0] trunc_ln44_154_fu_1977_p4;
wire   [20:0] select_ln51_72_fu_3509_p3;
wire   [21:0] trunc_ln44_73_fu_1987_p4;
wire   [0:0] icmp_ln51_73_fu_3521_p2;
wire   [20:0] trunc_ln44_155_fu_1997_p4;
wire   [20:0] select_ln51_73_fu_3527_p3;
wire   [21:0] trunc_ln44_74_fu_2007_p4;
wire   [0:0] icmp_ln51_74_fu_3539_p2;
wire   [20:0] trunc_ln44_156_fu_2017_p4;
wire   [20:0] select_ln51_74_fu_3545_p3;
wire   [21:0] trunc_ln44_75_fu_2027_p4;
wire   [0:0] icmp_ln51_75_fu_3557_p2;
wire   [20:0] trunc_ln44_157_fu_2037_p4;
wire   [20:0] select_ln51_75_fu_3563_p3;
wire   [21:0] trunc_ln44_76_fu_2047_p4;
wire   [0:0] icmp_ln51_76_fu_3575_p2;
wire   [20:0] trunc_ln44_158_fu_2057_p4;
wire   [20:0] select_ln51_76_fu_3581_p3;
wire   [21:0] trunc_ln44_77_fu_2067_p4;
wire   [0:0] icmp_ln51_77_fu_3593_p2;
wire   [20:0] trunc_ln44_159_fu_2077_p4;
wire   [20:0] select_ln51_77_fu_3599_p3;
wire   [21:0] trunc_ln44_78_fu_2087_p4;
wire   [0:0] icmp_ln51_78_fu_3611_p2;
wire   [20:0] trunc_ln44_160_fu_2097_p4;
wire   [20:0] select_ln51_78_fu_3617_p3;
wire   [21:0] trunc_ln44_79_fu_2107_p4;
wire   [0:0] icmp_ln51_79_fu_3629_p2;
wire   [20:0] trunc_ln44_161_fu_2117_p4;
wire   [20:0] select_ln51_79_fu_3635_p3;
wire   [21:0] trunc_ln44_80_fu_2127_p4;
wire   [0:0] icmp_ln51_80_fu_3647_p2;
wire   [20:0] trunc_ln44_162_fu_2137_p4;
wire   [20:0] select_ln51_80_fu_3653_p3;
wire   [21:0] trunc_ln44_81_fu_2147_p4;
wire   [0:0] icmp_ln51_81_fu_3665_p2;
wire   [20:0] trunc_ln44_163_fu_2157_p4;
wire   [20:0] select_ln51_81_fu_3671_p3;
wire   [21:0] trunc_ln44_82_fu_2167_p4;
wire   [0:0] icmp_ln51_82_fu_3683_p2;
wire   [20:0] trunc_ln44_164_fu_2177_p4;
wire   [20:0] select_ln51_82_fu_3689_p3;
wire   [21:0] trunc_ln44_83_fu_2187_p4;
wire   [0:0] icmp_ln51_83_fu_3701_p2;
wire   [20:0] trunc_ln1_fu_2197_p4;
wire   [20:0] select_ln51_83_fu_3707_p3;
wire   [21:0] zext_ln51_82_fu_3697_p1;
wire   [21:0] zext_ln51_81_fu_3679_p1;
wire   [21:0] zext_ln51_80_fu_3661_p1;
wire   [21:0] zext_ln51_79_fu_3643_p1;
wire   [21:0] zext_ln51_78_fu_3625_p1;
wire   [21:0] zext_ln51_77_fu_3607_p1;
wire   [21:0] zext_ln51_76_fu_3589_p1;
wire   [21:0] zext_ln51_75_fu_3571_p1;
wire   [21:0] zext_ln51_74_fu_3553_p1;
wire   [21:0] zext_ln51_73_fu_3535_p1;
wire   [21:0] zext_ln51_72_fu_3517_p1;
wire   [21:0] zext_ln51_71_fu_3499_p1;
wire   [21:0] zext_ln51_70_fu_3481_p1;
wire   [21:0] zext_ln51_69_fu_3463_p1;
wire   [21:0] zext_ln51_68_fu_3445_p1;
wire   [21:0] zext_ln51_67_fu_3427_p1;
wire   [21:0] zext_ln51_66_fu_3409_p1;
wire   [21:0] zext_ln51_65_fu_3391_p1;
wire   [21:0] zext_ln51_64_fu_3373_p1;
wire   [21:0] zext_ln51_63_fu_3355_p1;
wire   [21:0] zext_ln51_62_fu_3337_p1;
wire   [21:0] zext_ln51_61_fu_3319_p1;
wire   [21:0] zext_ln51_60_fu_3301_p1;
wire   [21:0] zext_ln51_59_fu_3283_p1;
wire   [21:0] zext_ln51_58_fu_3265_p1;
wire   [21:0] zext_ln51_57_fu_3247_p1;
wire   [21:0] zext_ln51_56_fu_3229_p1;
wire   [21:0] zext_ln51_55_fu_3211_p1;
wire   [21:0] zext_ln51_54_fu_3193_p1;
wire   [21:0] zext_ln51_53_fu_3175_p1;
wire   [21:0] zext_ln51_52_fu_3157_p1;
wire   [21:0] zext_ln51_51_fu_3139_p1;
wire   [21:0] zext_ln51_50_fu_3121_p1;
wire   [21:0] zext_ln51_49_fu_3103_p1;
wire   [21:0] zext_ln51_48_fu_3085_p1;
wire   [21:0] zext_ln51_47_fu_3067_p1;
wire   [21:0] zext_ln51_46_fu_3049_p1;
wire   [21:0] zext_ln51_45_fu_3031_p1;
wire   [21:0] zext_ln51_44_fu_3013_p1;
wire   [21:0] zext_ln51_43_fu_2995_p1;
wire   [21:0] zext_ln51_42_fu_2977_p1;
wire   [21:0] zext_ln51_41_fu_2959_p1;
wire   [21:0] zext_ln51_40_fu_2941_p1;
wire   [21:0] zext_ln51_39_fu_2923_p1;
wire   [21:0] zext_ln51_38_fu_2905_p1;
wire   [21:0] zext_ln51_37_fu_2887_p1;
wire   [21:0] zext_ln51_36_fu_2869_p1;
wire   [21:0] zext_ln51_35_fu_2851_p1;
wire   [21:0] zext_ln51_34_fu_2833_p1;
wire   [21:0] zext_ln51_33_fu_2815_p1;
wire   [21:0] zext_ln51_32_fu_2797_p1;
wire   [21:0] zext_ln51_31_fu_2779_p1;
wire   [21:0] zext_ln51_30_fu_2761_p1;
wire   [21:0] zext_ln51_29_fu_2743_p1;
wire   [21:0] zext_ln51_28_fu_2725_p1;
wire   [21:0] zext_ln51_27_fu_2707_p1;
wire   [21:0] zext_ln51_26_fu_2689_p1;
wire   [21:0] zext_ln51_25_fu_2671_p1;
wire   [21:0] zext_ln51_24_fu_2653_p1;
wire   [21:0] zext_ln51_23_fu_2635_p1;
wire   [21:0] zext_ln51_22_fu_2617_p1;
wire   [21:0] zext_ln51_21_fu_2599_p1;
wire   [21:0] zext_ln51_20_fu_2581_p1;
wire   [21:0] zext_ln51_19_fu_2563_p1;
wire   [21:0] zext_ln51_18_fu_2545_p1;
wire   [21:0] zext_ln51_17_fu_2527_p1;
wire   [21:0] zext_ln51_16_fu_2509_p1;
wire   [21:0] zext_ln51_15_fu_2491_p1;
wire   [21:0] zext_ln51_14_fu_2473_p1;
wire   [21:0] zext_ln51_13_fu_2455_p1;
wire   [21:0] zext_ln51_12_fu_2437_p1;
wire   [21:0] zext_ln51_11_fu_2419_p1;
wire   [21:0] zext_ln51_10_fu_2401_p1;
wire   [21:0] zext_ln51_9_fu_2383_p1;
wire   [21:0] zext_ln51_8_fu_2365_p1;
wire   [21:0] zext_ln51_7_fu_2347_p1;
wire   [21:0] zext_ln51_6_fu_2329_p1;
wire   [21:0] zext_ln51_5_fu_2311_p1;
wire   [21:0] zext_ln51_4_fu_2293_p1;
wire   [21:0] zext_ln51_3_fu_2275_p1;
wire   [21:0] zext_ln51_2_fu_2257_p1;
wire   [21:0] zext_ln51_1_fu_2239_p1;
wire   [21:0] zext_ln51_fu_2221_p1;
wire   [1846:0] or_ln57_s_fu_3715_p85;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer11_out_blk_n = layer11_out_empty_n;
    end else begin
        layer11_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer11_out_read = 1'b1;
    end else begin
        layer11_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer12_out_blk_n = layer12_out_full_n;
    end else begin
        layer12_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer12_out_write = 1'b1;
    end else begin
        layer12_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layer12_out_full_n == 1'b0) | (layer11_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign icmp_ln51_10_fu_2387_p2 = (($signed(trunc_ln44_10_fu_727_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_11_fu_2405_p2 = (($signed(trunc_ln44_11_fu_747_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_12_fu_2423_p2 = (($signed(trunc_ln44_12_fu_767_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_13_fu_2441_p2 = (($signed(trunc_ln44_13_fu_787_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_14_fu_2459_p2 = (($signed(trunc_ln44_14_fu_807_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_15_fu_2477_p2 = (($signed(trunc_ln44_15_fu_827_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_16_fu_2495_p2 = (($signed(trunc_ln44_16_fu_847_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_17_fu_2513_p2 = (($signed(trunc_ln44_17_fu_867_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_18_fu_2531_p2 = (($signed(trunc_ln44_18_fu_887_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_19_fu_2549_p2 = (($signed(trunc_ln44_19_fu_907_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_1_fu_2225_p2 = (($signed(trunc_ln44_1_fu_547_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_20_fu_2567_p2 = (($signed(trunc_ln44_20_fu_927_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_21_fu_2585_p2 = (($signed(trunc_ln44_21_fu_947_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_22_fu_2603_p2 = (($signed(trunc_ln44_22_fu_967_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_23_fu_2621_p2 = (($signed(trunc_ln44_23_fu_987_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_24_fu_2639_p2 = (($signed(trunc_ln44_24_fu_1007_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_25_fu_2657_p2 = (($signed(trunc_ln44_25_fu_1027_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_26_fu_2675_p2 = (($signed(trunc_ln44_26_fu_1047_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_27_fu_2693_p2 = (($signed(trunc_ln44_27_fu_1067_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_28_fu_2711_p2 = (($signed(trunc_ln44_28_fu_1087_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_29_fu_2729_p2 = (($signed(trunc_ln44_29_fu_1107_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_2_fu_2243_p2 = (($signed(trunc_ln44_2_fu_567_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_30_fu_2747_p2 = (($signed(trunc_ln44_30_fu_1127_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_31_fu_2765_p2 = (($signed(trunc_ln44_31_fu_1147_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_32_fu_2783_p2 = (($signed(trunc_ln44_32_fu_1167_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_33_fu_2801_p2 = (($signed(trunc_ln44_33_fu_1187_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_34_fu_2819_p2 = (($signed(trunc_ln44_34_fu_1207_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_35_fu_2837_p2 = (($signed(trunc_ln44_35_fu_1227_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_36_fu_2855_p2 = (($signed(trunc_ln44_36_fu_1247_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_37_fu_2873_p2 = (($signed(trunc_ln44_37_fu_1267_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_38_fu_2891_p2 = (($signed(trunc_ln44_38_fu_1287_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_39_fu_2909_p2 = (($signed(trunc_ln44_39_fu_1307_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_3_fu_2261_p2 = (($signed(trunc_ln44_3_fu_587_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_40_fu_2927_p2 = (($signed(trunc_ln44_40_fu_1327_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_41_fu_2945_p2 = (($signed(trunc_ln44_41_fu_1347_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_42_fu_2963_p2 = (($signed(trunc_ln44_42_fu_1367_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_43_fu_2981_p2 = (($signed(trunc_ln44_43_fu_1387_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_44_fu_2999_p2 = (($signed(trunc_ln44_44_fu_1407_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_45_fu_3017_p2 = (($signed(trunc_ln44_45_fu_1427_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_46_fu_3035_p2 = (($signed(trunc_ln44_46_fu_1447_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_47_fu_3053_p2 = (($signed(trunc_ln44_47_fu_1467_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_48_fu_3071_p2 = (($signed(trunc_ln44_48_fu_1487_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_49_fu_3089_p2 = (($signed(trunc_ln44_49_fu_1507_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_4_fu_2279_p2 = (($signed(trunc_ln44_4_fu_607_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_50_fu_3107_p2 = (($signed(trunc_ln44_50_fu_1527_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_51_fu_3125_p2 = (($signed(trunc_ln44_51_fu_1547_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_52_fu_3143_p2 = (($signed(trunc_ln44_52_fu_1567_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_53_fu_3161_p2 = (($signed(trunc_ln44_53_fu_1587_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_54_fu_3179_p2 = (($signed(trunc_ln44_54_fu_1607_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_55_fu_3197_p2 = (($signed(trunc_ln44_55_fu_1627_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_56_fu_3215_p2 = (($signed(trunc_ln44_56_fu_1647_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_57_fu_3233_p2 = (($signed(trunc_ln44_57_fu_1667_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_58_fu_3251_p2 = (($signed(trunc_ln44_58_fu_1687_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_59_fu_3269_p2 = (($signed(trunc_ln44_59_fu_1707_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_5_fu_2297_p2 = (($signed(trunc_ln44_5_fu_627_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_60_fu_3287_p2 = (($signed(trunc_ln44_60_fu_1727_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_61_fu_3305_p2 = (($signed(trunc_ln44_61_fu_1747_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_62_fu_3323_p2 = (($signed(trunc_ln44_62_fu_1767_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_63_fu_3341_p2 = (($signed(trunc_ln44_63_fu_1787_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_64_fu_3359_p2 = (($signed(trunc_ln44_64_fu_1807_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_65_fu_3377_p2 = (($signed(trunc_ln44_65_fu_1827_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_66_fu_3395_p2 = (($signed(trunc_ln44_66_fu_1847_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_67_fu_3413_p2 = (($signed(trunc_ln44_67_fu_1867_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_68_fu_3431_p2 = (($signed(trunc_ln44_68_fu_1887_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_69_fu_3449_p2 = (($signed(trunc_ln44_69_fu_1907_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_6_fu_2315_p2 = (($signed(trunc_ln44_6_fu_647_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_70_fu_3467_p2 = (($signed(trunc_ln44_70_fu_1927_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_71_fu_3485_p2 = (($signed(trunc_ln44_71_fu_1947_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_72_fu_3503_p2 = (($signed(trunc_ln44_72_fu_1967_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_73_fu_3521_p2 = (($signed(trunc_ln44_73_fu_1987_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_74_fu_3539_p2 = (($signed(trunc_ln44_74_fu_2007_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_75_fu_3557_p2 = (($signed(trunc_ln44_75_fu_2027_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_76_fu_3575_p2 = (($signed(trunc_ln44_76_fu_2047_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_77_fu_3593_p2 = (($signed(trunc_ln44_77_fu_2067_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_78_fu_3611_p2 = (($signed(trunc_ln44_78_fu_2087_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_79_fu_3629_p2 = (($signed(trunc_ln44_79_fu_2107_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_7_fu_2333_p2 = (($signed(trunc_ln44_7_fu_667_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_80_fu_3647_p2 = (($signed(trunc_ln44_80_fu_2127_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_81_fu_3665_p2 = (($signed(trunc_ln44_81_fu_2147_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_82_fu_3683_p2 = (($signed(trunc_ln44_82_fu_2167_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_83_fu_3701_p2 = (($signed(trunc_ln44_83_fu_2187_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_8_fu_2351_p2 = (($signed(trunc_ln44_8_fu_687_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_9_fu_2369_p2 = (($signed(trunc_ln44_9_fu_707_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_2207_p2 = (($signed(trunc_ln44_fu_539_p1) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign layer12_out_din = or_ln57_s_fu_3715_p85;

assign or_ln57_s_fu_3715_p85 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{select_ln51_83_fu_3707_p3}, {zext_ln51_82_fu_3697_p1}}, {zext_ln51_81_fu_3679_p1}}, {zext_ln51_80_fu_3661_p1}}, {zext_ln51_79_fu_3643_p1}}, {zext_ln51_78_fu_3625_p1}}, {zext_ln51_77_fu_3607_p1}}, {zext_ln51_76_fu_3589_p1}}, {zext_ln51_75_fu_3571_p1}}, {zext_ln51_74_fu_3553_p1}}, {zext_ln51_73_fu_3535_p1}}, {zext_ln51_72_fu_3517_p1}}, {zext_ln51_71_fu_3499_p1}}, {zext_ln51_70_fu_3481_p1}}, {zext_ln51_69_fu_3463_p1}}, {zext_ln51_68_fu_3445_p1}}, {zext_ln51_67_fu_3427_p1}}, {zext_ln51_66_fu_3409_p1}}, {zext_ln51_65_fu_3391_p1}}, {zext_ln51_64_fu_3373_p1}}, {zext_ln51_63_fu_3355_p1}}, {zext_ln51_62_fu_3337_p1}}, {zext_ln51_61_fu_3319_p1}}, {zext_ln51_60_fu_3301_p1}}, {zext_ln51_59_fu_3283_p1}}, {zext_ln51_58_fu_3265_p1}}, {zext_ln51_57_fu_3247_p1}}, {zext_ln51_56_fu_3229_p1}}, {zext_ln51_55_fu_3211_p1}}, {zext_ln51_54_fu_3193_p1}}, {zext_ln51_53_fu_3175_p1}}, {zext_ln51_52_fu_3157_p1}}, {zext_ln51_51_fu_3139_p1}}, {zext_ln51_50_fu_3121_p1}}, 
    {zext_ln51_49_fu_3103_p1}}, {zext_ln51_48_fu_3085_p1}}, {zext_ln51_47_fu_3067_p1}}, {zext_ln51_46_fu_3049_p1}}, {zext_ln51_45_fu_3031_p1}}, {zext_ln51_44_fu_3013_p1}}, {zext_ln51_43_fu_2995_p1}}, {zext_ln51_42_fu_2977_p1}}, {zext_ln51_41_fu_2959_p1}}, {zext_ln51_40_fu_2941_p1}}, {zext_ln51_39_fu_2923_p1}}, {zext_ln51_38_fu_2905_p1}}, {zext_ln51_37_fu_2887_p1}}, {zext_ln51_36_fu_2869_p1}}, {zext_ln51_35_fu_2851_p1}}, {zext_ln51_34_fu_2833_p1}}, {zext_ln51_33_fu_2815_p1}}, {zext_ln51_32_fu_2797_p1}}, {zext_ln51_31_fu_2779_p1}}, {zext_ln51_30_fu_2761_p1}}, {zext_ln51_29_fu_2743_p1}}, {zext_ln51_28_fu_2725_p1}}, {zext_ln51_27_fu_2707_p1}}, {zext_ln51_26_fu_2689_p1}}, {zext_ln51_25_fu_2671_p1}}, {zext_ln51_24_fu_2653_p1}}, {zext_ln51_23_fu_2635_p1}}, {zext_ln51_22_fu_2617_p1}}, {zext_ln51_21_fu_2599_p1}}, {zext_ln51_20_fu_2581_p1}}, {zext_ln51_19_fu_2563_p1}}, {zext_ln51_18_fu_2545_p1}}, {zext_ln51_17_fu_2527_p1}}, {zext_ln51_16_fu_2509_p1}}, {zext_ln51_15_fu_2491_p1}}, {zext_ln51_14_fu_2473_p1}}, {zext_ln51_13_fu_2455_p1}}, 
    {zext_ln51_12_fu_2437_p1}}, {zext_ln51_11_fu_2419_p1}}, {zext_ln51_10_fu_2401_p1}}, {zext_ln51_9_fu_2383_p1}}, {zext_ln51_8_fu_2365_p1}}, {zext_ln51_7_fu_2347_p1}}, {zext_ln51_6_fu_2329_p1}}, {zext_ln51_5_fu_2311_p1}}, {zext_ln51_4_fu_2293_p1}}, {zext_ln51_3_fu_2275_p1}}, {zext_ln51_2_fu_2257_p1}}, {zext_ln51_1_fu_2239_p1}}, {zext_ln51_fu_2221_p1}};

assign select_ln51_10_fu_2393_p3 = ((icmp_ln51_10_fu_2387_p2[0:0] == 1'b1) ? trunc_ln44_92_fu_737_p4 : 21'd0);

assign select_ln51_11_fu_2411_p3 = ((icmp_ln51_11_fu_2405_p2[0:0] == 1'b1) ? trunc_ln44_93_fu_757_p4 : 21'd0);

assign select_ln51_12_fu_2429_p3 = ((icmp_ln51_12_fu_2423_p2[0:0] == 1'b1) ? trunc_ln44_94_fu_777_p4 : 21'd0);

assign select_ln51_13_fu_2447_p3 = ((icmp_ln51_13_fu_2441_p2[0:0] == 1'b1) ? trunc_ln44_95_fu_797_p4 : 21'd0);

assign select_ln51_14_fu_2465_p3 = ((icmp_ln51_14_fu_2459_p2[0:0] == 1'b1) ? trunc_ln44_96_fu_817_p4 : 21'd0);

assign select_ln51_15_fu_2483_p3 = ((icmp_ln51_15_fu_2477_p2[0:0] == 1'b1) ? trunc_ln44_97_fu_837_p4 : 21'd0);

assign select_ln51_16_fu_2501_p3 = ((icmp_ln51_16_fu_2495_p2[0:0] == 1'b1) ? trunc_ln44_98_fu_857_p4 : 21'd0);

assign select_ln51_17_fu_2519_p3 = ((icmp_ln51_17_fu_2513_p2[0:0] == 1'b1) ? trunc_ln44_99_fu_877_p4 : 21'd0);

assign select_ln51_18_fu_2537_p3 = ((icmp_ln51_18_fu_2531_p2[0:0] == 1'b1) ? trunc_ln44_100_fu_897_p4 : 21'd0);

assign select_ln51_19_fu_2555_p3 = ((icmp_ln51_19_fu_2549_p2[0:0] == 1'b1) ? trunc_ln44_101_fu_917_p4 : 21'd0);

assign select_ln51_1_fu_2231_p3 = ((icmp_ln51_1_fu_2225_p2[0:0] == 1'b1) ? trunc_ln44_s_fu_557_p4 : 21'd0);

assign select_ln51_20_fu_2573_p3 = ((icmp_ln51_20_fu_2567_p2[0:0] == 1'b1) ? trunc_ln44_102_fu_937_p4 : 21'd0);

assign select_ln51_21_fu_2591_p3 = ((icmp_ln51_21_fu_2585_p2[0:0] == 1'b1) ? trunc_ln44_103_fu_957_p4 : 21'd0);

assign select_ln51_22_fu_2609_p3 = ((icmp_ln51_22_fu_2603_p2[0:0] == 1'b1) ? trunc_ln44_104_fu_977_p4 : 21'd0);

assign select_ln51_23_fu_2627_p3 = ((icmp_ln51_23_fu_2621_p2[0:0] == 1'b1) ? trunc_ln44_105_fu_997_p4 : 21'd0);

assign select_ln51_24_fu_2645_p3 = ((icmp_ln51_24_fu_2639_p2[0:0] == 1'b1) ? trunc_ln44_106_fu_1017_p4 : 21'd0);

assign select_ln51_25_fu_2663_p3 = ((icmp_ln51_25_fu_2657_p2[0:0] == 1'b1) ? trunc_ln44_107_fu_1037_p4 : 21'd0);

assign select_ln51_26_fu_2681_p3 = ((icmp_ln51_26_fu_2675_p2[0:0] == 1'b1) ? trunc_ln44_108_fu_1057_p4 : 21'd0);

assign select_ln51_27_fu_2699_p3 = ((icmp_ln51_27_fu_2693_p2[0:0] == 1'b1) ? trunc_ln44_109_fu_1077_p4 : 21'd0);

assign select_ln51_28_fu_2717_p3 = ((icmp_ln51_28_fu_2711_p2[0:0] == 1'b1) ? trunc_ln44_110_fu_1097_p4 : 21'd0);

assign select_ln51_29_fu_2735_p3 = ((icmp_ln51_29_fu_2729_p2[0:0] == 1'b1) ? trunc_ln44_111_fu_1117_p4 : 21'd0);

assign select_ln51_2_fu_2249_p3 = ((icmp_ln51_2_fu_2243_p2[0:0] == 1'b1) ? trunc_ln44_84_fu_577_p4 : 21'd0);

assign select_ln51_30_fu_2753_p3 = ((icmp_ln51_30_fu_2747_p2[0:0] == 1'b1) ? trunc_ln44_112_fu_1137_p4 : 21'd0);

assign select_ln51_31_fu_2771_p3 = ((icmp_ln51_31_fu_2765_p2[0:0] == 1'b1) ? trunc_ln44_113_fu_1157_p4 : 21'd0);

assign select_ln51_32_fu_2789_p3 = ((icmp_ln51_32_fu_2783_p2[0:0] == 1'b1) ? trunc_ln44_114_fu_1177_p4 : 21'd0);

assign select_ln51_33_fu_2807_p3 = ((icmp_ln51_33_fu_2801_p2[0:0] == 1'b1) ? trunc_ln44_115_fu_1197_p4 : 21'd0);

assign select_ln51_34_fu_2825_p3 = ((icmp_ln51_34_fu_2819_p2[0:0] == 1'b1) ? trunc_ln44_116_fu_1217_p4 : 21'd0);

assign select_ln51_35_fu_2843_p3 = ((icmp_ln51_35_fu_2837_p2[0:0] == 1'b1) ? trunc_ln44_117_fu_1237_p4 : 21'd0);

assign select_ln51_36_fu_2861_p3 = ((icmp_ln51_36_fu_2855_p2[0:0] == 1'b1) ? trunc_ln44_118_fu_1257_p4 : 21'd0);

assign select_ln51_37_fu_2879_p3 = ((icmp_ln51_37_fu_2873_p2[0:0] == 1'b1) ? trunc_ln44_119_fu_1277_p4 : 21'd0);

assign select_ln51_38_fu_2897_p3 = ((icmp_ln51_38_fu_2891_p2[0:0] == 1'b1) ? trunc_ln44_120_fu_1297_p4 : 21'd0);

assign select_ln51_39_fu_2915_p3 = ((icmp_ln51_39_fu_2909_p2[0:0] == 1'b1) ? trunc_ln44_121_fu_1317_p4 : 21'd0);

assign select_ln51_3_fu_2267_p3 = ((icmp_ln51_3_fu_2261_p2[0:0] == 1'b1) ? trunc_ln44_85_fu_597_p4 : 21'd0);

assign select_ln51_40_fu_2933_p3 = ((icmp_ln51_40_fu_2927_p2[0:0] == 1'b1) ? trunc_ln44_122_fu_1337_p4 : 21'd0);

assign select_ln51_41_fu_2951_p3 = ((icmp_ln51_41_fu_2945_p2[0:0] == 1'b1) ? trunc_ln44_123_fu_1357_p4 : 21'd0);

assign select_ln51_42_fu_2969_p3 = ((icmp_ln51_42_fu_2963_p2[0:0] == 1'b1) ? trunc_ln44_124_fu_1377_p4 : 21'd0);

assign select_ln51_43_fu_2987_p3 = ((icmp_ln51_43_fu_2981_p2[0:0] == 1'b1) ? trunc_ln44_125_fu_1397_p4 : 21'd0);

assign select_ln51_44_fu_3005_p3 = ((icmp_ln51_44_fu_2999_p2[0:0] == 1'b1) ? trunc_ln44_126_fu_1417_p4 : 21'd0);

assign select_ln51_45_fu_3023_p3 = ((icmp_ln51_45_fu_3017_p2[0:0] == 1'b1) ? trunc_ln44_127_fu_1437_p4 : 21'd0);

assign select_ln51_46_fu_3041_p3 = ((icmp_ln51_46_fu_3035_p2[0:0] == 1'b1) ? trunc_ln44_128_fu_1457_p4 : 21'd0);

assign select_ln51_47_fu_3059_p3 = ((icmp_ln51_47_fu_3053_p2[0:0] == 1'b1) ? trunc_ln44_129_fu_1477_p4 : 21'd0);

assign select_ln51_48_fu_3077_p3 = ((icmp_ln51_48_fu_3071_p2[0:0] == 1'b1) ? trunc_ln44_130_fu_1497_p4 : 21'd0);

assign select_ln51_49_fu_3095_p3 = ((icmp_ln51_49_fu_3089_p2[0:0] == 1'b1) ? trunc_ln44_131_fu_1517_p4 : 21'd0);

assign select_ln51_4_fu_2285_p3 = ((icmp_ln51_4_fu_2279_p2[0:0] == 1'b1) ? trunc_ln44_86_fu_617_p4 : 21'd0);

assign select_ln51_50_fu_3113_p3 = ((icmp_ln51_50_fu_3107_p2[0:0] == 1'b1) ? trunc_ln44_132_fu_1537_p4 : 21'd0);

assign select_ln51_51_fu_3131_p3 = ((icmp_ln51_51_fu_3125_p2[0:0] == 1'b1) ? trunc_ln44_133_fu_1557_p4 : 21'd0);

assign select_ln51_52_fu_3149_p3 = ((icmp_ln51_52_fu_3143_p2[0:0] == 1'b1) ? trunc_ln44_134_fu_1577_p4 : 21'd0);

assign select_ln51_53_fu_3167_p3 = ((icmp_ln51_53_fu_3161_p2[0:0] == 1'b1) ? trunc_ln44_135_fu_1597_p4 : 21'd0);

assign select_ln51_54_fu_3185_p3 = ((icmp_ln51_54_fu_3179_p2[0:0] == 1'b1) ? trunc_ln44_136_fu_1617_p4 : 21'd0);

assign select_ln51_55_fu_3203_p3 = ((icmp_ln51_55_fu_3197_p2[0:0] == 1'b1) ? trunc_ln44_137_fu_1637_p4 : 21'd0);

assign select_ln51_56_fu_3221_p3 = ((icmp_ln51_56_fu_3215_p2[0:0] == 1'b1) ? trunc_ln44_138_fu_1657_p4 : 21'd0);

assign select_ln51_57_fu_3239_p3 = ((icmp_ln51_57_fu_3233_p2[0:0] == 1'b1) ? trunc_ln44_139_fu_1677_p4 : 21'd0);

assign select_ln51_58_fu_3257_p3 = ((icmp_ln51_58_fu_3251_p2[0:0] == 1'b1) ? trunc_ln44_140_fu_1697_p4 : 21'd0);

assign select_ln51_59_fu_3275_p3 = ((icmp_ln51_59_fu_3269_p2[0:0] == 1'b1) ? trunc_ln44_141_fu_1717_p4 : 21'd0);

assign select_ln51_5_fu_2303_p3 = ((icmp_ln51_5_fu_2297_p2[0:0] == 1'b1) ? trunc_ln44_87_fu_637_p4 : 21'd0);

assign select_ln51_60_fu_3293_p3 = ((icmp_ln51_60_fu_3287_p2[0:0] == 1'b1) ? trunc_ln44_142_fu_1737_p4 : 21'd0);

assign select_ln51_61_fu_3311_p3 = ((icmp_ln51_61_fu_3305_p2[0:0] == 1'b1) ? trunc_ln44_143_fu_1757_p4 : 21'd0);

assign select_ln51_62_fu_3329_p3 = ((icmp_ln51_62_fu_3323_p2[0:0] == 1'b1) ? trunc_ln44_144_fu_1777_p4 : 21'd0);

assign select_ln51_63_fu_3347_p3 = ((icmp_ln51_63_fu_3341_p2[0:0] == 1'b1) ? trunc_ln44_145_fu_1797_p4 : 21'd0);

assign select_ln51_64_fu_3365_p3 = ((icmp_ln51_64_fu_3359_p2[0:0] == 1'b1) ? trunc_ln44_146_fu_1817_p4 : 21'd0);

assign select_ln51_65_fu_3383_p3 = ((icmp_ln51_65_fu_3377_p2[0:0] == 1'b1) ? trunc_ln44_147_fu_1837_p4 : 21'd0);

assign select_ln51_66_fu_3401_p3 = ((icmp_ln51_66_fu_3395_p2[0:0] == 1'b1) ? trunc_ln44_148_fu_1857_p4 : 21'd0);

assign select_ln51_67_fu_3419_p3 = ((icmp_ln51_67_fu_3413_p2[0:0] == 1'b1) ? trunc_ln44_149_fu_1877_p4 : 21'd0);

assign select_ln51_68_fu_3437_p3 = ((icmp_ln51_68_fu_3431_p2[0:0] == 1'b1) ? trunc_ln44_150_fu_1897_p4 : 21'd0);

assign select_ln51_69_fu_3455_p3 = ((icmp_ln51_69_fu_3449_p2[0:0] == 1'b1) ? trunc_ln44_151_fu_1917_p4 : 21'd0);

assign select_ln51_6_fu_2321_p3 = ((icmp_ln51_6_fu_2315_p2[0:0] == 1'b1) ? trunc_ln44_88_fu_657_p4 : 21'd0);

assign select_ln51_70_fu_3473_p3 = ((icmp_ln51_70_fu_3467_p2[0:0] == 1'b1) ? trunc_ln44_152_fu_1937_p4 : 21'd0);

assign select_ln51_71_fu_3491_p3 = ((icmp_ln51_71_fu_3485_p2[0:0] == 1'b1) ? trunc_ln44_153_fu_1957_p4 : 21'd0);

assign select_ln51_72_fu_3509_p3 = ((icmp_ln51_72_fu_3503_p2[0:0] == 1'b1) ? trunc_ln44_154_fu_1977_p4 : 21'd0);

assign select_ln51_73_fu_3527_p3 = ((icmp_ln51_73_fu_3521_p2[0:0] == 1'b1) ? trunc_ln44_155_fu_1997_p4 : 21'd0);

assign select_ln51_74_fu_3545_p3 = ((icmp_ln51_74_fu_3539_p2[0:0] == 1'b1) ? trunc_ln44_156_fu_2017_p4 : 21'd0);

assign select_ln51_75_fu_3563_p3 = ((icmp_ln51_75_fu_3557_p2[0:0] == 1'b1) ? trunc_ln44_157_fu_2037_p4 : 21'd0);

assign select_ln51_76_fu_3581_p3 = ((icmp_ln51_76_fu_3575_p2[0:0] == 1'b1) ? trunc_ln44_158_fu_2057_p4 : 21'd0);

assign select_ln51_77_fu_3599_p3 = ((icmp_ln51_77_fu_3593_p2[0:0] == 1'b1) ? trunc_ln44_159_fu_2077_p4 : 21'd0);

assign select_ln51_78_fu_3617_p3 = ((icmp_ln51_78_fu_3611_p2[0:0] == 1'b1) ? trunc_ln44_160_fu_2097_p4 : 21'd0);

assign select_ln51_79_fu_3635_p3 = ((icmp_ln51_79_fu_3629_p2[0:0] == 1'b1) ? trunc_ln44_161_fu_2117_p4 : 21'd0);

assign select_ln51_7_fu_2339_p3 = ((icmp_ln51_7_fu_2333_p2[0:0] == 1'b1) ? trunc_ln44_89_fu_677_p4 : 21'd0);

assign select_ln51_80_fu_3653_p3 = ((icmp_ln51_80_fu_3647_p2[0:0] == 1'b1) ? trunc_ln44_162_fu_2137_p4 : 21'd0);

assign select_ln51_81_fu_3671_p3 = ((icmp_ln51_81_fu_3665_p2[0:0] == 1'b1) ? trunc_ln44_163_fu_2157_p4 : 21'd0);

assign select_ln51_82_fu_3689_p3 = ((icmp_ln51_82_fu_3683_p2[0:0] == 1'b1) ? trunc_ln44_164_fu_2177_p4 : 21'd0);

assign select_ln51_83_fu_3707_p3 = ((icmp_ln51_83_fu_3701_p2[0:0] == 1'b1) ? trunc_ln1_fu_2197_p4 : 21'd0);

assign select_ln51_8_fu_2357_p3 = ((icmp_ln51_8_fu_2351_p2[0:0] == 1'b1) ? trunc_ln44_90_fu_697_p4 : 21'd0);

assign select_ln51_9_fu_2375_p3 = ((icmp_ln51_9_fu_2369_p2[0:0] == 1'b1) ? trunc_ln44_91_fu_717_p4 : 21'd0);

assign select_ln51_fu_2213_p3 = ((icmp_ln51_fu_2207_p2[0:0] == 1'b1) ? trunc_ln44_166_fu_543_p1 : 21'd0);

assign start_out = real_start;

assign trunc_ln1_fu_2197_p4 = {{layer11_out_dout[1846:1826]}};

assign trunc_ln44_100_fu_897_p4 = {{layer11_out_dout[416:396]}};

assign trunc_ln44_101_fu_917_p4 = {{layer11_out_dout[438:418]}};

assign trunc_ln44_102_fu_937_p4 = {{layer11_out_dout[460:440]}};

assign trunc_ln44_103_fu_957_p4 = {{layer11_out_dout[482:462]}};

assign trunc_ln44_104_fu_977_p4 = {{layer11_out_dout[504:484]}};

assign trunc_ln44_105_fu_997_p4 = {{layer11_out_dout[526:506]}};

assign trunc_ln44_106_fu_1017_p4 = {{layer11_out_dout[548:528]}};

assign trunc_ln44_107_fu_1037_p4 = {{layer11_out_dout[570:550]}};

assign trunc_ln44_108_fu_1057_p4 = {{layer11_out_dout[592:572]}};

assign trunc_ln44_109_fu_1077_p4 = {{layer11_out_dout[614:594]}};

assign trunc_ln44_10_fu_727_p4 = {{layer11_out_dout[241:220]}};

assign trunc_ln44_110_fu_1097_p4 = {{layer11_out_dout[636:616]}};

assign trunc_ln44_111_fu_1117_p4 = {{layer11_out_dout[658:638]}};

assign trunc_ln44_112_fu_1137_p4 = {{layer11_out_dout[680:660]}};

assign trunc_ln44_113_fu_1157_p4 = {{layer11_out_dout[702:682]}};

assign trunc_ln44_114_fu_1177_p4 = {{layer11_out_dout[724:704]}};

assign trunc_ln44_115_fu_1197_p4 = {{layer11_out_dout[746:726]}};

assign trunc_ln44_116_fu_1217_p4 = {{layer11_out_dout[768:748]}};

assign trunc_ln44_117_fu_1237_p4 = {{layer11_out_dout[790:770]}};

assign trunc_ln44_118_fu_1257_p4 = {{layer11_out_dout[812:792]}};

assign trunc_ln44_119_fu_1277_p4 = {{layer11_out_dout[834:814]}};

assign trunc_ln44_11_fu_747_p4 = {{layer11_out_dout[263:242]}};

assign trunc_ln44_120_fu_1297_p4 = {{layer11_out_dout[856:836]}};

assign trunc_ln44_121_fu_1317_p4 = {{layer11_out_dout[878:858]}};

assign trunc_ln44_122_fu_1337_p4 = {{layer11_out_dout[900:880]}};

assign trunc_ln44_123_fu_1357_p4 = {{layer11_out_dout[922:902]}};

assign trunc_ln44_124_fu_1377_p4 = {{layer11_out_dout[944:924]}};

assign trunc_ln44_125_fu_1397_p4 = {{layer11_out_dout[966:946]}};

assign trunc_ln44_126_fu_1417_p4 = {{layer11_out_dout[988:968]}};

assign trunc_ln44_127_fu_1437_p4 = {{layer11_out_dout[1010:990]}};

assign trunc_ln44_128_fu_1457_p4 = {{layer11_out_dout[1032:1012]}};

assign trunc_ln44_129_fu_1477_p4 = {{layer11_out_dout[1054:1034]}};

assign trunc_ln44_12_fu_767_p4 = {{layer11_out_dout[285:264]}};

assign trunc_ln44_130_fu_1497_p4 = {{layer11_out_dout[1076:1056]}};

assign trunc_ln44_131_fu_1517_p4 = {{layer11_out_dout[1098:1078]}};

assign trunc_ln44_132_fu_1537_p4 = {{layer11_out_dout[1120:1100]}};

assign trunc_ln44_133_fu_1557_p4 = {{layer11_out_dout[1142:1122]}};

assign trunc_ln44_134_fu_1577_p4 = {{layer11_out_dout[1164:1144]}};

assign trunc_ln44_135_fu_1597_p4 = {{layer11_out_dout[1186:1166]}};

assign trunc_ln44_136_fu_1617_p4 = {{layer11_out_dout[1208:1188]}};

assign trunc_ln44_137_fu_1637_p4 = {{layer11_out_dout[1230:1210]}};

assign trunc_ln44_138_fu_1657_p4 = {{layer11_out_dout[1252:1232]}};

assign trunc_ln44_139_fu_1677_p4 = {{layer11_out_dout[1274:1254]}};

assign trunc_ln44_13_fu_787_p4 = {{layer11_out_dout[307:286]}};

assign trunc_ln44_140_fu_1697_p4 = {{layer11_out_dout[1296:1276]}};

assign trunc_ln44_141_fu_1717_p4 = {{layer11_out_dout[1318:1298]}};

assign trunc_ln44_142_fu_1737_p4 = {{layer11_out_dout[1340:1320]}};

assign trunc_ln44_143_fu_1757_p4 = {{layer11_out_dout[1362:1342]}};

assign trunc_ln44_144_fu_1777_p4 = {{layer11_out_dout[1384:1364]}};

assign trunc_ln44_145_fu_1797_p4 = {{layer11_out_dout[1406:1386]}};

assign trunc_ln44_146_fu_1817_p4 = {{layer11_out_dout[1428:1408]}};

assign trunc_ln44_147_fu_1837_p4 = {{layer11_out_dout[1450:1430]}};

assign trunc_ln44_148_fu_1857_p4 = {{layer11_out_dout[1472:1452]}};

assign trunc_ln44_149_fu_1877_p4 = {{layer11_out_dout[1494:1474]}};

assign trunc_ln44_14_fu_807_p4 = {{layer11_out_dout[329:308]}};

assign trunc_ln44_150_fu_1897_p4 = {{layer11_out_dout[1516:1496]}};

assign trunc_ln44_151_fu_1917_p4 = {{layer11_out_dout[1538:1518]}};

assign trunc_ln44_152_fu_1937_p4 = {{layer11_out_dout[1560:1540]}};

assign trunc_ln44_153_fu_1957_p4 = {{layer11_out_dout[1582:1562]}};

assign trunc_ln44_154_fu_1977_p4 = {{layer11_out_dout[1604:1584]}};

assign trunc_ln44_155_fu_1997_p4 = {{layer11_out_dout[1626:1606]}};

assign trunc_ln44_156_fu_2017_p4 = {{layer11_out_dout[1648:1628]}};

assign trunc_ln44_157_fu_2037_p4 = {{layer11_out_dout[1670:1650]}};

assign trunc_ln44_158_fu_2057_p4 = {{layer11_out_dout[1692:1672]}};

assign trunc_ln44_159_fu_2077_p4 = {{layer11_out_dout[1714:1694]}};

assign trunc_ln44_15_fu_827_p4 = {{layer11_out_dout[351:330]}};

assign trunc_ln44_160_fu_2097_p4 = {{layer11_out_dout[1736:1716]}};

assign trunc_ln44_161_fu_2117_p4 = {{layer11_out_dout[1758:1738]}};

assign trunc_ln44_162_fu_2137_p4 = {{layer11_out_dout[1780:1760]}};

assign trunc_ln44_163_fu_2157_p4 = {{layer11_out_dout[1802:1782]}};

assign trunc_ln44_164_fu_2177_p4 = {{layer11_out_dout[1824:1804]}};

assign trunc_ln44_166_fu_543_p1 = layer11_out_dout[20:0];

assign trunc_ln44_16_fu_847_p4 = {{layer11_out_dout[373:352]}};

assign trunc_ln44_17_fu_867_p4 = {{layer11_out_dout[395:374]}};

assign trunc_ln44_18_fu_887_p4 = {{layer11_out_dout[417:396]}};

assign trunc_ln44_19_fu_907_p4 = {{layer11_out_dout[439:418]}};

assign trunc_ln44_1_fu_547_p4 = {{layer11_out_dout[43:22]}};

assign trunc_ln44_20_fu_927_p4 = {{layer11_out_dout[461:440]}};

assign trunc_ln44_21_fu_947_p4 = {{layer11_out_dout[483:462]}};

assign trunc_ln44_22_fu_967_p4 = {{layer11_out_dout[505:484]}};

assign trunc_ln44_23_fu_987_p4 = {{layer11_out_dout[527:506]}};

assign trunc_ln44_24_fu_1007_p4 = {{layer11_out_dout[549:528]}};

assign trunc_ln44_25_fu_1027_p4 = {{layer11_out_dout[571:550]}};

assign trunc_ln44_26_fu_1047_p4 = {{layer11_out_dout[593:572]}};

assign trunc_ln44_27_fu_1067_p4 = {{layer11_out_dout[615:594]}};

assign trunc_ln44_28_fu_1087_p4 = {{layer11_out_dout[637:616]}};

assign trunc_ln44_29_fu_1107_p4 = {{layer11_out_dout[659:638]}};

assign trunc_ln44_2_fu_567_p4 = {{layer11_out_dout[65:44]}};

assign trunc_ln44_30_fu_1127_p4 = {{layer11_out_dout[681:660]}};

assign trunc_ln44_31_fu_1147_p4 = {{layer11_out_dout[703:682]}};

assign trunc_ln44_32_fu_1167_p4 = {{layer11_out_dout[725:704]}};

assign trunc_ln44_33_fu_1187_p4 = {{layer11_out_dout[747:726]}};

assign trunc_ln44_34_fu_1207_p4 = {{layer11_out_dout[769:748]}};

assign trunc_ln44_35_fu_1227_p4 = {{layer11_out_dout[791:770]}};

assign trunc_ln44_36_fu_1247_p4 = {{layer11_out_dout[813:792]}};

assign trunc_ln44_37_fu_1267_p4 = {{layer11_out_dout[835:814]}};

assign trunc_ln44_38_fu_1287_p4 = {{layer11_out_dout[857:836]}};

assign trunc_ln44_39_fu_1307_p4 = {{layer11_out_dout[879:858]}};

assign trunc_ln44_3_fu_587_p4 = {{layer11_out_dout[87:66]}};

assign trunc_ln44_40_fu_1327_p4 = {{layer11_out_dout[901:880]}};

assign trunc_ln44_41_fu_1347_p4 = {{layer11_out_dout[923:902]}};

assign trunc_ln44_42_fu_1367_p4 = {{layer11_out_dout[945:924]}};

assign trunc_ln44_43_fu_1387_p4 = {{layer11_out_dout[967:946]}};

assign trunc_ln44_44_fu_1407_p4 = {{layer11_out_dout[989:968]}};

assign trunc_ln44_45_fu_1427_p4 = {{layer11_out_dout[1011:990]}};

assign trunc_ln44_46_fu_1447_p4 = {{layer11_out_dout[1033:1012]}};

assign trunc_ln44_47_fu_1467_p4 = {{layer11_out_dout[1055:1034]}};

assign trunc_ln44_48_fu_1487_p4 = {{layer11_out_dout[1077:1056]}};

assign trunc_ln44_49_fu_1507_p4 = {{layer11_out_dout[1099:1078]}};

assign trunc_ln44_4_fu_607_p4 = {{layer11_out_dout[109:88]}};

assign trunc_ln44_50_fu_1527_p4 = {{layer11_out_dout[1121:1100]}};

assign trunc_ln44_51_fu_1547_p4 = {{layer11_out_dout[1143:1122]}};

assign trunc_ln44_52_fu_1567_p4 = {{layer11_out_dout[1165:1144]}};

assign trunc_ln44_53_fu_1587_p4 = {{layer11_out_dout[1187:1166]}};

assign trunc_ln44_54_fu_1607_p4 = {{layer11_out_dout[1209:1188]}};

assign trunc_ln44_55_fu_1627_p4 = {{layer11_out_dout[1231:1210]}};

assign trunc_ln44_56_fu_1647_p4 = {{layer11_out_dout[1253:1232]}};

assign trunc_ln44_57_fu_1667_p4 = {{layer11_out_dout[1275:1254]}};

assign trunc_ln44_58_fu_1687_p4 = {{layer11_out_dout[1297:1276]}};

assign trunc_ln44_59_fu_1707_p4 = {{layer11_out_dout[1319:1298]}};

assign trunc_ln44_5_fu_627_p4 = {{layer11_out_dout[131:110]}};

assign trunc_ln44_60_fu_1727_p4 = {{layer11_out_dout[1341:1320]}};

assign trunc_ln44_61_fu_1747_p4 = {{layer11_out_dout[1363:1342]}};

assign trunc_ln44_62_fu_1767_p4 = {{layer11_out_dout[1385:1364]}};

assign trunc_ln44_63_fu_1787_p4 = {{layer11_out_dout[1407:1386]}};

assign trunc_ln44_64_fu_1807_p4 = {{layer11_out_dout[1429:1408]}};

assign trunc_ln44_65_fu_1827_p4 = {{layer11_out_dout[1451:1430]}};

assign trunc_ln44_66_fu_1847_p4 = {{layer11_out_dout[1473:1452]}};

assign trunc_ln44_67_fu_1867_p4 = {{layer11_out_dout[1495:1474]}};

assign trunc_ln44_68_fu_1887_p4 = {{layer11_out_dout[1517:1496]}};

assign trunc_ln44_69_fu_1907_p4 = {{layer11_out_dout[1539:1518]}};

assign trunc_ln44_6_fu_647_p4 = {{layer11_out_dout[153:132]}};

assign trunc_ln44_70_fu_1927_p4 = {{layer11_out_dout[1561:1540]}};

assign trunc_ln44_71_fu_1947_p4 = {{layer11_out_dout[1583:1562]}};

assign trunc_ln44_72_fu_1967_p4 = {{layer11_out_dout[1605:1584]}};

assign trunc_ln44_73_fu_1987_p4 = {{layer11_out_dout[1627:1606]}};

assign trunc_ln44_74_fu_2007_p4 = {{layer11_out_dout[1649:1628]}};

assign trunc_ln44_75_fu_2027_p4 = {{layer11_out_dout[1671:1650]}};

assign trunc_ln44_76_fu_2047_p4 = {{layer11_out_dout[1693:1672]}};

assign trunc_ln44_77_fu_2067_p4 = {{layer11_out_dout[1715:1694]}};

assign trunc_ln44_78_fu_2087_p4 = {{layer11_out_dout[1737:1716]}};

assign trunc_ln44_79_fu_2107_p4 = {{layer11_out_dout[1759:1738]}};

assign trunc_ln44_7_fu_667_p4 = {{layer11_out_dout[175:154]}};

assign trunc_ln44_80_fu_2127_p4 = {{layer11_out_dout[1781:1760]}};

assign trunc_ln44_81_fu_2147_p4 = {{layer11_out_dout[1803:1782]}};

assign trunc_ln44_82_fu_2167_p4 = {{layer11_out_dout[1825:1804]}};

assign trunc_ln44_83_fu_2187_p4 = {{layer11_out_dout[1847:1826]}};

assign trunc_ln44_84_fu_577_p4 = {{layer11_out_dout[64:44]}};

assign trunc_ln44_85_fu_597_p4 = {{layer11_out_dout[86:66]}};

assign trunc_ln44_86_fu_617_p4 = {{layer11_out_dout[108:88]}};

assign trunc_ln44_87_fu_637_p4 = {{layer11_out_dout[130:110]}};

assign trunc_ln44_88_fu_657_p4 = {{layer11_out_dout[152:132]}};

assign trunc_ln44_89_fu_677_p4 = {{layer11_out_dout[174:154]}};

assign trunc_ln44_8_fu_687_p4 = {{layer11_out_dout[197:176]}};

assign trunc_ln44_90_fu_697_p4 = {{layer11_out_dout[196:176]}};

assign trunc_ln44_91_fu_717_p4 = {{layer11_out_dout[218:198]}};

assign trunc_ln44_92_fu_737_p4 = {{layer11_out_dout[240:220]}};

assign trunc_ln44_93_fu_757_p4 = {{layer11_out_dout[262:242]}};

assign trunc_ln44_94_fu_777_p4 = {{layer11_out_dout[284:264]}};

assign trunc_ln44_95_fu_797_p4 = {{layer11_out_dout[306:286]}};

assign trunc_ln44_96_fu_817_p4 = {{layer11_out_dout[328:308]}};

assign trunc_ln44_97_fu_837_p4 = {{layer11_out_dout[350:330]}};

assign trunc_ln44_98_fu_857_p4 = {{layer11_out_dout[372:352]}};

assign trunc_ln44_99_fu_877_p4 = {{layer11_out_dout[394:374]}};

assign trunc_ln44_9_fu_707_p4 = {{layer11_out_dout[219:198]}};

assign trunc_ln44_fu_539_p1 = layer11_out_dout[21:0];

assign trunc_ln44_s_fu_557_p4 = {{layer11_out_dout[42:22]}};

assign zext_ln51_10_fu_2401_p1 = select_ln51_10_fu_2393_p3;

assign zext_ln51_11_fu_2419_p1 = select_ln51_11_fu_2411_p3;

assign zext_ln51_12_fu_2437_p1 = select_ln51_12_fu_2429_p3;

assign zext_ln51_13_fu_2455_p1 = select_ln51_13_fu_2447_p3;

assign zext_ln51_14_fu_2473_p1 = select_ln51_14_fu_2465_p3;

assign zext_ln51_15_fu_2491_p1 = select_ln51_15_fu_2483_p3;

assign zext_ln51_16_fu_2509_p1 = select_ln51_16_fu_2501_p3;

assign zext_ln51_17_fu_2527_p1 = select_ln51_17_fu_2519_p3;

assign zext_ln51_18_fu_2545_p1 = select_ln51_18_fu_2537_p3;

assign zext_ln51_19_fu_2563_p1 = select_ln51_19_fu_2555_p3;

assign zext_ln51_1_fu_2239_p1 = select_ln51_1_fu_2231_p3;

assign zext_ln51_20_fu_2581_p1 = select_ln51_20_fu_2573_p3;

assign zext_ln51_21_fu_2599_p1 = select_ln51_21_fu_2591_p3;

assign zext_ln51_22_fu_2617_p1 = select_ln51_22_fu_2609_p3;

assign zext_ln51_23_fu_2635_p1 = select_ln51_23_fu_2627_p3;

assign zext_ln51_24_fu_2653_p1 = select_ln51_24_fu_2645_p3;

assign zext_ln51_25_fu_2671_p1 = select_ln51_25_fu_2663_p3;

assign zext_ln51_26_fu_2689_p1 = select_ln51_26_fu_2681_p3;

assign zext_ln51_27_fu_2707_p1 = select_ln51_27_fu_2699_p3;

assign zext_ln51_28_fu_2725_p1 = select_ln51_28_fu_2717_p3;

assign zext_ln51_29_fu_2743_p1 = select_ln51_29_fu_2735_p3;

assign zext_ln51_2_fu_2257_p1 = select_ln51_2_fu_2249_p3;

assign zext_ln51_30_fu_2761_p1 = select_ln51_30_fu_2753_p3;

assign zext_ln51_31_fu_2779_p1 = select_ln51_31_fu_2771_p3;

assign zext_ln51_32_fu_2797_p1 = select_ln51_32_fu_2789_p3;

assign zext_ln51_33_fu_2815_p1 = select_ln51_33_fu_2807_p3;

assign zext_ln51_34_fu_2833_p1 = select_ln51_34_fu_2825_p3;

assign zext_ln51_35_fu_2851_p1 = select_ln51_35_fu_2843_p3;

assign zext_ln51_36_fu_2869_p1 = select_ln51_36_fu_2861_p3;

assign zext_ln51_37_fu_2887_p1 = select_ln51_37_fu_2879_p3;

assign zext_ln51_38_fu_2905_p1 = select_ln51_38_fu_2897_p3;

assign zext_ln51_39_fu_2923_p1 = select_ln51_39_fu_2915_p3;

assign zext_ln51_3_fu_2275_p1 = select_ln51_3_fu_2267_p3;

assign zext_ln51_40_fu_2941_p1 = select_ln51_40_fu_2933_p3;

assign zext_ln51_41_fu_2959_p1 = select_ln51_41_fu_2951_p3;

assign zext_ln51_42_fu_2977_p1 = select_ln51_42_fu_2969_p3;

assign zext_ln51_43_fu_2995_p1 = select_ln51_43_fu_2987_p3;

assign zext_ln51_44_fu_3013_p1 = select_ln51_44_fu_3005_p3;

assign zext_ln51_45_fu_3031_p1 = select_ln51_45_fu_3023_p3;

assign zext_ln51_46_fu_3049_p1 = select_ln51_46_fu_3041_p3;

assign zext_ln51_47_fu_3067_p1 = select_ln51_47_fu_3059_p3;

assign zext_ln51_48_fu_3085_p1 = select_ln51_48_fu_3077_p3;

assign zext_ln51_49_fu_3103_p1 = select_ln51_49_fu_3095_p3;

assign zext_ln51_4_fu_2293_p1 = select_ln51_4_fu_2285_p3;

assign zext_ln51_50_fu_3121_p1 = select_ln51_50_fu_3113_p3;

assign zext_ln51_51_fu_3139_p1 = select_ln51_51_fu_3131_p3;

assign zext_ln51_52_fu_3157_p1 = select_ln51_52_fu_3149_p3;

assign zext_ln51_53_fu_3175_p1 = select_ln51_53_fu_3167_p3;

assign zext_ln51_54_fu_3193_p1 = select_ln51_54_fu_3185_p3;

assign zext_ln51_55_fu_3211_p1 = select_ln51_55_fu_3203_p3;

assign zext_ln51_56_fu_3229_p1 = select_ln51_56_fu_3221_p3;

assign zext_ln51_57_fu_3247_p1 = select_ln51_57_fu_3239_p3;

assign zext_ln51_58_fu_3265_p1 = select_ln51_58_fu_3257_p3;

assign zext_ln51_59_fu_3283_p1 = select_ln51_59_fu_3275_p3;

assign zext_ln51_5_fu_2311_p1 = select_ln51_5_fu_2303_p3;

assign zext_ln51_60_fu_3301_p1 = select_ln51_60_fu_3293_p3;

assign zext_ln51_61_fu_3319_p1 = select_ln51_61_fu_3311_p3;

assign zext_ln51_62_fu_3337_p1 = select_ln51_62_fu_3329_p3;

assign zext_ln51_63_fu_3355_p1 = select_ln51_63_fu_3347_p3;

assign zext_ln51_64_fu_3373_p1 = select_ln51_64_fu_3365_p3;

assign zext_ln51_65_fu_3391_p1 = select_ln51_65_fu_3383_p3;

assign zext_ln51_66_fu_3409_p1 = select_ln51_66_fu_3401_p3;

assign zext_ln51_67_fu_3427_p1 = select_ln51_67_fu_3419_p3;

assign zext_ln51_68_fu_3445_p1 = select_ln51_68_fu_3437_p3;

assign zext_ln51_69_fu_3463_p1 = select_ln51_69_fu_3455_p3;

assign zext_ln51_6_fu_2329_p1 = select_ln51_6_fu_2321_p3;

assign zext_ln51_70_fu_3481_p1 = select_ln51_70_fu_3473_p3;

assign zext_ln51_71_fu_3499_p1 = select_ln51_71_fu_3491_p3;

assign zext_ln51_72_fu_3517_p1 = select_ln51_72_fu_3509_p3;

assign zext_ln51_73_fu_3535_p1 = select_ln51_73_fu_3527_p3;

assign zext_ln51_74_fu_3553_p1 = select_ln51_74_fu_3545_p3;

assign zext_ln51_75_fu_3571_p1 = select_ln51_75_fu_3563_p3;

assign zext_ln51_76_fu_3589_p1 = select_ln51_76_fu_3581_p3;

assign zext_ln51_77_fu_3607_p1 = select_ln51_77_fu_3599_p3;

assign zext_ln51_78_fu_3625_p1 = select_ln51_78_fu_3617_p3;

assign zext_ln51_79_fu_3643_p1 = select_ln51_79_fu_3635_p3;

assign zext_ln51_7_fu_2347_p1 = select_ln51_7_fu_2339_p3;

assign zext_ln51_80_fu_3661_p1 = select_ln51_80_fu_3653_p3;

assign zext_ln51_81_fu_3679_p1 = select_ln51_81_fu_3671_p3;

assign zext_ln51_82_fu_3697_p1 = select_ln51_82_fu_3689_p3;

assign zext_ln51_8_fu_2365_p1 = select_ln51_8_fu_2357_p3;

assign zext_ln51_9_fu_2383_p1 = select_ln51_9_fu_2375_p3;

assign zext_ln51_fu_2221_p1 = select_ln51_fu_2213_p3;

endmodule //lenet_mnist_cap64_hls_relu_array_ap_fixed_84u_array_ap_fixed_22_12_4_0_0_84u_relu_config12_s
