// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module lenet_mnist_cap64_hls_pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_22_12_4_0_0_6u_config4_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer4_out_din,
        layer4_out_full_n,
        layer4_out_write,
        layer4_out_num_data_valid,
        layer4_out_fifo_cap,
        layer3_out_dout,
        layer3_out_empty_n,
        layer3_out_read,
        layer3_out_num_data_valid,
        layer3_out_fifo_cap,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [131:0] layer4_out_din;
input   layer4_out_full_n;
output   layer4_out_write;
input  [8:0] layer4_out_num_data_valid;
input  [8:0] layer4_out_fifo_cap;
input  [131:0] layer3_out_dout;
input   layer3_out_empty_n;
output   layer3_out_read;
input  [10:0] layer3_out_num_data_valid;
input  [10:0] layer3_out_fifo_cap;
output   start_out;
output   start_write;

reg ap_idle;
reg layer4_out_write;
reg layer3_out_read;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    internal_ap_ready;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_done_reg;
reg    ap_block_pp0_stage1_subdone;
reg   [0:0] icmp_ln109_reg_978;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [31:0] sY;
reg   [31:0] pY;
reg   [21:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9;
reg   [21:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3;
reg   [21:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_11;
reg   [21:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_5;
reg   [21:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8;
reg   [21:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2;
reg   [21:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_10;
reg   [21:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_4;
reg   [21:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7;
reg   [21:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1;
reg   [21:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_9;
reg   [21:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_3;
reg   [21:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6;
reg   [21:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel;
reg   [21:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_8;
reg   [21:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_2;
reg   [21:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5;
reg   [21:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_13;
reg   [21:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_7;
reg   [21:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_1;
reg   [21:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4;
reg   [21:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_12;
reg   [21:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_6;
reg   [21:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a;
reg   [31:0] pX;
reg   [31:0] sX;
reg    layer3_out_blk_n;
wire    ap_block_pp0_stage1_grp1;
reg    layer4_out_blk_n;
wire    ap_block_pp0_stage0_grp2;
reg   [0:0] icmp_ln55_reg_957;
reg   [0:0] and_ln55_1_reg_961;
wire   [0:0] icmp_ln55_fu_244_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_predicate_op143_write_state3;
reg    ap_block_state3_pp0_stage0_iter1_grp2;
reg    ap_block_pp0_stage0_11001_grp2;
wire   [0:0] and_ln55_1_fu_292_p2;
wire   [0:0] icmp_ln76_fu_304_p2;
reg   [0:0] icmp_ln76_reg_965;
wire   [0:0] icmp_ln80_fu_358_p2;
wire   [31:0] select_ln86_fu_386_p3;
wire   [0:0] icmp_ln109_fu_400_p2;
reg    ap_block_pp0_stage0_11001;
reg    ap_block_pp0_stage0_subdone;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_ap_start;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_ap_done;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_ap_idle;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_ap_ready;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_read;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_read1;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_read2;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_read3;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_read4;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_read5;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_o;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_o_ap_vld;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9_ap_vld;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o_ap_vld;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_ap_vld;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o_ap_vld;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7_ap_vld;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o_ap_vld;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6_ap_vld;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_13_o;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_13_o_ap_vld;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5_ap_vld;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_12_o;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_12_o_ap_vld;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4_ap_vld;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_5_o;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_5_o_ap_vld;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_11;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_11_ap_vld;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_4_o;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_4_o_ap_vld;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_10;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_10_ap_vld;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_3_o;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_3_o_ap_vld;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_9;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_9_ap_vld;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_2_o;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_2_o_ap_vld;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_8;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_8_ap_vld;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_1_o;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_1_o_ap_vld;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_7;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_7_ap_vld;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_o;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_o_ap_vld;
wire   [21:0] call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_6;
wire    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_6_ap_vld;
reg    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_ap_ce;
reg    ap_block_pp0_stage1_11001_ignoreCallOp60;
reg    ap_block_pp0_stage1_11001_ignoreCallOp60_grp1;
reg   [31:0] ap_phi_reg_pp0_iter0_storemerge_i_reg_151;
reg    ap_block_pp0_stage1_11001_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
reg    ap_block_pp0_stage1_subdone_grp0;
reg    call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_ap_start_reg;
wire    ap_block_pp0_stage1_ignoreCallOp60_grp1;
wire   [31:0] add_ln80_fu_352_p2;
wire   [31:0] add_ln76_fu_298_p2;
wire   [31:0] select_ln91_fu_322_p3;
reg   [9:0] indvar_flatten2_fu_134;
wire   [9:0] add_ln109_fu_254_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_indvar_flatten2_load;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage1_11001_grp1;
reg    ap_block_pp0_stage0_01001_grp2;
wire   [0:0] icmp_ln55_2_fu_274_p2;
wire   [0:0] icmp_ln55_3_fu_280_p2;
wire   [0:0] and_ln55_fu_286_p2;
wire   [0:0] icmp_ln55_1_fu_264_p2;
wire   [31:0] add_ln91_fu_316_p2;
wire   [0:0] icmp_ln86_fu_374_p2;
wire   [31:0] add_ln86_fu_380_p2;
wire   [0:0] icmp_ln66_fu_493_p2;
wire   [0:0] xor_ln66_fu_499_p2;
wire   [0:0] icmp_ln66_1_fu_513_p2;
wire   [0:0] xor_ln66_1_fu_519_p2;
wire   [21:0] select_ln0_fu_505_p3;
wire   [21:0] select_ln0_1_fu_525_p3;
wire   [0:0] icmp_ln66_2_fu_533_p2;
wire   [0:0] xor_ln66_2_fu_539_p2;
wire   [0:0] icmp_ln66_3_fu_569_p2;
wire   [0:0] xor_ln66_3_fu_575_p2;
wire   [0:0] icmp_ln66_4_fu_589_p2;
wire   [0:0] xor_ln66_4_fu_595_p2;
wire   [21:0] select_ln0_2_fu_581_p3;
wire   [21:0] select_ln0_3_fu_601_p3;
wire   [0:0] icmp_ln66_5_fu_609_p2;
wire   [0:0] xor_ln66_5_fu_615_p2;
wire   [0:0] icmp_ln66_6_fu_645_p2;
wire   [0:0] xor_ln66_6_fu_651_p2;
wire   [0:0] icmp_ln66_7_fu_665_p2;
wire   [0:0] xor_ln66_7_fu_671_p2;
wire   [21:0] select_ln0_4_fu_657_p3;
wire   [21:0] select_ln0_5_fu_677_p3;
wire   [0:0] icmp_ln66_8_fu_685_p2;
wire   [0:0] xor_ln66_8_fu_691_p2;
wire   [0:0] icmp_ln66_9_fu_721_p2;
wire   [0:0] xor_ln66_9_fu_727_p2;
wire   [0:0] icmp_ln66_10_fu_741_p2;
wire   [0:0] xor_ln66_10_fu_747_p2;
wire   [21:0] select_ln0_6_fu_733_p3;
wire   [21:0] select_ln0_7_fu_753_p3;
wire   [0:0] icmp_ln66_11_fu_761_p2;
wire   [0:0] xor_ln66_11_fu_767_p2;
wire   [0:0] icmp_ln66_12_fu_797_p2;
wire   [0:0] xor_ln66_12_fu_803_p2;
wire   [0:0] icmp_ln66_13_fu_817_p2;
wire   [0:0] xor_ln66_13_fu_823_p2;
wire   [21:0] select_ln0_8_fu_809_p3;
wire   [21:0] select_ln0_9_fu_829_p3;
wire   [0:0] icmp_ln66_14_fu_837_p2;
wire   [0:0] xor_ln66_14_fu_843_p2;
wire   [0:0] icmp_ln66_15_fu_873_p2;
wire   [0:0] xor_ln66_15_fu_879_p2;
wire   [0:0] icmp_ln66_16_fu_893_p2;
wire   [0:0] xor_ln66_16_fu_899_p2;
wire   [21:0] select_ln0_10_fu_885_p3;
wire   [21:0] select_ln0_11_fu_905_p3;
wire   [0:0] icmp_ln66_17_fu_913_p2;
wire   [0:0] xor_ln66_17_fu_919_p2;
wire   [21:0] res_pack_5_fu_925_p3;
wire   [21:0] res_pack_4_fu_849_p3;
wire   [21:0] res_pack_3_fu_773_p3;
wire   [21:0] res_pack_2_fu_697_p3;
wire   [21:0] res_pack_1_fu_621_p3;
wire   [21:0] res_pack_fu_545_p3;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_block_pp0_stage1_11001;
reg    ap_condition_exit_pp0_iter1_stage0;
reg    ap_idle_pp0_0to0;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_done_sig;
reg    ap_condition_398;
reg    ap_condition_271;
reg    ap_condition_250;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 sY = 32'd0;
#0 pY = 32'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9 = 22'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3 = 22'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_11 = 22'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_5 = 22'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8 = 22'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2 = 22'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_10 = 22'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_4 = 22'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7 = 22'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1 = 22'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_9 = 22'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_3 = 22'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6 = 22'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel = 22'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_8 = 22'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_2 = 22'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5 = 22'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_13 = 22'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_7 = 22'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_1 = 22'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4 = 22'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_12 = 22'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_6 = 22'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a = 22'd0;
#0 pX = 32'd0;
#0 sX = 32'd0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_ap_start_reg = 1'b0;
#0 indvar_flatten2_fu_134 = 10'd0;
end

lenet_mnist_cap64_hls_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_ap_start),
    .ap_done(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_ap_done),
    .ap_idle(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_ap_idle),
    .ap_ready(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_ap_ready),
    .p_read(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_read),
    .p_read1(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_read1),
    .p_read2(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_read2),
    .p_read3(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_read3),
    .p_read4(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_read4),
    .p_read5(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_read5),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_i(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_o(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_o),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_o_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_o_ap_vld),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9_ap_vld),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_i(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o_ap_vld),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_ap_vld),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_i(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o_ap_vld),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7_ap_vld),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_i(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o_ap_vld),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6_ap_vld),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_13_i(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_13),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_13_o(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_13_o),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_13_o_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_13_o_ap_vld),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5_ap_vld),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_12_i(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_12),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_12_o(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_12_o),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_12_o_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_12_o_ap_vld),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4_ap_vld),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_5_i(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_5),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_5_o(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_5_o),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_5_o_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_5_o_ap_vld),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_11(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_11),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_11_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_11_ap_vld),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_4_i(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_4),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_4_o(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_4_o),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_4_o_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_4_o_ap_vld),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_10(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_10),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_10_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_10_ap_vld),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_3_i(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_3),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_3_o(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_3_o),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_3_o_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_3_o_ap_vld),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_9(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_9),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_9_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_9_ap_vld),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_2_i(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_2),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_2_o(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_2_o),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_2_o_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_2_o_ap_vld),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_8(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_8),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_8_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_8_ap_vld),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_1_i(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_1),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_1_o(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_1_o),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_1_o_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_1_o_ap_vld),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_7(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_7),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_7_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_7_ap_vld),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_i(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_o(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_o),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_o_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_o_ap_vld),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_6(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_6),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_6_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_6_ap_vld),
    .ap_ce(call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_ap_ce)
);

lenet_mnist_cap64_hls_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_ap_start_reg <= 1'b1;
        end else if ((call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_ap_ready == 1'b1)) begin
            call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage0)))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_398)) begin
        if ((icmp_ln80_fu_358_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_storemerge_i_reg_151 <= 32'd0;
        end else if ((icmp_ln80_fu_358_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_storemerge_i_reg_151 <= select_ln86_fu_386_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_271)) begin
        indvar_flatten2_fu_134 <= add_ln109_fu_254_p2;
    end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_250)) begin
    if ((icmp_ln76_fu_304_p2 == 1'd1)) begin
        pX <= 32'd0;
    end else if ((icmp_ln76_fu_304_p2 == 1'd0)) begin
        pX <= add_ln76_fu_298_p2;
    end
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_398)) begin
    if ((icmp_ln80_fu_358_p2 == 1'd1)) begin
        pY <= 32'd0;
    end else if ((icmp_ln80_fu_358_p2 == 1'd0)) begin
        pY <= add_ln80_fu_352_p2;
    end
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_250)) begin
    if ((icmp_ln76_fu_304_p2 == 1'd1)) begin
        sX <= 32'd0;
    end else if ((icmp_ln76_fu_304_p2 == 1'd0)) begin
        sX <= select_ln91_fu_322_p3;
    end
end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln55_1_reg_961 <= and_ln55_1_fu_292_p2;
        icmp_ln55_reg_957 <= icmp_ln55_fu_244_p2;
        icmp_ln76_reg_965 <= icmp_ln76_fu_304_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln109_reg_978 <= icmp_ln109_fu_400_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a <= call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_1 <= call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_10_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_10 <= call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_10;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_11_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_11 <= call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_11;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_12_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_12 <= call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_12_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_13_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_13 <= call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_13_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_2 <= call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_3 <= call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_4 <= call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_4_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_5 <= call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_5_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_6_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_6 <= call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_7_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_7 <= call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_7;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_8_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_8 <= call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_8;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_9_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_9 <= call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_9;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln76_reg_965 == 1'd1))) begin
        sY <= ap_phi_reg_pp0_iter0_storemerge_i_reg_151;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o_ap_vld == 1'b1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel <= call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o_ap_vld == 1'b1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1 <= call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o_ap_vld == 1'b1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2 <= call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_o_ap_vld == 1'b1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3 <= call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4 <= call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5 <= call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6_ap_vld == 1'b1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6 <= call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7_ap_vld == 1'b1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7 <= call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_ap_vld == 1'b1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8 <= call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9_ap_vld == 1'b1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9 <= call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9;
    end
end

always @ (*) begin
    if (((icmp_ln109_reg_978 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln109_reg_978 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten2_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten2_load = indvar_flatten2_fu_134;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001_ignoreCallOp60_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_ap_ce = 1'b1;
    end else begin
        call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        layer3_out_blk_n = layer3_out_empty_n;
    end else begin
        layer3_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        layer3_out_read = 1'b1;
    end else begin
        layer3_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln55_1_reg_961) & (1'b0 == ap_block_pp0_stage0_grp2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln55_reg_957 == 1'd1))) begin
        layer4_out_blk_n = layer4_out_full_n;
    end else begin
        layer4_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op143_write_state3 == 1'b1))) begin
        layer4_out_write = 1'b1;
    end else begin
        layer4_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln109_fu_254_p2 = (ap_sig_allocacmp_indvar_flatten2_load + 10'd1);

assign add_ln76_fu_298_p2 = (pX + 32'd1);

assign add_ln80_fu_352_p2 = (pY + 32'd1);

assign add_ln86_fu_380_p2 = (sY + 32'd1);

assign add_ln91_fu_316_p2 = (sX + 32'd1);

assign and_ln55_1_fu_292_p2 = (icmp_ln55_1_fu_264_p2 & and_ln55_fu_286_p2);

assign and_ln55_fu_286_p2 = (icmp_ln55_3_fu_280_p2 & icmp_ln55_2_fu_274_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp2 = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1_grp2)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1_grp2)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp2 = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1_grp2)));
end

assign ap_block_pp0_stage0_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1_grp2)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (layer3_out_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp1 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (layer3_out_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_ignoreCallOp60 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (layer3_out_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_ignoreCallOp60_grp1 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (layer3_out_empty_n == 1'b0)));
end

assign ap_block_pp0_stage1_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_ignoreCallOp60_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (layer3_out_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1_grp2 = ((layer4_out_full_n == 1'b0) & (ap_predicate_op143_write_state3 == 1'b1));
end

always @ (*) begin
    ap_condition_250 = ((1'b0 == ap_block_pp0_stage0_11001_grp2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_271 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_398 = ((1'b0 == ap_block_pp0_stage0_11001_grp2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln76_fu_304_p2 == 1'd1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

always @ (*) begin
    ap_predicate_op143_write_state3 = ((1'd1 == and_ln55_1_reg_961) & (icmp_ln55_reg_957 == 1'd1));
end

assign ap_ready = internal_ap_ready;

assign call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_ap_start = call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_ap_start_reg;

assign call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_read = layer3_out_dout[21:0];

assign call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_read1 = {{layer3_out_dout[43:22]}};

assign call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_read2 = {{layer3_out_dout[65:44]}};

assign call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_read3 = {{layer3_out_dout[87:66]}};

assign call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_read4 = {{layer3_out_dout[109:88]}};

assign call_ln52_shift_line_buffer_array_ap_fixed_22_12_4_0_0_6u_config4_s_fu_162_p_read5 = {{layer3_out_dout[131:110]}};

assign icmp_ln109_fu_400_p2 = ((ap_sig_allocacmp_indvar_flatten2_load == 10'd575) ? 1'b1 : 1'b0);

assign icmp_ln55_1_fu_264_p2 = ((sY == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln55_2_fu_274_p2 = (($signed(pY) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln55_3_fu_280_p2 = (($signed(pX) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_244_p2 = ((sX == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln66_10_fu_741_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_8) < $signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_2)) ? 1'b1 : 1'b0);

assign icmp_ln66_11_fu_761_p2 = (($signed(select_ln0_6_fu_733_p3) < $signed(select_ln0_7_fu_753_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_12_fu_797_p2 = (($signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5) < $signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_13)) ? 1'b1 : 1'b0);

assign icmp_ln66_13_fu_817_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_7) < $signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_1)) ? 1'b1 : 1'b0);

assign icmp_ln66_14_fu_837_p2 = (($signed(select_ln0_8_fu_809_p3) < $signed(select_ln0_9_fu_829_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_15_fu_873_p2 = (($signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4) < $signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_12)) ? 1'b1 : 1'b0);

assign icmp_ln66_16_fu_893_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_6) < $signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a)) ? 1'b1 : 1'b0);

assign icmp_ln66_17_fu_913_p2 = (($signed(select_ln0_10_fu_885_p3) < $signed(select_ln0_11_fu_905_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_1_fu_513_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_11) < $signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_5)) ? 1'b1 : 1'b0);

assign icmp_ln66_2_fu_533_p2 = (($signed(select_ln0_fu_505_p3) < $signed(select_ln0_1_fu_525_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_3_fu_569_p2 = (($signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8) < $signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2)) ? 1'b1 : 1'b0);

assign icmp_ln66_4_fu_589_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_10) < $signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_4)) ? 1'b1 : 1'b0);

assign icmp_ln66_5_fu_609_p2 = (($signed(select_ln0_2_fu_581_p3) < $signed(select_ln0_3_fu_601_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_6_fu_645_p2 = (($signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7) < $signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1)) ? 1'b1 : 1'b0);

assign icmp_ln66_7_fu_665_p2 = (($signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_9) < $signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_3)) ? 1'b1 : 1'b0);

assign icmp_ln66_8_fu_685_p2 = (($signed(select_ln0_4_fu_657_p3) < $signed(select_ln0_5_fu_677_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_9_fu_721_p2 = (($signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6) < $signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel)) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_493_p2 = (($signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9) < $signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3)) ? 1'b1 : 1'b0);

assign icmp_ln76_fu_304_p2 = ((add_ln76_fu_298_p2 == 32'd24) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_358_p2 = ((add_ln80_fu_352_p2 == 32'd24) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_374_p2 = ((sY == 32'd1) ? 1'b1 : 1'b0);

assign layer4_out_din = {{{{{{res_pack_5_fu_925_p3}, {res_pack_4_fu_849_p3}}, {res_pack_3_fu_773_p3}}, {res_pack_2_fu_697_p3}}, {res_pack_1_fu_621_p3}}, {res_pack_fu_545_p3}};

assign res_pack_1_fu_621_p3 = ((xor_ln66_5_fu_615_p2[0:0] == 1'b1) ? select_ln0_2_fu_581_p3 : select_ln0_3_fu_601_p3);

assign res_pack_2_fu_697_p3 = ((xor_ln66_8_fu_691_p2[0:0] == 1'b1) ? select_ln0_4_fu_657_p3 : select_ln0_5_fu_677_p3);

assign res_pack_3_fu_773_p3 = ((xor_ln66_11_fu_767_p2[0:0] == 1'b1) ? select_ln0_6_fu_733_p3 : select_ln0_7_fu_753_p3);

assign res_pack_4_fu_849_p3 = ((xor_ln66_14_fu_843_p2[0:0] == 1'b1) ? select_ln0_8_fu_809_p3 : select_ln0_9_fu_829_p3);

assign res_pack_5_fu_925_p3 = ((xor_ln66_17_fu_919_p2[0:0] == 1'b1) ? select_ln0_10_fu_885_p3 : select_ln0_11_fu_905_p3);

assign res_pack_fu_545_p3 = ((xor_ln66_2_fu_539_p2[0:0] == 1'b1) ? select_ln0_fu_505_p3 : select_ln0_1_fu_525_p3);

assign select_ln0_10_fu_885_p3 = ((xor_ln66_15_fu_879_p2[0:0] == 1'b1) ? void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4 : p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_12);

assign select_ln0_11_fu_905_p3 = ((xor_ln66_16_fu_899_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_6 : p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a);

assign select_ln0_1_fu_525_p3 = ((xor_ln66_1_fu_519_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_11 : p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_5);

assign select_ln0_2_fu_581_p3 = ((xor_ln66_3_fu_575_p2[0:0] == 1'b1) ? void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8 : void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2);

assign select_ln0_3_fu_601_p3 = ((xor_ln66_4_fu_595_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_10 : p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_4);

assign select_ln0_4_fu_657_p3 = ((xor_ln66_6_fu_651_p2[0:0] == 1'b1) ? void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7 : void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1);

assign select_ln0_5_fu_677_p3 = ((xor_ln66_7_fu_671_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_9 : p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_3);

assign select_ln0_6_fu_733_p3 = ((xor_ln66_9_fu_727_p2[0:0] == 1'b1) ? void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6 : void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel);

assign select_ln0_7_fu_753_p3 = ((xor_ln66_10_fu_747_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_8 : p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_2);

assign select_ln0_8_fu_809_p3 = ((xor_ln66_12_fu_803_p2[0:0] == 1'b1) ? void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5 : p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_13);

assign select_ln0_9_fu_829_p3 = ((xor_ln66_13_fu_823_p2[0:0] == 1'b1) ? p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_7 : p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi22ELi12EL9ap_q_mode4EL9a_1);

assign select_ln0_fu_505_p3 = ((xor_ln66_fu_499_p2[0:0] == 1'b1) ? void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9 : void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3);

assign select_ln86_fu_386_p3 = ((icmp_ln86_fu_374_p2[0:0] == 1'b1) ? 32'd0 : add_ln86_fu_380_p2);

assign select_ln91_fu_322_p3 = ((icmp_ln55_fu_244_p2[0:0] == 1'b1) ? 32'd0 : add_ln91_fu_316_p2);

assign start_out = real_start;

assign xor_ln66_10_fu_747_p2 = (icmp_ln66_10_fu_741_p2 ^ 1'd1);

assign xor_ln66_11_fu_767_p2 = (icmp_ln66_11_fu_761_p2 ^ 1'd1);

assign xor_ln66_12_fu_803_p2 = (icmp_ln66_12_fu_797_p2 ^ 1'd1);

assign xor_ln66_13_fu_823_p2 = (icmp_ln66_13_fu_817_p2 ^ 1'd1);

assign xor_ln66_14_fu_843_p2 = (icmp_ln66_14_fu_837_p2 ^ 1'd1);

assign xor_ln66_15_fu_879_p2 = (icmp_ln66_15_fu_873_p2 ^ 1'd1);

assign xor_ln66_16_fu_899_p2 = (icmp_ln66_16_fu_893_p2 ^ 1'd1);

assign xor_ln66_17_fu_919_p2 = (icmp_ln66_17_fu_913_p2 ^ 1'd1);

assign xor_ln66_1_fu_519_p2 = (icmp_ln66_1_fu_513_p2 ^ 1'd1);

assign xor_ln66_2_fu_539_p2 = (icmp_ln66_2_fu_533_p2 ^ 1'd1);

assign xor_ln66_3_fu_575_p2 = (icmp_ln66_3_fu_569_p2 ^ 1'd1);

assign xor_ln66_4_fu_595_p2 = (icmp_ln66_4_fu_589_p2 ^ 1'd1);

assign xor_ln66_5_fu_615_p2 = (icmp_ln66_5_fu_609_p2 ^ 1'd1);

assign xor_ln66_6_fu_651_p2 = (icmp_ln66_6_fu_645_p2 ^ 1'd1);

assign xor_ln66_7_fu_671_p2 = (icmp_ln66_7_fu_665_p2 ^ 1'd1);

assign xor_ln66_8_fu_691_p2 = (icmp_ln66_8_fu_685_p2 ^ 1'd1);

assign xor_ln66_9_fu_727_p2 = (icmp_ln66_9_fu_721_p2 ^ 1'd1);

assign xor_ln66_fu_499_p2 = (icmp_ln66_fu_493_p2 ^ 1'd1);

endmodule //lenet_mnist_cap64_hls_pooling2d_cl_array_ap_fixed_6u_array_ap_fixed_22_12_4_0_0_6u_config4_s
