// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module lenet_mnist_cap64_hls_dense_array_ap_fixed_84u_array_ap_fixed_22_12_4_0_0_10u_config13_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer12_out_dout,
        layer12_out_empty_n,
        layer12_out_read,
        layer12_out_num_data_valid,
        layer12_out_fifo_cap,
        layer13_out_TDATA,
        layer13_out_TVALID,
        layer13_out_TREADY
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [1847:0] layer12_out_dout;
input   layer12_out_empty_n;
output   layer12_out_read;
input  [1:0] layer12_out_num_data_valid;
input  [1:0] layer12_out_fifo_cap;
output  [319:0] layer13_out_TDATA;
output   layer13_out_TVALID;
input   layer13_out_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer12_out_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    layer12_out_blk_n;
reg    layer13_out_TDATA_blk_n;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [21:0] data_fu_469_p1;
reg   [21:0] data_reg_1474;
reg    ap_block_state1;
reg   [21:0] data_1_reg_1479;
reg   [21:0] data_2_reg_1484;
reg   [21:0] data_3_reg_1489;
reg   [21:0] data_4_reg_1494;
reg   [21:0] data_5_reg_1499;
reg   [21:0] data_6_reg_1504;
reg   [21:0] data_7_reg_1509;
reg   [21:0] data_8_reg_1514;
reg   [21:0] data_9_reg_1519;
reg   [21:0] data_83_reg_1524;
reg   [21:0] data_10_reg_1529;
reg   [21:0] data_11_reg_1534;
reg   [21:0] data_12_reg_1539;
reg   [21:0] data_13_reg_1544;
reg   [21:0] data_14_reg_1549;
reg   [21:0] data_15_reg_1554;
reg   [21:0] data_16_reg_1559;
reg   [21:0] data_17_reg_1564;
reg   [21:0] data_18_reg_1569;
reg   [21:0] data_19_reg_1574;
reg   [21:0] data_20_reg_1579;
reg   [21:0] data_21_reg_1584;
reg   [21:0] data_22_reg_1589;
reg   [21:0] data_23_reg_1594;
reg   [21:0] data_24_reg_1599;
reg   [21:0] data_25_reg_1604;
reg   [21:0] data_26_reg_1609;
reg   [21:0] data_27_reg_1614;
reg   [21:0] data_28_reg_1619;
reg   [21:0] data_29_reg_1624;
reg   [21:0] data_30_reg_1629;
reg   [21:0] data_31_reg_1634;
reg   [21:0] data_32_reg_1639;
reg   [21:0] data_33_reg_1644;
reg   [21:0] data_34_reg_1649;
reg   [21:0] data_35_reg_1654;
reg   [21:0] data_36_reg_1659;
reg   [21:0] data_37_reg_1664;
reg   [21:0] data_38_reg_1669;
reg   [21:0] data_39_reg_1674;
reg   [21:0] data_40_reg_1679;
reg   [21:0] data_41_reg_1684;
reg   [21:0] data_42_reg_1689;
reg   [21:0] data_43_reg_1694;
reg   [21:0] data_44_reg_1699;
reg   [21:0] data_45_reg_1704;
reg   [21:0] data_46_reg_1709;
reg   [21:0] data_47_reg_1714;
reg   [21:0] data_48_reg_1719;
reg   [21:0] data_49_reg_1724;
reg   [21:0] data_50_reg_1729;
reg   [21:0] data_51_reg_1734;
reg   [21:0] data_52_reg_1739;
reg   [21:0] data_53_reg_1744;
reg   [21:0] data_54_reg_1749;
reg   [21:0] data_55_reg_1754;
reg   [21:0] data_56_reg_1759;
reg   [21:0] data_57_reg_1764;
reg   [21:0] data_58_reg_1769;
reg   [21:0] data_59_reg_1774;
reg   [21:0] data_60_reg_1779;
reg   [21:0] data_61_reg_1784;
reg   [21:0] data_62_reg_1789;
reg   [21:0] data_63_reg_1794;
reg   [21:0] data_64_reg_1799;
reg   [21:0] data_65_reg_1804;
reg   [21:0] data_66_reg_1809;
reg   [21:0] data_67_reg_1814;
reg   [21:0] data_68_reg_1819;
reg   [21:0] data_69_reg_1824;
reg   [21:0] data_70_reg_1829;
reg   [21:0] data_71_reg_1834;
reg   [21:0] data_72_reg_1839;
reg   [21:0] data_73_reg_1844;
reg   [21:0] data_74_reg_1849;
reg   [21:0] data_75_reg_1854;
reg   [21:0] data_76_reg_1859;
reg   [21:0] data_77_reg_1864;
reg   [21:0] data_78_reg_1869;
reg   [21:0] data_79_reg_1874;
reg   [21:0] data_80_reg_1879;
reg   [21:0] data_81_reg_1884;
reg   [21:0] data_82_reg_1889;
wire    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_done;
wire    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_start;
wire    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_idle;
wire    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_ready;
wire   [21:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_0;
wire   [21:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_1;
wire   [21:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_2;
wire   [21:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_3;
wire   [21:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_4;
wire   [21:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_5;
wire   [21:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_6;
wire   [21:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_7;
wire   [21:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_8;
wire   [21:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_9;
reg    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_start_reg;
reg    ap_block_state1_ignore_call87;
wire   [309:0] tmp_fu_1427_p20;
wire    regslice_both_layer13_out_U_apdone_blk;
reg    ap_block_state3;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire   [319:0] layer13_out_TDATA_int_regslice;
reg    layer13_out_TVALID_int_regslice;
wire    layer13_out_TREADY_int_regslice;
wire    regslice_both_layer13_out_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_start_reg = 1'b0;
end

lenet_mnist_cap64_hls_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_start),
    .ap_done(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_done),
    .ap_idle(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_idle),
    .ap_ready(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_ready),
    .data_0_val(data_reg_1474),
    .data_1_val(data_1_reg_1479),
    .data_2_val(data_2_reg_1484),
    .data_3_val(data_3_reg_1489),
    .data_4_val(data_4_reg_1494),
    .data_5_val(data_5_reg_1499),
    .data_6_val(data_6_reg_1504),
    .data_7_val(data_7_reg_1509),
    .data_8_val(data_8_reg_1514),
    .data_9_val(data_9_reg_1519),
    .data_10_val(data_83_reg_1524),
    .data_11_val(data_10_reg_1529),
    .data_12_val(data_11_reg_1534),
    .data_13_val(data_12_reg_1539),
    .data_14_val(data_13_reg_1544),
    .data_15_val(data_14_reg_1549),
    .data_16_val(data_15_reg_1554),
    .data_17_val(data_16_reg_1559),
    .data_18_val(data_17_reg_1564),
    .data_19_val(data_18_reg_1569),
    .data_20_val(data_19_reg_1574),
    .data_21_val(data_20_reg_1579),
    .data_22_val(data_21_reg_1584),
    .data_23_val(data_22_reg_1589),
    .data_24_val(data_23_reg_1594),
    .data_25_val(data_24_reg_1599),
    .data_26_val(data_25_reg_1604),
    .data_27_val(data_26_reg_1609),
    .data_28_val(data_27_reg_1614),
    .data_29_val(data_28_reg_1619),
    .data_30_val(data_29_reg_1624),
    .data_31_val(data_30_reg_1629),
    .data_32_val(data_31_reg_1634),
    .data_33_val(data_32_reg_1639),
    .data_34_val(data_33_reg_1644),
    .data_35_val(data_34_reg_1649),
    .data_36_val(data_35_reg_1654),
    .data_37_val(data_36_reg_1659),
    .data_38_val(data_37_reg_1664),
    .data_39_val(data_38_reg_1669),
    .data_40_val(data_39_reg_1674),
    .data_41_val(data_40_reg_1679),
    .data_42_val(data_41_reg_1684),
    .data_43_val(data_42_reg_1689),
    .data_44_val(data_43_reg_1694),
    .data_45_val(data_44_reg_1699),
    .data_46_val(data_45_reg_1704),
    .data_47_val(data_46_reg_1709),
    .data_48_val(data_47_reg_1714),
    .data_49_val(data_48_reg_1719),
    .data_50_val(data_49_reg_1724),
    .data_51_val(data_50_reg_1729),
    .data_52_val(data_51_reg_1734),
    .data_53_val(data_52_reg_1739),
    .data_54_val(data_53_reg_1744),
    .data_55_val(data_54_reg_1749),
    .data_56_val(data_55_reg_1754),
    .data_57_val(data_56_reg_1759),
    .data_58_val(data_57_reg_1764),
    .data_59_val(data_58_reg_1769),
    .data_60_val(data_59_reg_1774),
    .data_61_val(data_60_reg_1779),
    .data_62_val(data_61_reg_1784),
    .data_63_val(data_62_reg_1789),
    .data_64_val(data_63_reg_1794),
    .data_65_val(data_64_reg_1799),
    .data_66_val(data_65_reg_1804),
    .data_67_val(data_66_reg_1809),
    .data_68_val(data_67_reg_1814),
    .data_69_val(data_68_reg_1819),
    .data_70_val(data_69_reg_1824),
    .data_71_val(data_70_reg_1829),
    .data_72_val(data_71_reg_1834),
    .data_73_val(data_72_reg_1839),
    .data_74_val(data_73_reg_1844),
    .data_75_val(data_74_reg_1849),
    .data_76_val(data_75_reg_1854),
    .data_77_val(data_76_reg_1859),
    .data_78_val(data_77_reg_1864),
    .data_79_val(data_78_reg_1869),
    .data_80_val(data_79_reg_1874),
    .data_81_val(data_80_reg_1879),
    .data_82_val(data_81_reg_1884),
    .data_83_val(data_82_reg_1889),
    .ap_return_0(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_0),
    .ap_return_1(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_1),
    .ap_return_2(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_2),
    .ap_return_3(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_3),
    .ap_return_4(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_4),
    .ap_return_5(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_5),
    .ap_return_6(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_6),
    .ap_return_7(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_7),
    .ap_return_8(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_8),
    .ap_return_9(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_9)
);

lenet_mnist_cap64_hls_regslice_both #(
    .DataWidth( 320 ))
regslice_both_layer13_out_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(layer13_out_TDATA_int_regslice),
    .vld_in(layer13_out_TVALID_int_regslice),
    .ack_in(layer13_out_TREADY_int_regslice),
    .data_out(layer13_out_TDATA),
    .vld_out(regslice_both_layer13_out_U_vld_out),
    .ack_out(layer13_out_TREADY),
    .apdone_blk(regslice_both_layer13_out_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call87) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_start_reg <= 1'b1;
        end else if ((grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_ready == 1'b1)) begin
            grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        data_10_reg_1529 <= {{layer12_out_dout[263:242]}};
        data_11_reg_1534 <= {{layer12_out_dout[285:264]}};
        data_12_reg_1539 <= {{layer12_out_dout[307:286]}};
        data_13_reg_1544 <= {{layer12_out_dout[329:308]}};
        data_14_reg_1549 <= {{layer12_out_dout[351:330]}};
        data_15_reg_1554 <= {{layer12_out_dout[373:352]}};
        data_16_reg_1559 <= {{layer12_out_dout[395:374]}};
        data_17_reg_1564 <= {{layer12_out_dout[417:396]}};
        data_18_reg_1569 <= {{layer12_out_dout[439:418]}};
        data_19_reg_1574 <= {{layer12_out_dout[461:440]}};
        data_1_reg_1479 <= {{layer12_out_dout[43:22]}};
        data_20_reg_1579 <= {{layer12_out_dout[483:462]}};
        data_21_reg_1584 <= {{layer12_out_dout[505:484]}};
        data_22_reg_1589 <= {{layer12_out_dout[527:506]}};
        data_23_reg_1594 <= {{layer12_out_dout[549:528]}};
        data_24_reg_1599 <= {{layer12_out_dout[571:550]}};
        data_25_reg_1604 <= {{layer12_out_dout[593:572]}};
        data_26_reg_1609 <= {{layer12_out_dout[615:594]}};
        data_27_reg_1614 <= {{layer12_out_dout[637:616]}};
        data_28_reg_1619 <= {{layer12_out_dout[659:638]}};
        data_29_reg_1624 <= {{layer12_out_dout[681:660]}};
        data_2_reg_1484 <= {{layer12_out_dout[65:44]}};
        data_30_reg_1629 <= {{layer12_out_dout[703:682]}};
        data_31_reg_1634 <= {{layer12_out_dout[725:704]}};
        data_32_reg_1639 <= {{layer12_out_dout[747:726]}};
        data_33_reg_1644 <= {{layer12_out_dout[769:748]}};
        data_34_reg_1649 <= {{layer12_out_dout[791:770]}};
        data_35_reg_1654 <= {{layer12_out_dout[813:792]}};
        data_36_reg_1659 <= {{layer12_out_dout[835:814]}};
        data_37_reg_1664 <= {{layer12_out_dout[857:836]}};
        data_38_reg_1669 <= {{layer12_out_dout[879:858]}};
        data_39_reg_1674 <= {{layer12_out_dout[901:880]}};
        data_3_reg_1489 <= {{layer12_out_dout[87:66]}};
        data_40_reg_1679 <= {{layer12_out_dout[923:902]}};
        data_41_reg_1684 <= {{layer12_out_dout[945:924]}};
        data_42_reg_1689 <= {{layer12_out_dout[967:946]}};
        data_43_reg_1694 <= {{layer12_out_dout[989:968]}};
        data_44_reg_1699 <= {{layer12_out_dout[1011:990]}};
        data_45_reg_1704 <= {{layer12_out_dout[1033:1012]}};
        data_46_reg_1709 <= {{layer12_out_dout[1055:1034]}};
        data_47_reg_1714 <= {{layer12_out_dout[1077:1056]}};
        data_48_reg_1719 <= {{layer12_out_dout[1099:1078]}};
        data_49_reg_1724 <= {{layer12_out_dout[1121:1100]}};
        data_4_reg_1494 <= {{layer12_out_dout[109:88]}};
        data_50_reg_1729 <= {{layer12_out_dout[1143:1122]}};
        data_51_reg_1734 <= {{layer12_out_dout[1165:1144]}};
        data_52_reg_1739 <= {{layer12_out_dout[1187:1166]}};
        data_53_reg_1744 <= {{layer12_out_dout[1209:1188]}};
        data_54_reg_1749 <= {{layer12_out_dout[1231:1210]}};
        data_55_reg_1754 <= {{layer12_out_dout[1253:1232]}};
        data_56_reg_1759 <= {{layer12_out_dout[1275:1254]}};
        data_57_reg_1764 <= {{layer12_out_dout[1297:1276]}};
        data_58_reg_1769 <= {{layer12_out_dout[1319:1298]}};
        data_59_reg_1774 <= {{layer12_out_dout[1341:1320]}};
        data_5_reg_1499 <= {{layer12_out_dout[131:110]}};
        data_60_reg_1779 <= {{layer12_out_dout[1363:1342]}};
        data_61_reg_1784 <= {{layer12_out_dout[1385:1364]}};
        data_62_reg_1789 <= {{layer12_out_dout[1407:1386]}};
        data_63_reg_1794 <= {{layer12_out_dout[1429:1408]}};
        data_64_reg_1799 <= {{layer12_out_dout[1451:1430]}};
        data_65_reg_1804 <= {{layer12_out_dout[1473:1452]}};
        data_66_reg_1809 <= {{layer12_out_dout[1495:1474]}};
        data_67_reg_1814 <= {{layer12_out_dout[1517:1496]}};
        data_68_reg_1819 <= {{layer12_out_dout[1539:1518]}};
        data_69_reg_1824 <= {{layer12_out_dout[1561:1540]}};
        data_6_reg_1504 <= {{layer12_out_dout[153:132]}};
        data_70_reg_1829 <= {{layer12_out_dout[1583:1562]}};
        data_71_reg_1834 <= {{layer12_out_dout[1605:1584]}};
        data_72_reg_1839 <= {{layer12_out_dout[1627:1606]}};
        data_73_reg_1844 <= {{layer12_out_dout[1649:1628]}};
        data_74_reg_1849 <= {{layer12_out_dout[1671:1650]}};
        data_75_reg_1854 <= {{layer12_out_dout[1693:1672]}};
        data_76_reg_1859 <= {{layer12_out_dout[1715:1694]}};
        data_77_reg_1864 <= {{layer12_out_dout[1737:1716]}};
        data_78_reg_1869 <= {{layer12_out_dout[1759:1738]}};
        data_79_reg_1874 <= {{layer12_out_dout[1781:1760]}};
        data_7_reg_1509 <= {{layer12_out_dout[175:154]}};
        data_80_reg_1879 <= {{layer12_out_dout[1803:1782]}};
        data_81_reg_1884 <= {{layer12_out_dout[1825:1804]}};
        data_82_reg_1889 <= {{layer12_out_dout[1847:1826]}};
        data_83_reg_1524 <= {{layer12_out_dout[241:220]}};
        data_8_reg_1514 <= {{layer12_out_dout[197:176]}};
        data_9_reg_1519 <= {{layer12_out_dout[219:198]}};
        data_reg_1474 <= data_fu_469_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_done == 1'b0) | (layer13_out_TREADY_int_regslice == 1'b0))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state3)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer12_out_blk_n = layer12_out_empty_n;
    end else begin
        layer12_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer12_out_read = 1'b1;
    end else begin
        layer12_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        layer13_out_TDATA_blk_n = layer13_out_TREADY_int_regslice;
    end else begin
        layer13_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_done == 1'b0) | (layer13_out_TREADY_int_regslice == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        layer13_out_TVALID_int_regslice = 1'b1;
    end else begin
        layer13_out_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_done == 1'b0) | (layer13_out_TREADY_int_regslice == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (layer12_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call87 = ((ap_start == 1'b0) | (layer12_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state3 = ((layer13_out_TREADY_int_regslice == 1'b0) | (regslice_both_layer13_out_U_apdone_blk == 1'b1));
end

assign data_fu_469_p1 = layer12_out_dout[21:0];

assign grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_start = grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_start_reg;

assign layer13_out_TDATA_int_regslice = tmp_fu_1427_p20;

assign layer13_out_TVALID = regslice_both_layer13_out_U_vld_out;

assign tmp_fu_1427_p20 = {{{{{{{{{{{{{{{{{{{grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_9}, {10'd0}}, {grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_8}}, {10'd0}}, {grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_7}}, {10'd0}}, {grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_6}}, {10'd0}}, {grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_5}}, {10'd0}}, {grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_4}}, {10'd0}}, {grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_3}}, {10'd0}}, {grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_2}}, {10'd0}}, {grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_1}}, {10'd0}}, {grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config13_s_fu_379_ap_return_0}};

endmodule //lenet_mnist_cap64_hls_dense_array_ap_fixed_84u_array_ap_fixed_22_12_4_0_0_10u_config13_s
