// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module lenet_mnist_cap64_hls_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_12_4_0_0_6u_config2_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        input_layer_TDATA,
        input_layer_TVALID,
        input_layer_TREADY,
        layer2_out_din,
        layer2_out_full_n,
        layer2_out_write,
        layer2_out_num_data_valid,
        layer2_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] input_layer_TDATA;
input   input_layer_TVALID;
output   input_layer_TREADY;
output  [131:0] layer2_out_din;
input   layer2_out_full_n;
output   layer2_out_write;
input  [10:0] layer2_out_num_data_valid;
input  [10:0] layer2_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    input_layer_TDATA_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln52_fu_199_p2;
wire   [21:0] trunc_ln58_fu_211_p1;
reg   [21:0] trunc_ln58_reg_231;
reg    ap_block_state2;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_6u_config2_s_fu_116_ap_start;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_6u_config2_s_fu_116_ap_done;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_6u_config2_s_fu_116_ap_idle;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_6u_config2_s_fu_116_ap_ready;
wire   [131:0] grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_6u_config2_s_fu_116_layer2_out_din;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_6u_config2_s_fu_116_layer2_out_write;
reg    grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_6u_config2_s_fu_116_ap_start_reg;
reg    ap_block_state2_ignore_call4;
wire    ap_CS_fsm_state3;
reg   [9:0] indvar_flatten_fu_106;
wire   [9:0] add_ln52_fu_205_p2;
reg    ap_block_state1;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    regslice_both_input_layer_U_apdone_blk;
wire   [31:0] input_layer_TDATA_int_regslice;
wire    input_layer_TVALID_int_regslice;
reg    input_layer_TREADY_int_regslice;
wire    regslice_both_input_layer_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_6u_config2_s_fu_116_ap_start_reg = 1'b0;
#0 indvar_flatten_fu_106 = 10'd0;
end

lenet_mnist_cap64_hls_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_6u_config2_s grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_6u_config2_s_fu_116(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_6u_config2_s_fu_116_ap_start),
    .ap_done(grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_6u_config2_s_fu_116_ap_done),
    .ap_idle(grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_6u_config2_s_fu_116_ap_idle),
    .ap_ready(grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_6u_config2_s_fu_116_ap_ready),
    .in_elem_0_0_0_0_0_val(trunc_ln58_reg_231),
    .layer2_out_din(grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_6u_config2_s_fu_116_layer2_out_din),
    .layer2_out_full_n(layer2_out_full_n),
    .layer2_out_write(grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_6u_config2_s_fu_116_layer2_out_write),
    .layer2_out_num_data_valid(11'd0),
    .layer2_out_fifo_cap(11'd0)
);

lenet_mnist_cap64_hls_regslice_both #(
    .DataWidth( 32 ))
regslice_both_input_layer_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(input_layer_TDATA),
    .vld_in(input_layer_TVALID),
    .ack_in(regslice_both_input_layer_U_ack_in),
    .data_out(input_layer_TDATA_int_regslice),
    .vld_out(input_layer_TVALID_int_regslice),
    .ack_out(input_layer_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_layer_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_199_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_6u_config2_s_fu_116_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state2_ignore_call4) & (icmp_ln52_fu_199_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_6u_config2_s_fu_116_ap_start_reg <= 1'b1;
        end else if ((grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_6u_config2_s_fu_116_ap_ready == 1'b1)) begin
            grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_6u_config2_s_fu_116_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_fu_106 <= 10'd0;
    end else if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_199_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        indvar_flatten_fu_106 <= add_ln52_fu_205_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
        trunc_ln58_reg_231 <= trunc_ln58_fu_211_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_6u_config2_s_fu_116_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_199_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln52_fu_199_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        input_layer_TDATA_blk_n = input_layer_TVALID_int_regslice;
    end else begin
        input_layer_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_199_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        input_layer_TREADY_int_regslice = 1'b1;
    end else begin
        input_layer_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_199_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_199_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_199_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_6u_config2_s_fu_116_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln52_fu_205_p2 = (indvar_flatten_fu_106 + 10'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2 = ((icmp_ln52_fu_199_p2 == 1'd0) & (input_layer_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state2_ignore_call4 = ((icmp_ln52_fu_199_p2 == 1'd0) & (input_layer_TVALID_int_regslice == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_6u_config2_s_fu_116_ap_start = grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_6u_config2_s_fu_116_ap_start_reg;

assign icmp_ln52_fu_199_p2 = ((indvar_flatten_fu_106 == 10'd784) ? 1'b1 : 1'b0);

assign input_layer_TREADY = regslice_both_input_layer_U_ack_in;

assign layer2_out_din = grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_6u_config2_s_fu_116_layer2_out_din;

assign layer2_out_write = grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_6u_config2_s_fu_116_layer2_out_write;

assign start_out = real_start;

assign trunc_ln58_fu_211_p1 = input_layer_TDATA_int_regslice[21:0];

endmodule //lenet_mnist_cap64_hls_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_22_12_4_0_0_6u_config2_s
