// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module resnet8_resource_fifo_opt_dense_array_ap_fixed_64u_array_ap_fixed_22_12_4_0_0_10u_config31_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer30_out_dout,
        layer30_out_empty_n,
        layer30_out_read,
        layer30_out_num_data_valid,
        layer30_out_fifo_cap,
        layer31_out_TDATA,
        layer31_out_TVALID,
        layer31_out_TREADY
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [1407:0] layer30_out_dout;
input   layer30_out_empty_n;
output   layer30_out_read;
input  [1:0] layer30_out_num_data_valid;
input  [1:0] layer30_out_fifo_cap;
output  [319:0] layer31_out_TDATA;
output   layer31_out_TVALID;
input   layer31_out_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer30_out_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    layer30_out_blk_n;
reg    layer31_out_TDATA_blk_n;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [21:0] data_fu_369_p1;
reg   [21:0] data_reg_1154;
reg    ap_block_state1;
reg   [21:0] data_107_reg_1159;
reg   [21:0] data_45_reg_1164;
reg   [21:0] data_46_reg_1169;
reg   [21:0] data_47_reg_1174;
reg   [21:0] data_48_reg_1179;
reg   [21:0] data_49_reg_1184;
reg   [21:0] data_50_reg_1189;
reg   [21:0] data_51_reg_1194;
reg   [21:0] data_52_reg_1199;
reg   [21:0] data_53_reg_1204;
reg   [21:0] data_54_reg_1209;
reg   [21:0] data_55_reg_1214;
reg   [21:0] data_56_reg_1219;
reg   [21:0] data_57_reg_1224;
reg   [21:0] data_58_reg_1229;
reg   [21:0] data_59_reg_1234;
reg   [21:0] data_60_reg_1239;
reg   [21:0] data_61_reg_1244;
reg   [21:0] data_62_reg_1249;
reg   [21:0] data_63_reg_1254;
reg   [21:0] data_64_reg_1259;
reg   [21:0] data_65_reg_1264;
reg   [21:0] data_66_reg_1269;
reg   [21:0] data_67_reg_1274;
reg   [21:0] data_68_reg_1279;
reg   [21:0] data_69_reg_1284;
reg   [21:0] data_70_reg_1289;
reg   [21:0] data_71_reg_1294;
reg   [21:0] data_72_reg_1299;
reg   [21:0] data_73_reg_1304;
reg   [21:0] data_74_reg_1309;
reg   [21:0] data_75_reg_1314;
reg   [21:0] data_76_reg_1319;
reg   [21:0] data_77_reg_1324;
reg   [21:0] data_78_reg_1329;
reg   [21:0] data_79_reg_1334;
reg   [21:0] data_80_reg_1339;
reg   [21:0] data_81_reg_1344;
reg   [21:0] data_82_reg_1349;
reg   [21:0] data_83_reg_1354;
reg   [21:0] data_84_reg_1359;
reg   [21:0] data_85_reg_1364;
reg   [21:0] data_86_reg_1369;
reg   [21:0] data_87_reg_1374;
reg   [21:0] data_88_reg_1379;
reg   [21:0] data_89_reg_1384;
reg   [21:0] data_90_reg_1389;
reg   [21:0] data_91_reg_1394;
reg   [21:0] data_92_reg_1399;
reg   [21:0] data_93_reg_1404;
reg   [21:0] data_94_reg_1409;
reg   [21:0] data_95_reg_1414;
reg   [21:0] data_96_reg_1419;
reg   [21:0] data_97_reg_1424;
reg   [21:0] data_98_reg_1429;
reg   [21:0] data_99_reg_1434;
reg   [21:0] data_100_reg_1439;
reg   [21:0] data_101_reg_1444;
reg   [21:0] data_102_reg_1449;
reg   [21:0] data_103_reg_1454;
reg   [21:0] data_104_reg_1459;
reg   [21:0] data_105_reg_1464;
reg   [21:0] data_106_reg_1469;
wire    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_done;
wire    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_start;
wire    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_idle;
wire    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_ready;
wire   [21:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_0;
wire   [21:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_1;
wire   [21:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_2;
wire   [21:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_3;
wire   [21:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_4;
wire   [21:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_5;
wire   [21:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_6;
wire   [21:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_7;
wire   [21:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_8;
wire   [21:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_9;
reg    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_start_reg;
reg    ap_block_state1_ignore_call67;
wire   [309:0] tmp_fu_1107_p20;
wire    regslice_both_layer31_out_U_apdone_blk;
reg    ap_block_state3;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire   [319:0] layer31_out_TDATA_int_regslice;
reg    layer31_out_TVALID_int_regslice;
wire    layer31_out_TREADY_int_regslice;
wire    regslice_both_layer31_out_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_start_reg = 1'b0;
end

resnet8_resource_fifo_opt_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_start),
    .ap_done(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_done),
    .ap_idle(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_idle),
    .ap_ready(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_ready),
    .data_0_val(data_reg_1154),
    .data_1_val(data_107_reg_1159),
    .data_2_val(data_45_reg_1164),
    .data_3_val(data_46_reg_1169),
    .data_4_val(data_47_reg_1174),
    .data_5_val(data_48_reg_1179),
    .data_6_val(data_49_reg_1184),
    .data_7_val(data_50_reg_1189),
    .data_8_val(data_51_reg_1194),
    .data_9_val(data_52_reg_1199),
    .data_10_val(data_53_reg_1204),
    .data_11_val(data_54_reg_1209),
    .data_12_val(data_55_reg_1214),
    .data_13_val(data_56_reg_1219),
    .data_14_val(data_57_reg_1224),
    .data_15_val(data_58_reg_1229),
    .data_16_val(data_59_reg_1234),
    .data_17_val(data_60_reg_1239),
    .data_18_val(data_61_reg_1244),
    .data_19_val(data_62_reg_1249),
    .data_20_val(data_63_reg_1254),
    .data_21_val(data_64_reg_1259),
    .data_22_val(data_65_reg_1264),
    .data_23_val(data_66_reg_1269),
    .data_24_val(data_67_reg_1274),
    .data_25_val(data_68_reg_1279),
    .data_26_val(data_69_reg_1284),
    .data_27_val(data_70_reg_1289),
    .data_28_val(data_71_reg_1294),
    .data_29_val(data_72_reg_1299),
    .data_30_val(data_73_reg_1304),
    .data_31_val(data_74_reg_1309),
    .data_32_val(data_75_reg_1314),
    .data_33_val(data_76_reg_1319),
    .data_34_val(data_77_reg_1324),
    .data_35_val(data_78_reg_1329),
    .data_36_val(data_79_reg_1334),
    .data_37_val(data_80_reg_1339),
    .data_38_val(data_81_reg_1344),
    .data_39_val(data_82_reg_1349),
    .data_40_val(data_83_reg_1354),
    .data_41_val(data_84_reg_1359),
    .data_42_val(data_85_reg_1364),
    .data_43_val(data_86_reg_1369),
    .data_44_val(data_87_reg_1374),
    .data_45_val(data_88_reg_1379),
    .data_46_val(data_89_reg_1384),
    .data_47_val(data_90_reg_1389),
    .data_48_val(data_91_reg_1394),
    .data_49_val(data_92_reg_1399),
    .data_50_val(data_93_reg_1404),
    .data_51_val(data_94_reg_1409),
    .data_52_val(data_95_reg_1414),
    .data_53_val(data_96_reg_1419),
    .data_54_val(data_97_reg_1424),
    .data_55_val(data_98_reg_1429),
    .data_56_val(data_99_reg_1434),
    .data_57_val(data_100_reg_1439),
    .data_58_val(data_101_reg_1444),
    .data_59_val(data_102_reg_1449),
    .data_60_val(data_103_reg_1454),
    .data_61_val(data_104_reg_1459),
    .data_62_val(data_105_reg_1464),
    .data_63_val(data_106_reg_1469),
    .ap_return_0(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_0),
    .ap_return_1(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_1),
    .ap_return_2(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_2),
    .ap_return_3(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_3),
    .ap_return_4(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_4),
    .ap_return_5(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_5),
    .ap_return_6(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_6),
    .ap_return_7(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_7),
    .ap_return_8(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_8),
    .ap_return_9(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_9)
);

resnet8_resource_fifo_opt_regslice_both #(
    .DataWidth( 320 ))
regslice_both_layer31_out_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(layer31_out_TDATA_int_regslice),
    .vld_in(layer31_out_TVALID_int_regslice),
    .ack_in(layer31_out_TREADY_int_regslice),
    .data_out(layer31_out_TDATA),
    .vld_out(regslice_both_layer31_out_U_vld_out),
    .ack_out(layer31_out_TREADY),
    .apdone_blk(regslice_both_layer31_out_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call67) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_start_reg <= 1'b1;
        end else if ((grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_ready == 1'b1)) begin
            grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        data_100_reg_1439 <= {{layer30_out_dout[1275:1254]}};
        data_101_reg_1444 <= {{layer30_out_dout[1297:1276]}};
        data_102_reg_1449 <= {{layer30_out_dout[1319:1298]}};
        data_103_reg_1454 <= {{layer30_out_dout[1341:1320]}};
        data_104_reg_1459 <= {{layer30_out_dout[1363:1342]}};
        data_105_reg_1464 <= {{layer30_out_dout[1385:1364]}};
        data_106_reg_1469 <= {{layer30_out_dout[1407:1386]}};
        data_107_reg_1159 <= {{layer30_out_dout[43:22]}};
        data_45_reg_1164 <= {{layer30_out_dout[65:44]}};
        data_46_reg_1169 <= {{layer30_out_dout[87:66]}};
        data_47_reg_1174 <= {{layer30_out_dout[109:88]}};
        data_48_reg_1179 <= {{layer30_out_dout[131:110]}};
        data_49_reg_1184 <= {{layer30_out_dout[153:132]}};
        data_50_reg_1189 <= {{layer30_out_dout[175:154]}};
        data_51_reg_1194 <= {{layer30_out_dout[197:176]}};
        data_52_reg_1199 <= {{layer30_out_dout[219:198]}};
        data_53_reg_1204 <= {{layer30_out_dout[241:220]}};
        data_54_reg_1209 <= {{layer30_out_dout[263:242]}};
        data_55_reg_1214 <= {{layer30_out_dout[285:264]}};
        data_56_reg_1219 <= {{layer30_out_dout[307:286]}};
        data_57_reg_1224 <= {{layer30_out_dout[329:308]}};
        data_58_reg_1229 <= {{layer30_out_dout[351:330]}};
        data_59_reg_1234 <= {{layer30_out_dout[373:352]}};
        data_60_reg_1239 <= {{layer30_out_dout[395:374]}};
        data_61_reg_1244 <= {{layer30_out_dout[417:396]}};
        data_62_reg_1249 <= {{layer30_out_dout[439:418]}};
        data_63_reg_1254 <= {{layer30_out_dout[461:440]}};
        data_64_reg_1259 <= {{layer30_out_dout[483:462]}};
        data_65_reg_1264 <= {{layer30_out_dout[505:484]}};
        data_66_reg_1269 <= {{layer30_out_dout[527:506]}};
        data_67_reg_1274 <= {{layer30_out_dout[549:528]}};
        data_68_reg_1279 <= {{layer30_out_dout[571:550]}};
        data_69_reg_1284 <= {{layer30_out_dout[593:572]}};
        data_70_reg_1289 <= {{layer30_out_dout[615:594]}};
        data_71_reg_1294 <= {{layer30_out_dout[637:616]}};
        data_72_reg_1299 <= {{layer30_out_dout[659:638]}};
        data_73_reg_1304 <= {{layer30_out_dout[681:660]}};
        data_74_reg_1309 <= {{layer30_out_dout[703:682]}};
        data_75_reg_1314 <= {{layer30_out_dout[725:704]}};
        data_76_reg_1319 <= {{layer30_out_dout[747:726]}};
        data_77_reg_1324 <= {{layer30_out_dout[769:748]}};
        data_78_reg_1329 <= {{layer30_out_dout[791:770]}};
        data_79_reg_1334 <= {{layer30_out_dout[813:792]}};
        data_80_reg_1339 <= {{layer30_out_dout[835:814]}};
        data_81_reg_1344 <= {{layer30_out_dout[857:836]}};
        data_82_reg_1349 <= {{layer30_out_dout[879:858]}};
        data_83_reg_1354 <= {{layer30_out_dout[901:880]}};
        data_84_reg_1359 <= {{layer30_out_dout[923:902]}};
        data_85_reg_1364 <= {{layer30_out_dout[945:924]}};
        data_86_reg_1369 <= {{layer30_out_dout[967:946]}};
        data_87_reg_1374 <= {{layer30_out_dout[989:968]}};
        data_88_reg_1379 <= {{layer30_out_dout[1011:990]}};
        data_89_reg_1384 <= {{layer30_out_dout[1033:1012]}};
        data_90_reg_1389 <= {{layer30_out_dout[1055:1034]}};
        data_91_reg_1394 <= {{layer30_out_dout[1077:1056]}};
        data_92_reg_1399 <= {{layer30_out_dout[1099:1078]}};
        data_93_reg_1404 <= {{layer30_out_dout[1121:1100]}};
        data_94_reg_1409 <= {{layer30_out_dout[1143:1122]}};
        data_95_reg_1414 <= {{layer30_out_dout[1165:1144]}};
        data_96_reg_1419 <= {{layer30_out_dout[1187:1166]}};
        data_97_reg_1424 <= {{layer30_out_dout[1209:1188]}};
        data_98_reg_1429 <= {{layer30_out_dout[1231:1210]}};
        data_99_reg_1434 <= {{layer30_out_dout[1253:1232]}};
        data_reg_1154 <= data_fu_369_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer31_out_TREADY_int_regslice == 1'b0) | (grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_done == 1'b0))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state3)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer30_out_blk_n = layer30_out_empty_n;
    end else begin
        layer30_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer30_out_read = 1'b1;
    end else begin
        layer30_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        layer31_out_TDATA_blk_n = layer31_out_TREADY_int_regslice;
    end else begin
        layer31_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((layer31_out_TREADY_int_regslice == 1'b0) | (grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        layer31_out_TVALID_int_regslice = 1'b1;
    end else begin
        layer31_out_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((layer31_out_TREADY_int_regslice == 1'b0) | (grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (layer30_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call67 = ((ap_start == 1'b0) | (layer30_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state3 = ((layer31_out_TREADY_int_regslice == 1'b0) | (regslice_both_layer31_out_U_apdone_blk == 1'b1));
end

assign data_fu_369_p1 = layer30_out_dout[21:0];

assign grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_start = grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_start_reg;

assign layer31_out_TDATA_int_regslice = tmp_fu_1107_p20;

assign layer31_out_TVALID = regslice_both_layer31_out_U_vld_out;

assign tmp_fu_1107_p20 = {{{{{{{{{{{{{{{{{{{grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_9}, {10'd0}}, {grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_8}}, {10'd0}}, {grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_7}}, {10'd0}}, {grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_6}}, {10'd0}}, {grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_5}}, {10'd0}}, {grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_4}}, {10'd0}}, {grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_3}}, {10'd0}}, {grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_2}}, {10'd0}}, {grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_1}}, {10'd0}}, {grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_22_12_4_0_0_config31_s_fu_299_ap_return_0}};

endmodule //resnet8_resource_fifo_opt_dense_array_ap_fixed_64u_array_ap_fixed_22_12_4_0_0_10u_config31_s
