// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module resnet8_resource_fifo_opt_normalize_array_ap_fixed_32u_array_ap_fixed_22_12_4_0_0_32u_config13_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer13_out_din,
        layer13_out_full_n,
        layer13_out_write,
        layer13_out_num_data_valid,
        layer13_out_fifo_cap,
        start_out,
        start_write,
        layer12_out_dout,
        layer12_out_empty_n,
        layer12_out_read,
        layer12_out_num_data_valid,
        layer12_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [703:0] layer13_out_din;
input   layer13_out_full_n;
output   layer13_out_write;
input  [1:0] layer13_out_num_data_valid;
input  [1:0] layer13_out_fifo_cap;
output   start_out;
output   start_write;
input  [703:0] layer12_out_dout;
input   layer12_out_empty_n;
output   layer12_out_read;
input  [1:0] layer12_out_num_data_valid;
input  [1:0] layer12_out_fifo_cap;

reg ap_idle;
reg layer13_out_write;
reg start_write;
reg layer12_out_read;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    internal_ap_ready;
wire    ap_CS_fsm_state2;
reg    ap_block_state2_pp0_stage1_iter0;
wire   [0:0] icmp_ln25_fu_68956_p2;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer12_out_blk_n;
reg    ap_done_reg;
reg    layer13_out_blk_n;
reg   [0:0] tmp_reg_68974;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [21:0] add_ln41_fu_64939_p2;
reg   [21:0] add_ln41_reg_68980;
reg   [0:0] tmp_1252_reg_68985;
reg   [0:0] tmp_1253_reg_68991;
wire   [21:0] add_ln41_251_fu_65028_p2;
reg   [21:0] add_ln41_251_reg_68997;
reg   [0:0] tmp_1256_reg_69002;
reg   [0:0] tmp_1257_reg_69008;
wire   [21:0] add_ln41_252_fu_65113_p2;
reg   [21:0] add_ln41_252_reg_69014;
reg   [0:0] tmp_1260_reg_69019;
reg   [0:0] tmp_1261_reg_69025;
wire   [21:0] add_ln41_253_fu_65198_p2;
reg   [21:0] add_ln41_253_reg_69031;
reg   [0:0] tmp_1264_reg_69036;
reg   [0:0] tmp_1265_reg_69042;
wire   [21:0] add_ln41_254_fu_65283_p2;
reg   [21:0] add_ln41_254_reg_69048;
reg   [0:0] tmp_1268_reg_69053;
reg   [0:0] tmp_1269_reg_69059;
wire   [21:0] add_ln41_255_fu_65368_p2;
reg   [21:0] add_ln41_255_reg_69065;
reg   [0:0] tmp_1272_reg_69070;
reg   [0:0] tmp_1273_reg_69076;
wire   [21:0] add_ln41_256_fu_65453_p2;
reg   [21:0] add_ln41_256_reg_69082;
reg   [0:0] tmp_1276_reg_69087;
reg   [0:0] tmp_1277_reg_69093;
wire   [21:0] add_ln41_257_fu_65538_p2;
reg   [21:0] add_ln41_257_reg_69099;
reg   [0:0] tmp_1280_reg_69104;
reg   [0:0] tmp_1281_reg_69110;
wire   [21:0] add_ln41_258_fu_65623_p2;
reg   [21:0] add_ln41_258_reg_69116;
reg   [0:0] tmp_1284_reg_69121;
reg   [0:0] tmp_1285_reg_69127;
wire   [21:0] add_ln41_259_fu_65708_p2;
reg   [21:0] add_ln41_259_reg_69133;
reg   [0:0] tmp_1288_reg_69138;
reg   [0:0] tmp_1289_reg_69144;
wire   [21:0] add_ln41_260_fu_65793_p2;
reg   [21:0] add_ln41_260_reg_69150;
reg   [0:0] tmp_1292_reg_69155;
reg   [0:0] tmp_1293_reg_69161;
wire   [21:0] add_ln41_261_fu_65878_p2;
reg   [21:0] add_ln41_261_reg_69167;
reg   [0:0] tmp_1296_reg_69172;
reg   [0:0] tmp_1297_reg_69178;
wire   [21:0] add_ln41_262_fu_65963_p2;
reg   [21:0] add_ln41_262_reg_69184;
reg   [0:0] tmp_1300_reg_69189;
reg   [0:0] tmp_1301_reg_69195;
wire   [21:0] add_ln41_263_fu_66048_p2;
reg   [21:0] add_ln41_263_reg_69201;
reg   [0:0] tmp_1304_reg_69206;
reg   [0:0] tmp_1305_reg_69212;
wire   [21:0] add_ln41_264_fu_66133_p2;
reg   [21:0] add_ln41_264_reg_69218;
reg   [0:0] tmp_1308_reg_69223;
reg   [0:0] tmp_1309_reg_69229;
wire   [21:0] add_ln41_265_fu_66218_p2;
reg   [21:0] add_ln41_265_reg_69235;
reg   [0:0] tmp_1312_reg_69240;
reg   [0:0] tmp_1313_reg_69246;
wire   [21:0] add_ln41_266_fu_66303_p2;
reg   [21:0] add_ln41_266_reg_69252;
reg   [0:0] tmp_1316_reg_69257;
reg   [0:0] tmp_1317_reg_69263;
wire   [21:0] add_ln41_267_fu_66388_p2;
reg   [21:0] add_ln41_267_reg_69269;
reg   [0:0] tmp_1320_reg_69274;
reg   [21:0] tmp_1321_reg_69280;
reg   [0:0] tmp_1328_reg_69286;
wire   [21:0] add_ln41_269_fu_66483_p2;
reg   [21:0] add_ln41_269_reg_69292;
reg   [0:0] tmp_1331_reg_69297;
reg   [0:0] tmp_1332_reg_69303;
wire   [21:0] add_ln41_270_fu_66568_p2;
reg   [21:0] add_ln41_270_reg_69309;
reg   [0:0] tmp_1335_reg_69314;
reg   [0:0] tmp_1336_reg_69320;
wire   [21:0] add_ln41_271_fu_66653_p2;
reg   [21:0] add_ln41_271_reg_69326;
reg   [0:0] tmp_1339_reg_69331;
reg   [0:0] tmp_1340_reg_69337;
wire   [21:0] add_ln41_272_fu_66738_p2;
reg   [21:0] add_ln41_272_reg_69343;
reg   [0:0] tmp_1343_reg_69348;
reg   [0:0] tmp_1344_reg_69354;
wire   [21:0] add_ln41_273_fu_66823_p2;
reg   [21:0] add_ln41_273_reg_69360;
reg   [0:0] tmp_1347_reg_69365;
reg   [0:0] tmp_1348_reg_69371;
wire   [21:0] add_ln41_274_fu_66908_p2;
reg   [21:0] add_ln41_274_reg_69377;
reg   [0:0] tmp_1351_reg_69382;
reg   [0:0] tmp_1352_reg_69388;
wire   [21:0] add_ln41_275_fu_66993_p2;
reg   [21:0] add_ln41_275_reg_69394;
reg   [0:0] tmp_1355_reg_69399;
reg   [0:0] tmp_1356_reg_69405;
wire   [21:0] add_ln41_276_fu_67078_p2;
reg   [21:0] add_ln41_276_reg_69411;
reg   [0:0] tmp_1359_reg_69416;
reg   [0:0] tmp_1360_reg_69422;
wire   [21:0] add_ln41_277_fu_67163_p2;
reg   [21:0] add_ln41_277_reg_69428;
reg   [0:0] tmp_1363_reg_69433;
reg   [0:0] tmp_1364_reg_69439;
wire   [21:0] add_ln41_278_fu_67248_p2;
reg   [21:0] add_ln41_278_reg_69445;
reg   [0:0] tmp_1367_reg_69450;
reg   [0:0] tmp_1368_reg_69456;
wire   [21:0] add_ln41_279_fu_67333_p2;
reg   [21:0] add_ln41_279_reg_69462;
reg   [0:0] tmp_1371_reg_69467;
reg   [0:0] tmp_1372_reg_69473;
wire   [21:0] add_ln41_280_fu_67418_p2;
reg   [21:0] add_ln41_280_reg_69479;
reg   [0:0] tmp_1375_reg_69484;
reg   [0:0] tmp_1376_reg_69490;
wire   [21:0] add_ln41_281_fu_67503_p2;
reg   [21:0] add_ln41_281_reg_69496;
reg   [0:0] tmp_1379_reg_69501;
reg   [7:0] i_021_fu_324;
wire   [7:0] i_fu_68950_p2;
wire    ap_loop_init;
wire   [10:0] mul_ln42_268_fu_342_p1;
wire   [10:0] mul_ln42_261_fu_343_p1;
wire   [10:0] mul_ln42_247_fu_345_p1;
wire   [10:0] mul_ln42_249_fu_369_p1;
wire   [10:0] mul_ln42_242_fu_370_p1;
wire   [10:0] mul_ln42_267_fu_376_p1;
wire   [10:0] mul_ln42_254_fu_425_p1;
wire   [10:0] mul_ln42_257_fu_431_p1;
wire   [10:0] mul_ln42_255_fu_438_p1;
wire   [10:0] mul_ln42_252_fu_442_p1;
wire   [10:0] mul_ln42_fu_447_p1;
wire   [10:0] mul_ln42_263_fu_579_p1;
wire   [10:0] mul_ln42_258_fu_603_p1;
wire   [10:0] mul_ln42_245_fu_605_p1;
wire   [10:0] mul_ln42_248_fu_611_p1;
wire   [10:0] mul_ln42_253_fu_613_p1;
wire   [10:0] mul_ln42_259_fu_618_p1;
wire   [10:0] mul_ln42_266_fu_624_p1;
wire   [9:0] mul_ln42_240_fu_632_p1;
wire   [10:0] mul_ln42_262_fu_636_p1;
wire   [10:0] mul_ln42_265_fu_655_p1;
wire   [10:0] mul_ln42_260_fu_666_p1;
wire   [10:0] mul_ln42_264_fu_673_p1;
wire   [10:0] mul_ln42_269_fu_716_p1;
wire   [10:0] mul_ln42_241_fu_720_p1;
wire   [10:0] mul_ln42_246_fu_749_p1;
wire   [10:0] mul_ln42_250_fu_756_p1;
wire   [10:0] mul_ln42_243_fu_784_p1;
wire   [10:0] mul_ln42_244_fu_793_p1;
wire   [10:0] mul_ln42_256_fu_835_p1;
wire   [10:0] mul_ln42_251_fu_846_p1;
wire  signed [21:0] a_fu_64564_p1;
wire   [31:0] mul_ln42_fu_447_p2;
wire   [31:0] add_ln42_fu_64873_p2;
wire   [8:0] trunc_ln41_fu_64905_p1;
wire   [0:0] tmp_1251_fu_64915_p3;
wire   [0:0] icmp_ln41_fu_64909_p2;
wire   [0:0] or_ln41_fu_64923_p2;
wire   [0:0] tmp_1250_fu_64897_p3;
wire   [0:0] and_ln41_fu_64929_p2;
wire   [21:0] trunc_ln_fu_64887_p4;
wire   [21:0] zext_ln41_fu_64935_p1;
wire  signed [21:0] a_264_fu_64568_p4;
wire   [30:0] mul_ln42_240_fu_632_p2;
wire   [30:0] add_ln42_252_fu_64958_p2;
wire   [20:0] trunc_ln41_s_fu_64972_p4;
wire   [8:0] trunc_ln41_313_fu_64994_p1;
wire   [0:0] tmp_1255_fu_65004_p3;
wire   [0:0] icmp_ln41_379_fu_64998_p2;
wire   [0:0] or_ln41_765_fu_65012_p2;
wire   [0:0] tmp_1254_fu_64986_p3;
wire   [0:0] and_ln41_900_fu_65018_p2;
wire  signed [21:0] sext_ln41_fu_64982_p1;
wire   [21:0] zext_ln41_251_fu_65024_p1;
wire  signed [21:0] a_235_fu_64578_p4;
wire   [31:0] mul_ln42_241_fu_720_p2;
wire   [31:0] add_ln42_253_fu_65047_p2;
wire   [8:0] trunc_ln41_314_fu_65079_p1;
wire   [0:0] tmp_1259_fu_65089_p3;
wire   [0:0] icmp_ln41_380_fu_65083_p2;
wire   [0:0] or_ln41_768_fu_65097_p2;
wire   [0:0] tmp_1258_fu_65071_p3;
wire   [0:0] and_ln41_902_fu_65103_p2;
wire   [21:0] trunc_ln41_247_fu_65061_p4;
wire   [21:0] zext_ln41_252_fu_65109_p1;
wire  signed [21:0] a_236_fu_64588_p4;
wire   [31:0] mul_ln42_242_fu_370_p2;
wire   [31:0] add_ln42_254_fu_65132_p2;
wire   [8:0] trunc_ln41_315_fu_65164_p1;
wire   [0:0] tmp_1263_fu_65174_p3;
wire   [0:0] icmp_ln41_381_fu_65168_p2;
wire   [0:0] or_ln41_771_fu_65182_p2;
wire   [0:0] tmp_1262_fu_65156_p3;
wire   [0:0] and_ln41_904_fu_65188_p2;
wire   [21:0] trunc_ln41_248_fu_65146_p4;
wire   [21:0] zext_ln41_253_fu_65194_p1;
wire  signed [21:0] a_237_fu_64598_p4;
wire   [31:0] mul_ln42_243_fu_784_p2;
wire   [31:0] add_ln42_255_fu_65217_p2;
wire   [8:0] trunc_ln41_316_fu_65249_p1;
wire   [0:0] tmp_1267_fu_65259_p3;
wire   [0:0] icmp_ln41_382_fu_65253_p2;
wire   [0:0] or_ln41_774_fu_65267_p2;
wire   [0:0] tmp_1266_fu_65241_p3;
wire   [0:0] and_ln41_906_fu_65273_p2;
wire   [21:0] trunc_ln41_249_fu_65231_p4;
wire   [21:0] zext_ln41_254_fu_65279_p1;
wire  signed [21:0] a_238_fu_64608_p4;
wire   [31:0] mul_ln42_244_fu_793_p2;
wire   [31:0] add_ln42_256_fu_65302_p2;
wire   [8:0] trunc_ln41_317_fu_65334_p1;
wire   [0:0] tmp_1271_fu_65344_p3;
wire   [0:0] icmp_ln41_383_fu_65338_p2;
wire   [0:0] or_ln41_777_fu_65352_p2;
wire   [0:0] tmp_1270_fu_65326_p3;
wire   [0:0] and_ln41_908_fu_65358_p2;
wire   [21:0] trunc_ln41_250_fu_65316_p4;
wire   [21:0] zext_ln41_255_fu_65364_p1;
wire  signed [21:0] a_239_fu_64618_p4;
wire   [31:0] mul_ln42_245_fu_605_p2;
wire   [31:0] add_ln42_257_fu_65387_p2;
wire   [8:0] trunc_ln41_318_fu_65419_p1;
wire   [0:0] tmp_1275_fu_65429_p3;
wire   [0:0] icmp_ln41_384_fu_65423_p2;
wire   [0:0] or_ln41_780_fu_65437_p2;
wire   [0:0] tmp_1274_fu_65411_p3;
wire   [0:0] and_ln41_910_fu_65443_p2;
wire   [21:0] trunc_ln41_251_fu_65401_p4;
wire   [21:0] zext_ln41_256_fu_65449_p1;
wire  signed [21:0] a_240_fu_64628_p4;
wire   [31:0] mul_ln42_246_fu_749_p2;
wire   [31:0] add_ln42_258_fu_65472_p2;
wire   [8:0] trunc_ln41_319_fu_65504_p1;
wire   [0:0] tmp_1279_fu_65514_p3;
wire   [0:0] icmp_ln41_385_fu_65508_p2;
wire   [0:0] or_ln41_783_fu_65522_p2;
wire   [0:0] tmp_1278_fu_65496_p3;
wire   [0:0] and_ln41_912_fu_65528_p2;
wire   [21:0] trunc_ln41_252_fu_65486_p4;
wire   [21:0] zext_ln41_257_fu_65534_p1;
wire  signed [21:0] a_241_fu_64638_p4;
wire   [31:0] mul_ln42_247_fu_345_p2;
wire   [31:0] add_ln42_259_fu_65557_p2;
wire   [8:0] trunc_ln41_320_fu_65589_p1;
wire   [0:0] tmp_1283_fu_65599_p3;
wire   [0:0] icmp_ln41_386_fu_65593_p2;
wire   [0:0] or_ln41_786_fu_65607_p2;
wire   [0:0] tmp_1282_fu_65581_p3;
wire   [0:0] and_ln41_914_fu_65613_p2;
wire   [21:0] trunc_ln41_253_fu_65571_p4;
wire   [21:0] zext_ln41_258_fu_65619_p1;
wire  signed [21:0] a_242_fu_64648_p4;
wire   [31:0] mul_ln42_248_fu_611_p2;
wire   [31:0] add_ln42_260_fu_65642_p2;
wire   [8:0] trunc_ln41_321_fu_65674_p1;
wire   [0:0] tmp_1287_fu_65684_p3;
wire   [0:0] icmp_ln41_387_fu_65678_p2;
wire   [0:0] or_ln41_789_fu_65692_p2;
wire   [0:0] tmp_1286_fu_65666_p3;
wire   [0:0] and_ln41_916_fu_65698_p2;
wire   [21:0] trunc_ln41_254_fu_65656_p4;
wire   [21:0] zext_ln41_259_fu_65704_p1;
wire  signed [21:0] a_243_fu_64658_p4;
wire   [31:0] mul_ln42_249_fu_369_p2;
wire   [31:0] add_ln42_261_fu_65727_p2;
wire   [8:0] trunc_ln41_322_fu_65759_p1;
wire   [0:0] tmp_1291_fu_65769_p3;
wire   [0:0] icmp_ln41_388_fu_65763_p2;
wire   [0:0] or_ln41_792_fu_65777_p2;
wire   [0:0] tmp_1290_fu_65751_p3;
wire   [0:0] and_ln41_918_fu_65783_p2;
wire   [21:0] trunc_ln41_255_fu_65741_p4;
wire   [21:0] zext_ln41_260_fu_65789_p1;
wire  signed [21:0] a_244_fu_64668_p4;
wire   [31:0] mul_ln42_250_fu_756_p2;
wire   [31:0] add_ln42_262_fu_65812_p2;
wire   [8:0] trunc_ln41_323_fu_65844_p1;
wire   [0:0] tmp_1295_fu_65854_p3;
wire   [0:0] icmp_ln41_389_fu_65848_p2;
wire   [0:0] or_ln41_795_fu_65862_p2;
wire   [0:0] tmp_1294_fu_65836_p3;
wire   [0:0] and_ln41_920_fu_65868_p2;
wire   [21:0] trunc_ln41_256_fu_65826_p4;
wire   [21:0] zext_ln41_261_fu_65874_p1;
wire  signed [21:0] a_245_fu_64678_p4;
wire   [31:0] mul_ln42_251_fu_846_p2;
wire   [31:0] add_ln42_263_fu_65897_p2;
wire   [8:0] trunc_ln41_324_fu_65929_p1;
wire   [0:0] tmp_1299_fu_65939_p3;
wire   [0:0] icmp_ln41_390_fu_65933_p2;
wire   [0:0] or_ln41_798_fu_65947_p2;
wire   [0:0] tmp_1298_fu_65921_p3;
wire   [0:0] and_ln41_922_fu_65953_p2;
wire   [21:0] trunc_ln41_257_fu_65911_p4;
wire   [21:0] zext_ln41_262_fu_65959_p1;
wire  signed [21:0] a_246_fu_64688_p4;
wire   [31:0] mul_ln42_252_fu_442_p2;
wire   [31:0] add_ln42_264_fu_65982_p2;
wire   [8:0] trunc_ln41_325_fu_66014_p1;
wire   [0:0] tmp_1303_fu_66024_p3;
wire   [0:0] icmp_ln41_391_fu_66018_p2;
wire   [0:0] or_ln41_801_fu_66032_p2;
wire   [0:0] tmp_1302_fu_66006_p3;
wire   [0:0] and_ln41_924_fu_66038_p2;
wire   [21:0] trunc_ln41_258_fu_65996_p4;
wire   [21:0] zext_ln41_263_fu_66044_p1;
wire  signed [21:0] a_247_fu_64698_p4;
wire   [31:0] mul_ln42_253_fu_613_p2;
wire   [31:0] add_ln42_265_fu_66067_p2;
wire   [8:0] trunc_ln41_326_fu_66099_p1;
wire   [0:0] tmp_1307_fu_66109_p3;
wire   [0:0] icmp_ln41_392_fu_66103_p2;
wire   [0:0] or_ln41_804_fu_66117_p2;
wire   [0:0] tmp_1306_fu_66091_p3;
wire   [0:0] and_ln41_926_fu_66123_p2;
wire   [21:0] trunc_ln41_259_fu_66081_p4;
wire   [21:0] zext_ln41_264_fu_66129_p1;
wire  signed [21:0] a_248_fu_64708_p4;
wire   [31:0] mul_ln42_254_fu_425_p2;
wire   [31:0] add_ln42_266_fu_66152_p2;
wire   [8:0] trunc_ln41_327_fu_66184_p1;
wire   [0:0] tmp_1311_fu_66194_p3;
wire   [0:0] icmp_ln41_393_fu_66188_p2;
wire   [0:0] or_ln41_807_fu_66202_p2;
wire   [0:0] tmp_1310_fu_66176_p3;
wire   [0:0] and_ln41_928_fu_66208_p2;
wire   [21:0] trunc_ln41_260_fu_66166_p4;
wire   [21:0] zext_ln41_265_fu_66214_p1;
wire  signed [21:0] a_249_fu_64718_p4;
wire   [31:0] mul_ln42_255_fu_438_p2;
wire   [31:0] add_ln42_267_fu_66237_p2;
wire   [8:0] trunc_ln41_328_fu_66269_p1;
wire   [0:0] tmp_1315_fu_66279_p3;
wire   [0:0] icmp_ln41_394_fu_66273_p2;
wire   [0:0] or_ln41_810_fu_66287_p2;
wire   [0:0] tmp_1314_fu_66261_p3;
wire   [0:0] and_ln41_930_fu_66293_p2;
wire   [21:0] trunc_ln41_261_fu_66251_p4;
wire   [21:0] zext_ln41_266_fu_66299_p1;
wire  signed [21:0] a_250_fu_64728_p4;
wire   [31:0] mul_ln42_256_fu_835_p2;
wire   [31:0] add_ln42_268_fu_66322_p2;
wire   [8:0] trunc_ln41_329_fu_66354_p1;
wire   [0:0] tmp_1319_fu_66364_p3;
wire   [0:0] icmp_ln41_395_fu_66358_p2;
wire   [0:0] or_ln41_813_fu_66372_p2;
wire   [0:0] tmp_1318_fu_66346_p3;
wire   [0:0] and_ln41_932_fu_66378_p2;
wire   [21:0] trunc_ln41_262_fu_66336_p4;
wire   [21:0] zext_ln41_267_fu_66384_p1;
wire  signed [21:0] a_251_fu_64738_p4;
wire   [31:0] mul_ln42_257_fu_431_p2;
wire   [31:0] add_ln42_270_fu_66417_p2;
wire   [8:0] trunc_ln41_331_fu_66449_p1;
wire   [0:0] tmp_1330_fu_66459_p3;
wire   [0:0] icmp_ln41_397_fu_66453_p2;
wire   [0:0] or_ln41_819_fu_66467_p2;
wire   [0:0] tmp_1329_fu_66441_p3;
wire   [0:0] and_ln41_936_fu_66473_p2;
wire   [21:0] trunc_ln41_264_fu_66431_p4;
wire   [21:0] zext_ln41_269_fu_66479_p1;
wire  signed [21:0] a_252_fu_64748_p4;
wire   [31:0] mul_ln42_258_fu_603_p2;
wire   [31:0] add_ln42_271_fu_66502_p2;
wire   [8:0] trunc_ln41_332_fu_66534_p1;
wire   [0:0] tmp_1334_fu_66544_p3;
wire   [0:0] icmp_ln41_398_fu_66538_p2;
wire   [0:0] or_ln41_822_fu_66552_p2;
wire   [0:0] tmp_1333_fu_66526_p3;
wire   [0:0] and_ln41_938_fu_66558_p2;
wire   [21:0] trunc_ln41_265_fu_66516_p4;
wire   [21:0] zext_ln41_270_fu_66564_p1;
wire  signed [21:0] a_253_fu_64758_p4;
wire   [31:0] mul_ln42_259_fu_618_p2;
wire   [31:0] add_ln42_272_fu_66587_p2;
wire   [8:0] trunc_ln41_333_fu_66619_p1;
wire   [0:0] tmp_1338_fu_66629_p3;
wire   [0:0] icmp_ln41_399_fu_66623_p2;
wire   [0:0] or_ln41_825_fu_66637_p2;
wire   [0:0] tmp_1337_fu_66611_p3;
wire   [0:0] and_ln41_940_fu_66643_p2;
wire   [21:0] trunc_ln41_266_fu_66601_p4;
wire   [21:0] zext_ln41_271_fu_66649_p1;
wire  signed [21:0] a_254_fu_64768_p4;
wire   [31:0] mul_ln42_260_fu_666_p2;
wire   [31:0] add_ln42_273_fu_66672_p2;
wire   [8:0] trunc_ln41_334_fu_66704_p1;
wire   [0:0] tmp_1342_fu_66714_p3;
wire   [0:0] icmp_ln41_400_fu_66708_p2;
wire   [0:0] or_ln41_828_fu_66722_p2;
wire   [0:0] tmp_1341_fu_66696_p3;
wire   [0:0] and_ln41_942_fu_66728_p2;
wire   [21:0] trunc_ln41_267_fu_66686_p4;
wire   [21:0] zext_ln41_272_fu_66734_p1;
wire  signed [21:0] a_255_fu_64778_p4;
wire   [31:0] mul_ln42_261_fu_343_p2;
wire   [31:0] add_ln42_274_fu_66757_p2;
wire   [8:0] trunc_ln41_335_fu_66789_p1;
wire   [0:0] tmp_1346_fu_66799_p3;
wire   [0:0] icmp_ln41_401_fu_66793_p2;
wire   [0:0] or_ln41_831_fu_66807_p2;
wire   [0:0] tmp_1345_fu_66781_p3;
wire   [0:0] and_ln41_944_fu_66813_p2;
wire   [21:0] trunc_ln41_268_fu_66771_p4;
wire   [21:0] zext_ln41_273_fu_66819_p1;
wire  signed [21:0] a_256_fu_64788_p4;
wire   [31:0] mul_ln42_262_fu_636_p2;
wire   [31:0] add_ln42_275_fu_66842_p2;
wire   [8:0] trunc_ln41_336_fu_66874_p1;
wire   [0:0] tmp_1350_fu_66884_p3;
wire   [0:0] icmp_ln41_402_fu_66878_p2;
wire   [0:0] or_ln41_834_fu_66892_p2;
wire   [0:0] tmp_1349_fu_66866_p3;
wire   [0:0] and_ln41_946_fu_66898_p2;
wire   [21:0] trunc_ln41_269_fu_66856_p4;
wire   [21:0] zext_ln41_274_fu_66904_p1;
wire  signed [21:0] a_257_fu_64798_p4;
wire   [31:0] mul_ln42_263_fu_579_p2;
wire   [31:0] add_ln42_276_fu_66927_p2;
wire   [8:0] trunc_ln41_337_fu_66959_p1;
wire   [0:0] tmp_1354_fu_66969_p3;
wire   [0:0] icmp_ln41_403_fu_66963_p2;
wire   [0:0] or_ln41_837_fu_66977_p2;
wire   [0:0] tmp_1353_fu_66951_p3;
wire   [0:0] and_ln41_948_fu_66983_p2;
wire   [21:0] trunc_ln41_270_fu_66941_p4;
wire   [21:0] zext_ln41_275_fu_66989_p1;
wire  signed [21:0] a_258_fu_64808_p4;
wire   [31:0] mul_ln42_264_fu_673_p2;
wire   [31:0] add_ln42_277_fu_67012_p2;
wire   [8:0] trunc_ln41_338_fu_67044_p1;
wire   [0:0] tmp_1358_fu_67054_p3;
wire   [0:0] icmp_ln41_404_fu_67048_p2;
wire   [0:0] or_ln41_840_fu_67062_p2;
wire   [0:0] tmp_1357_fu_67036_p3;
wire   [0:0] and_ln41_950_fu_67068_p2;
wire   [21:0] trunc_ln41_271_fu_67026_p4;
wire   [21:0] zext_ln41_276_fu_67074_p1;
wire  signed [21:0] a_259_fu_64818_p4;
wire   [31:0] mul_ln42_265_fu_655_p2;
wire   [31:0] add_ln42_278_fu_67097_p2;
wire   [8:0] trunc_ln41_339_fu_67129_p1;
wire   [0:0] tmp_1362_fu_67139_p3;
wire   [0:0] icmp_ln41_405_fu_67133_p2;
wire   [0:0] or_ln41_843_fu_67147_p2;
wire   [0:0] tmp_1361_fu_67121_p3;
wire   [0:0] and_ln41_952_fu_67153_p2;
wire   [21:0] trunc_ln41_272_fu_67111_p4;
wire   [21:0] zext_ln41_277_fu_67159_p1;
wire  signed [21:0] a_260_fu_64828_p4;
wire   [31:0] mul_ln42_266_fu_624_p2;
wire   [31:0] add_ln42_279_fu_67182_p2;
wire   [8:0] trunc_ln41_340_fu_67214_p1;
wire   [0:0] tmp_1366_fu_67224_p3;
wire   [0:0] icmp_ln41_406_fu_67218_p2;
wire   [0:0] or_ln41_846_fu_67232_p2;
wire   [0:0] tmp_1365_fu_67206_p3;
wire   [0:0] and_ln41_954_fu_67238_p2;
wire   [21:0] trunc_ln41_273_fu_67196_p4;
wire   [21:0] zext_ln41_278_fu_67244_p1;
wire  signed [21:0] a_261_fu_64838_p4;
wire   [31:0] mul_ln42_267_fu_376_p2;
wire   [31:0] add_ln42_280_fu_67267_p2;
wire   [8:0] trunc_ln41_341_fu_67299_p1;
wire   [0:0] tmp_1370_fu_67309_p3;
wire   [0:0] icmp_ln41_407_fu_67303_p2;
wire   [0:0] or_ln41_849_fu_67317_p2;
wire   [0:0] tmp_1369_fu_67291_p3;
wire   [0:0] and_ln41_956_fu_67323_p2;
wire   [21:0] trunc_ln41_274_fu_67281_p4;
wire   [21:0] zext_ln41_279_fu_67329_p1;
wire  signed [21:0] a_262_fu_64848_p4;
wire   [31:0] mul_ln42_268_fu_342_p2;
wire   [31:0] add_ln42_281_fu_67352_p2;
wire   [8:0] trunc_ln41_342_fu_67384_p1;
wire   [0:0] tmp_1374_fu_67394_p3;
wire   [0:0] icmp_ln41_408_fu_67388_p2;
wire   [0:0] or_ln41_852_fu_67402_p2;
wire   [0:0] tmp_1373_fu_67376_p3;
wire   [0:0] and_ln41_958_fu_67408_p2;
wire   [21:0] trunc_ln41_275_fu_67366_p4;
wire   [21:0] zext_ln41_280_fu_67414_p1;
wire  signed [21:0] a_263_fu_64858_p4;
wire   [31:0] mul_ln42_269_fu_716_p2;
wire   [31:0] add_ln42_282_fu_67437_p2;
wire   [8:0] trunc_ln41_343_fu_67469_p1;
wire   [0:0] tmp_1378_fu_67479_p3;
wire   [0:0] icmp_ln41_409_fu_67473_p2;
wire   [0:0] or_ln41_855_fu_67487_p2;
wire   [0:0] tmp_1377_fu_67461_p3;
wire   [0:0] and_ln41_960_fu_67493_p2;
wire   [21:0] trunc_ln41_276_fu_67451_p4;
wire   [21:0] zext_ln41_281_fu_67499_p1;
wire   [0:0] xor_ln41_fu_67520_p2;
wire   [0:0] or_ln41_773_fu_67525_p2;
wire   [0:0] xor_ln41_1035_fu_67530_p2;
wire   [0:0] xor_ln41_1036_fu_67535_p2;
wire   [0:0] or_ln41_763_fu_67541_p2;
wire   [0:0] and_ln41_899_fu_67546_p2;
wire   [0:0] xor_ln41_1037_fu_67559_p2;
wire   [0:0] or_ln41_776_fu_67564_p2;
wire   [0:0] xor_ln41_1038_fu_67569_p2;
wire   [0:0] xor_ln41_1039_fu_67574_p2;
wire   [0:0] or_ln41_766_fu_67580_p2;
wire   [0:0] and_ln41_901_fu_67585_p2;
wire   [0:0] xor_ln41_1040_fu_67598_p2;
wire   [0:0] or_ln41_779_fu_67603_p2;
wire   [0:0] xor_ln41_1041_fu_67608_p2;
wire   [0:0] xor_ln41_1042_fu_67613_p2;
wire   [0:0] or_ln41_769_fu_67619_p2;
wire   [0:0] and_ln41_903_fu_67624_p2;
wire   [0:0] xor_ln41_1043_fu_67637_p2;
wire   [0:0] or_ln41_782_fu_67642_p2;
wire   [0:0] xor_ln41_1044_fu_67647_p2;
wire   [0:0] xor_ln41_1045_fu_67652_p2;
wire   [0:0] or_ln41_772_fu_67658_p2;
wire   [0:0] and_ln41_905_fu_67663_p2;
wire   [0:0] xor_ln41_1046_fu_67676_p2;
wire   [0:0] or_ln41_785_fu_67681_p2;
wire   [0:0] xor_ln41_1047_fu_67686_p2;
wire   [0:0] xor_ln41_1048_fu_67691_p2;
wire   [0:0] or_ln41_775_fu_67697_p2;
wire   [0:0] and_ln41_907_fu_67702_p2;
wire   [0:0] xor_ln41_1049_fu_67715_p2;
wire   [0:0] or_ln41_788_fu_67720_p2;
wire   [0:0] xor_ln41_1050_fu_67725_p2;
wire   [0:0] xor_ln41_1051_fu_67730_p2;
wire   [0:0] or_ln41_778_fu_67736_p2;
wire   [0:0] and_ln41_909_fu_67741_p2;
wire   [0:0] xor_ln41_1052_fu_67754_p2;
wire   [0:0] or_ln41_791_fu_67759_p2;
wire   [0:0] xor_ln41_1053_fu_67764_p2;
wire   [0:0] xor_ln41_1054_fu_67769_p2;
wire   [0:0] or_ln41_781_fu_67775_p2;
wire   [0:0] and_ln41_911_fu_67780_p2;
wire   [0:0] xor_ln41_1055_fu_67793_p2;
wire   [0:0] or_ln41_794_fu_67798_p2;
wire   [0:0] xor_ln41_1056_fu_67803_p2;
wire   [0:0] xor_ln41_1057_fu_67808_p2;
wire   [0:0] or_ln41_784_fu_67814_p2;
wire   [0:0] and_ln41_913_fu_67819_p2;
wire   [0:0] xor_ln41_1058_fu_67832_p2;
wire   [0:0] or_ln41_797_fu_67837_p2;
wire   [0:0] xor_ln41_1059_fu_67842_p2;
wire   [0:0] xor_ln41_1060_fu_67847_p2;
wire   [0:0] or_ln41_787_fu_67853_p2;
wire   [0:0] and_ln41_915_fu_67858_p2;
wire   [0:0] xor_ln41_1061_fu_67871_p2;
wire   [0:0] or_ln41_800_fu_67876_p2;
wire   [0:0] xor_ln41_1062_fu_67881_p2;
wire   [0:0] xor_ln41_1063_fu_67886_p2;
wire   [0:0] or_ln41_790_fu_67892_p2;
wire   [0:0] and_ln41_917_fu_67897_p2;
wire   [0:0] xor_ln41_1064_fu_67910_p2;
wire   [0:0] or_ln41_803_fu_67915_p2;
wire   [0:0] xor_ln41_1065_fu_67920_p2;
wire   [0:0] xor_ln41_1066_fu_67925_p2;
wire   [0:0] or_ln41_793_fu_67931_p2;
wire   [0:0] and_ln41_919_fu_67936_p2;
wire   [0:0] xor_ln41_1067_fu_67949_p2;
wire   [0:0] or_ln41_806_fu_67954_p2;
wire   [0:0] xor_ln41_1068_fu_67959_p2;
wire   [0:0] xor_ln41_1069_fu_67964_p2;
wire   [0:0] or_ln41_796_fu_67970_p2;
wire   [0:0] and_ln41_921_fu_67975_p2;
wire   [0:0] xor_ln41_1070_fu_67988_p2;
wire   [0:0] or_ln41_809_fu_67993_p2;
wire   [0:0] xor_ln41_1071_fu_67998_p2;
wire   [0:0] xor_ln41_1072_fu_68003_p2;
wire   [0:0] or_ln41_799_fu_68009_p2;
wire   [0:0] and_ln41_923_fu_68014_p2;
wire   [0:0] xor_ln41_1073_fu_68027_p2;
wire   [0:0] or_ln41_812_fu_68032_p2;
wire   [0:0] xor_ln41_1074_fu_68037_p2;
wire   [0:0] xor_ln41_1075_fu_68042_p2;
wire   [0:0] or_ln41_802_fu_68048_p2;
wire   [0:0] and_ln41_925_fu_68053_p2;
wire   [0:0] xor_ln41_1076_fu_68066_p2;
wire   [0:0] or_ln41_815_fu_68071_p2;
wire   [0:0] xor_ln41_1077_fu_68076_p2;
wire   [0:0] xor_ln41_1078_fu_68081_p2;
wire   [0:0] or_ln41_805_fu_68087_p2;
wire   [0:0] and_ln41_927_fu_68092_p2;
wire   [0:0] xor_ln41_1079_fu_68105_p2;
wire   [0:0] or_ln41_818_fu_68110_p2;
wire   [0:0] xor_ln41_1080_fu_68115_p2;
wire   [0:0] xor_ln41_1081_fu_68120_p2;
wire   [0:0] or_ln41_808_fu_68126_p2;
wire   [0:0] and_ln41_929_fu_68131_p2;
wire   [0:0] xor_ln41_1082_fu_68144_p2;
wire   [0:0] or_ln41_821_fu_68149_p2;
wire   [0:0] xor_ln41_1083_fu_68154_p2;
wire   [0:0] xor_ln41_1084_fu_68159_p2;
wire   [0:0] or_ln41_811_fu_68165_p2;
wire   [0:0] and_ln41_931_fu_68170_p2;
wire   [0:0] xor_ln41_1085_fu_68183_p2;
wire   [0:0] or_ln41_824_fu_68188_p2;
wire   [0:0] xor_ln41_1086_fu_68193_p2;
wire   [0:0] xor_ln41_1087_fu_68198_p2;
wire   [0:0] or_ln41_814_fu_68204_p2;
wire   [0:0] and_ln41_933_fu_68209_p2;
wire   [30:0] tmp_1322_fu_68222_p3;
wire   [26:0] tmp_1323_fu_68233_p3;
wire  signed [31:0] sext_ln42_269_fu_68229_p1;
wire  signed [31:0] sext_ln42_283_fu_68240_p1;
wire   [31:0] add_ln42_283_fu_68244_p2;
wire   [31:0] add_ln42_269_fu_68250_p2;
wire   [8:0] trunc_ln41_330_fu_68282_p1;
wire   [0:0] tmp_1326_fu_68292_p3;
wire   [0:0] icmp_ln41_396_fu_68286_p2;
wire   [0:0] or_ln41_816_fu_68300_p2;
wire   [0:0] tmp_1325_fu_68274_p3;
wire   [0:0] and_ln41_934_fu_68306_p2;
wire   [21:0] trunc_ln41_263_fu_68264_p4;
wire   [21:0] zext_ln41_268_fu_68312_p1;
wire   [21:0] add_ln41_268_fu_68316_p2;
wire   [0:0] tmp_1324_fu_68256_p3;
wire   [0:0] tmp_1327_fu_68322_p3;
wire   [0:0] xor_ln41_1088_fu_68330_p2;
wire   [0:0] or_ln41_827_fu_68336_p2;
wire   [0:0] xor_ln41_1089_fu_68342_p2;
wire   [0:0] xor_ln41_1090_fu_68348_p2;
wire   [0:0] or_ln41_817_fu_68354_p2;
wire   [0:0] and_ln41_935_fu_68360_p2;
wire   [0:0] xor_ln41_1091_fu_68374_p2;
wire   [0:0] or_ln41_830_fu_68379_p2;
wire   [0:0] xor_ln41_1092_fu_68384_p2;
wire   [0:0] xor_ln41_1093_fu_68389_p2;
wire   [0:0] or_ln41_820_fu_68395_p2;
wire   [0:0] and_ln41_937_fu_68400_p2;
wire   [0:0] xor_ln41_1094_fu_68413_p2;
wire   [0:0] or_ln41_833_fu_68418_p2;
wire   [0:0] xor_ln41_1095_fu_68423_p2;
wire   [0:0] xor_ln41_1096_fu_68428_p2;
wire   [0:0] or_ln41_823_fu_68434_p2;
wire   [0:0] and_ln41_939_fu_68439_p2;
wire   [0:0] xor_ln41_1097_fu_68452_p2;
wire   [0:0] or_ln41_836_fu_68457_p2;
wire   [0:0] xor_ln41_1098_fu_68462_p2;
wire   [0:0] xor_ln41_1099_fu_68467_p2;
wire   [0:0] or_ln41_826_fu_68473_p2;
wire   [0:0] and_ln41_941_fu_68478_p2;
wire   [0:0] xor_ln41_1100_fu_68491_p2;
wire   [0:0] or_ln41_839_fu_68496_p2;
wire   [0:0] xor_ln41_1101_fu_68501_p2;
wire   [0:0] xor_ln41_1102_fu_68506_p2;
wire   [0:0] or_ln41_829_fu_68512_p2;
wire   [0:0] and_ln41_943_fu_68517_p2;
wire   [0:0] xor_ln41_1103_fu_68530_p2;
wire   [0:0] or_ln41_842_fu_68535_p2;
wire   [0:0] xor_ln41_1104_fu_68540_p2;
wire   [0:0] xor_ln41_1105_fu_68545_p2;
wire   [0:0] or_ln41_832_fu_68551_p2;
wire   [0:0] and_ln41_945_fu_68556_p2;
wire   [0:0] xor_ln41_1106_fu_68569_p2;
wire   [0:0] or_ln41_845_fu_68574_p2;
wire   [0:0] xor_ln41_1107_fu_68579_p2;
wire   [0:0] xor_ln41_1108_fu_68584_p2;
wire   [0:0] or_ln41_835_fu_68590_p2;
wire   [0:0] and_ln41_947_fu_68595_p2;
wire   [0:0] xor_ln41_1109_fu_68608_p2;
wire   [0:0] or_ln41_848_fu_68613_p2;
wire   [0:0] xor_ln41_1110_fu_68618_p2;
wire   [0:0] xor_ln41_1111_fu_68623_p2;
wire   [0:0] or_ln41_838_fu_68629_p2;
wire   [0:0] and_ln41_949_fu_68634_p2;
wire   [0:0] xor_ln41_1112_fu_68647_p2;
wire   [0:0] or_ln41_851_fu_68652_p2;
wire   [0:0] xor_ln41_1113_fu_68657_p2;
wire   [0:0] xor_ln41_1114_fu_68662_p2;
wire   [0:0] or_ln41_841_fu_68668_p2;
wire   [0:0] and_ln41_951_fu_68673_p2;
wire   [0:0] xor_ln41_1115_fu_68686_p2;
wire   [0:0] or_ln41_854_fu_68691_p2;
wire   [0:0] xor_ln41_1116_fu_68696_p2;
wire   [0:0] xor_ln41_1117_fu_68701_p2;
wire   [0:0] or_ln41_844_fu_68707_p2;
wire   [0:0] and_ln41_953_fu_68712_p2;
wire   [0:0] xor_ln41_1118_fu_68725_p2;
wire   [0:0] or_ln41_857_fu_68730_p2;
wire   [0:0] xor_ln41_1119_fu_68735_p2;
wire   [0:0] xor_ln41_1120_fu_68740_p2;
wire   [0:0] or_ln41_847_fu_68746_p2;
wire   [0:0] and_ln41_955_fu_68751_p2;
wire   [0:0] xor_ln41_1121_fu_68764_p2;
wire   [0:0] or_ln41_858_fu_68769_p2;
wire   [0:0] xor_ln41_1122_fu_68774_p2;
wire   [0:0] xor_ln41_1123_fu_68779_p2;
wire   [0:0] or_ln41_850_fu_68785_p2;
wire   [0:0] and_ln41_957_fu_68790_p2;
wire   [0:0] xor_ln41_1124_fu_68803_p2;
wire   [0:0] or_ln41_859_fu_68808_p2;
wire   [0:0] xor_ln41_1125_fu_68813_p2;
wire   [0:0] xor_ln41_1126_fu_68818_p2;
wire   [0:0] or_ln41_853_fu_68824_p2;
wire   [0:0] and_ln41_959_fu_68829_p2;
wire   [0:0] xor_ln41_1127_fu_68842_p2;
wire   [0:0] or_ln41_860_fu_68847_p2;
wire   [0:0] xor_ln41_1128_fu_68852_p2;
wire   [0:0] xor_ln41_1129_fu_68857_p2;
wire   [0:0] or_ln41_856_fu_68863_p2;
wire   [0:0] and_ln41_961_fu_68868_p2;
wire   [21:0] select_ln41_547_fu_68874_p3;
wire   [21:0] select_ln41_546_fu_68835_p3;
wire   [21:0] select_ln41_545_fu_68796_p3;
wire   [21:0] select_ln41_544_fu_68757_p3;
wire   [21:0] select_ln41_543_fu_68718_p3;
wire   [21:0] select_ln41_542_fu_68679_p3;
wire   [21:0] select_ln41_541_fu_68640_p3;
wire   [21:0] select_ln41_540_fu_68601_p3;
wire   [21:0] select_ln41_539_fu_68562_p3;
wire   [21:0] select_ln41_538_fu_68523_p3;
wire   [21:0] select_ln41_537_fu_68484_p3;
wire   [21:0] select_ln41_536_fu_68445_p3;
wire   [21:0] select_ln41_535_fu_68406_p3;
wire   [21:0] select_ln41_534_fu_68366_p3;
wire   [21:0] select_ln41_533_fu_68215_p3;
wire   [21:0] select_ln41_532_fu_68176_p3;
wire   [21:0] select_ln41_531_fu_68137_p3;
wire   [21:0] select_ln41_530_fu_68098_p3;
wire   [21:0] select_ln41_529_fu_68059_p3;
wire   [21:0] select_ln41_528_fu_68020_p3;
wire   [21:0] select_ln41_527_fu_67981_p3;
wire   [21:0] select_ln41_526_fu_67942_p3;
wire   [21:0] select_ln41_525_fu_67903_p3;
wire   [21:0] select_ln41_524_fu_67864_p3;
wire   [21:0] select_ln41_523_fu_67825_p3;
wire   [21:0] select_ln41_522_fu_67786_p3;
wire   [21:0] select_ln41_521_fu_67747_p3;
wire   [21:0] select_ln41_520_fu_67708_p3;
wire   [21:0] select_ln41_519_fu_67669_p3;
wire   [21:0] select_ln41_518_fu_67630_p3;
wire   [21:0] select_ln41_517_fu_67591_p3;
wire   [21:0] select_ln41_fu_67552_p3;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_start_int;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
#0 i_021_fu_324 = 8'd0;
end

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1396(
    .din0(a_262_fu_64848_p4),
    .din1(mul_ln42_268_fu_342_p1),
    .dout(mul_ln42_268_fu_342_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1397(
    .din0(a_255_fu_64778_p4),
    .din1(mul_ln42_261_fu_343_p1),
    .dout(mul_ln42_261_fu_343_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1398(
    .din0(a_241_fu_64638_p4),
    .din1(mul_ln42_247_fu_345_p1),
    .dout(mul_ln42_247_fu_345_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1399(
    .din0(a_243_fu_64658_p4),
    .din1(mul_ln42_249_fu_369_p1),
    .dout(mul_ln42_249_fu_369_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1400(
    .din0(a_236_fu_64588_p4),
    .din1(mul_ln42_242_fu_370_p1),
    .dout(mul_ln42_242_fu_370_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1401(
    .din0(a_261_fu_64838_p4),
    .din1(mul_ln42_267_fu_376_p1),
    .dout(mul_ln42_267_fu_376_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1402(
    .din0(a_248_fu_64708_p4),
    .din1(mul_ln42_254_fu_425_p1),
    .dout(mul_ln42_254_fu_425_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1403(
    .din0(a_251_fu_64738_p4),
    .din1(mul_ln42_257_fu_431_p1),
    .dout(mul_ln42_257_fu_431_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1404(
    .din0(a_249_fu_64718_p4),
    .din1(mul_ln42_255_fu_438_p1),
    .dout(mul_ln42_255_fu_438_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1405(
    .din0(a_246_fu_64688_p4),
    .din1(mul_ln42_252_fu_442_p1),
    .dout(mul_ln42_252_fu_442_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1406(
    .din0(a_fu_64564_p1),
    .din1(mul_ln42_fu_447_p1),
    .dout(mul_ln42_fu_447_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1407(
    .din0(a_257_fu_64798_p4),
    .din1(mul_ln42_263_fu_579_p1),
    .dout(mul_ln42_263_fu_579_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1408(
    .din0(a_252_fu_64748_p4),
    .din1(mul_ln42_258_fu_603_p1),
    .dout(mul_ln42_258_fu_603_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1409(
    .din0(a_239_fu_64618_p4),
    .din1(mul_ln42_245_fu_605_p1),
    .dout(mul_ln42_245_fu_605_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1410(
    .din0(a_242_fu_64648_p4),
    .din1(mul_ln42_248_fu_611_p1),
    .dout(mul_ln42_248_fu_611_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1411(
    .din0(a_247_fu_64698_p4),
    .din1(mul_ln42_253_fu_613_p1),
    .dout(mul_ln42_253_fu_613_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1412(
    .din0(a_253_fu_64758_p4),
    .din1(mul_ln42_259_fu_618_p1),
    .dout(mul_ln42_259_fu_618_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1413(
    .din0(a_260_fu_64828_p4),
    .din1(mul_ln42_266_fu_624_p1),
    .dout(mul_ln42_266_fu_624_p2)
);

resnet8_resource_fifo_opt_mul_22s_10ns_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 31 ))
mul_22s_10ns_31_1_1_U1414(
    .din0(a_264_fu_64568_p4),
    .din1(mul_ln42_240_fu_632_p1),
    .dout(mul_ln42_240_fu_632_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1415(
    .din0(a_256_fu_64788_p4),
    .din1(mul_ln42_262_fu_636_p1),
    .dout(mul_ln42_262_fu_636_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1416(
    .din0(a_259_fu_64818_p4),
    .din1(mul_ln42_265_fu_655_p1),
    .dout(mul_ln42_265_fu_655_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1417(
    .din0(a_254_fu_64768_p4),
    .din1(mul_ln42_260_fu_666_p1),
    .dout(mul_ln42_260_fu_666_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1418(
    .din0(a_258_fu_64808_p4),
    .din1(mul_ln42_264_fu_673_p1),
    .dout(mul_ln42_264_fu_673_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1419(
    .din0(a_263_fu_64858_p4),
    .din1(mul_ln42_269_fu_716_p1),
    .dout(mul_ln42_269_fu_716_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1420(
    .din0(a_235_fu_64578_p4),
    .din1(mul_ln42_241_fu_720_p1),
    .dout(mul_ln42_241_fu_720_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1421(
    .din0(a_240_fu_64628_p4),
    .din1(mul_ln42_246_fu_749_p1),
    .dout(mul_ln42_246_fu_749_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1422(
    .din0(a_244_fu_64668_p4),
    .din1(mul_ln42_250_fu_756_p1),
    .dout(mul_ln42_250_fu_756_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1423(
    .din0(a_237_fu_64598_p4),
    .din1(mul_ln42_243_fu_784_p1),
    .dout(mul_ln42_243_fu_784_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1424(
    .din0(a_238_fu_64608_p4),
    .din1(mul_ln42_244_fu_793_p1),
    .dout(mul_ln42_244_fu_793_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1425(
    .din0(a_250_fu_64728_p4),
    .din1(mul_ln42_256_fu_835_p1),
    .dout(mul_ln42_256_fu_835_p2)
);

resnet8_resource_fifo_opt_mul_22s_11ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_22s_11ns_32_1_1_U1426(
    .din0(a_245_fu_64678_p4),
    .din1(mul_ln42_251_fu_846_p1),
    .dout(mul_ln42_251_fu_846_p2)
);

resnet8_resource_fifo_opt_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_021_fu_324 <= 8'd0;
    end else if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_021_fu_324 <= i_fu_68950_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        add_ln41_251_reg_68997 <= add_ln41_251_fu_65028_p2;
        add_ln41_252_reg_69014 <= add_ln41_252_fu_65113_p2;
        add_ln41_253_reg_69031 <= add_ln41_253_fu_65198_p2;
        add_ln41_254_reg_69048 <= add_ln41_254_fu_65283_p2;
        add_ln41_255_reg_69065 <= add_ln41_255_fu_65368_p2;
        add_ln41_256_reg_69082 <= add_ln41_256_fu_65453_p2;
        add_ln41_257_reg_69099 <= add_ln41_257_fu_65538_p2;
        add_ln41_258_reg_69116 <= add_ln41_258_fu_65623_p2;
        add_ln41_259_reg_69133 <= add_ln41_259_fu_65708_p2;
        add_ln41_260_reg_69150 <= add_ln41_260_fu_65793_p2;
        add_ln41_261_reg_69167 <= add_ln41_261_fu_65878_p2;
        add_ln41_262_reg_69184 <= add_ln41_262_fu_65963_p2;
        add_ln41_263_reg_69201 <= add_ln41_263_fu_66048_p2;
        add_ln41_264_reg_69218 <= add_ln41_264_fu_66133_p2;
        add_ln41_265_reg_69235 <= add_ln41_265_fu_66218_p2;
        add_ln41_266_reg_69252 <= add_ln41_266_fu_66303_p2;
        add_ln41_267_reg_69269 <= add_ln41_267_fu_66388_p2;
        add_ln41_269_reg_69292 <= add_ln41_269_fu_66483_p2;
        add_ln41_270_reg_69309 <= add_ln41_270_fu_66568_p2;
        add_ln41_271_reg_69326 <= add_ln41_271_fu_66653_p2;
        add_ln41_272_reg_69343 <= add_ln41_272_fu_66738_p2;
        add_ln41_273_reg_69360 <= add_ln41_273_fu_66823_p2;
        add_ln41_274_reg_69377 <= add_ln41_274_fu_66908_p2;
        add_ln41_275_reg_69394 <= add_ln41_275_fu_66993_p2;
        add_ln41_276_reg_69411 <= add_ln41_276_fu_67078_p2;
        add_ln41_277_reg_69428 <= add_ln41_277_fu_67163_p2;
        add_ln41_278_reg_69445 <= add_ln41_278_fu_67248_p2;
        add_ln41_279_reg_69462 <= add_ln41_279_fu_67333_p2;
        add_ln41_280_reg_69479 <= add_ln41_280_fu_67418_p2;
        add_ln41_281_reg_69496 <= add_ln41_281_fu_67503_p2;
        add_ln41_reg_68980 <= add_ln41_fu_64939_p2;
        tmp_1252_reg_68985 <= add_ln41_fu_64939_p2[32'd21];
        tmp_1253_reg_68991 <= add_ln42_252_fu_64958_p2[32'd30];
        tmp_1256_reg_69002 <= add_ln41_251_fu_65028_p2[32'd21];
        tmp_1257_reg_69008 <= add_ln42_253_fu_65047_p2[32'd31];
        tmp_1260_reg_69019 <= add_ln41_252_fu_65113_p2[32'd21];
        tmp_1261_reg_69025 <= add_ln42_254_fu_65132_p2[32'd31];
        tmp_1264_reg_69036 <= add_ln41_253_fu_65198_p2[32'd21];
        tmp_1265_reg_69042 <= add_ln42_255_fu_65217_p2[32'd31];
        tmp_1268_reg_69053 <= add_ln41_254_fu_65283_p2[32'd21];
        tmp_1269_reg_69059 <= add_ln42_256_fu_65302_p2[32'd31];
        tmp_1272_reg_69070 <= add_ln41_255_fu_65368_p2[32'd21];
        tmp_1273_reg_69076 <= add_ln42_257_fu_65387_p2[32'd31];
        tmp_1276_reg_69087 <= add_ln41_256_fu_65453_p2[32'd21];
        tmp_1277_reg_69093 <= add_ln42_258_fu_65472_p2[32'd31];
        tmp_1280_reg_69104 <= add_ln41_257_fu_65538_p2[32'd21];
        tmp_1281_reg_69110 <= add_ln42_259_fu_65557_p2[32'd31];
        tmp_1284_reg_69121 <= add_ln41_258_fu_65623_p2[32'd21];
        tmp_1285_reg_69127 <= add_ln42_260_fu_65642_p2[32'd31];
        tmp_1288_reg_69138 <= add_ln41_259_fu_65708_p2[32'd21];
        tmp_1289_reg_69144 <= add_ln42_261_fu_65727_p2[32'd31];
        tmp_1292_reg_69155 <= add_ln41_260_fu_65793_p2[32'd21];
        tmp_1293_reg_69161 <= add_ln42_262_fu_65812_p2[32'd31];
        tmp_1296_reg_69172 <= add_ln41_261_fu_65878_p2[32'd21];
        tmp_1297_reg_69178 <= add_ln42_263_fu_65897_p2[32'd31];
        tmp_1300_reg_69189 <= add_ln41_262_fu_65963_p2[32'd21];
        tmp_1301_reg_69195 <= add_ln42_264_fu_65982_p2[32'd31];
        tmp_1304_reg_69206 <= add_ln41_263_fu_66048_p2[32'd21];
        tmp_1305_reg_69212 <= add_ln42_265_fu_66067_p2[32'd31];
        tmp_1308_reg_69223 <= add_ln41_264_fu_66133_p2[32'd21];
        tmp_1309_reg_69229 <= add_ln42_266_fu_66152_p2[32'd31];
        tmp_1312_reg_69240 <= add_ln41_265_fu_66218_p2[32'd21];
        tmp_1313_reg_69246 <= add_ln42_267_fu_66237_p2[32'd31];
        tmp_1316_reg_69257 <= add_ln41_266_fu_66303_p2[32'd21];
        tmp_1317_reg_69263 <= add_ln42_268_fu_66322_p2[32'd31];
        tmp_1320_reg_69274 <= add_ln41_267_fu_66388_p2[32'd21];
        tmp_1321_reg_69280 <= {{layer12_out_dout[417:396]}};
        tmp_1328_reg_69286 <= add_ln42_270_fu_66417_p2[32'd31];
        tmp_1331_reg_69297 <= add_ln41_269_fu_66483_p2[32'd21];
        tmp_1332_reg_69303 <= add_ln42_271_fu_66502_p2[32'd31];
        tmp_1335_reg_69314 <= add_ln41_270_fu_66568_p2[32'd21];
        tmp_1336_reg_69320 <= add_ln42_272_fu_66587_p2[32'd31];
        tmp_1339_reg_69331 <= add_ln41_271_fu_66653_p2[32'd21];
        tmp_1340_reg_69337 <= add_ln42_273_fu_66672_p2[32'd31];
        tmp_1343_reg_69348 <= add_ln41_272_fu_66738_p2[32'd21];
        tmp_1344_reg_69354 <= add_ln42_274_fu_66757_p2[32'd31];
        tmp_1347_reg_69365 <= add_ln41_273_fu_66823_p2[32'd21];
        tmp_1348_reg_69371 <= add_ln42_275_fu_66842_p2[32'd31];
        tmp_1351_reg_69382 <= add_ln41_274_fu_66908_p2[32'd21];
        tmp_1352_reg_69388 <= add_ln42_276_fu_66927_p2[32'd31];
        tmp_1355_reg_69399 <= add_ln41_275_fu_66993_p2[32'd21];
        tmp_1356_reg_69405 <= add_ln42_277_fu_67012_p2[32'd31];
        tmp_1359_reg_69416 <= add_ln41_276_fu_67078_p2[32'd21];
        tmp_1360_reg_69422 <= add_ln42_278_fu_67097_p2[32'd31];
        tmp_1363_reg_69433 <= add_ln41_277_fu_67163_p2[32'd21];
        tmp_1364_reg_69439 <= add_ln42_279_fu_67182_p2[32'd31];
        tmp_1367_reg_69450 <= add_ln41_278_fu_67248_p2[32'd21];
        tmp_1368_reg_69456 <= add_ln42_280_fu_67267_p2[32'd31];
        tmp_1371_reg_69467 <= add_ln41_279_fu_67333_p2[32'd21];
        tmp_1372_reg_69473 <= add_ln42_281_fu_67352_p2[32'd31];
        tmp_1375_reg_69484 <= add_ln41_280_fu_67418_p2[32'd21];
        tmp_1376_reg_69490 <= add_ln42_282_fu_67437_p2[32'd31];
        tmp_1379_reg_69501 <= add_ln41_281_fu_67503_p2[32'd21];
        tmp_reg_68974 <= add_ln42_fu_64873_p2[32'd31];
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_pp0_stage1_iter0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln25_fu_68956_p2 == 1'd1) & (1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer12_out_blk_n = layer12_out_empty_n;
    end else begin
        layer12_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        layer12_out_read = 1'b1;
    end else begin
        layer12_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        layer13_out_blk_n = layer13_out_full_n;
    end else begin
        layer13_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer13_out_write = 1'b1;
    end else begin
        layer13_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_235_fu_64578_p4 = {{layer12_out_dout[65:44]}};

assign a_236_fu_64588_p4 = {{layer12_out_dout[87:66]}};

assign a_237_fu_64598_p4 = {{layer12_out_dout[109:88]}};

assign a_238_fu_64608_p4 = {{layer12_out_dout[131:110]}};

assign a_239_fu_64618_p4 = {{layer12_out_dout[153:132]}};

assign a_240_fu_64628_p4 = {{layer12_out_dout[175:154]}};

assign a_241_fu_64638_p4 = {{layer12_out_dout[197:176]}};

assign a_242_fu_64648_p4 = {{layer12_out_dout[219:198]}};

assign a_243_fu_64658_p4 = {{layer12_out_dout[241:220]}};

assign a_244_fu_64668_p4 = {{layer12_out_dout[263:242]}};

assign a_245_fu_64678_p4 = {{layer12_out_dout[285:264]}};

assign a_246_fu_64688_p4 = {{layer12_out_dout[307:286]}};

assign a_247_fu_64698_p4 = {{layer12_out_dout[329:308]}};

assign a_248_fu_64708_p4 = {{layer12_out_dout[351:330]}};

assign a_249_fu_64718_p4 = {{layer12_out_dout[373:352]}};

assign a_250_fu_64728_p4 = {{layer12_out_dout[395:374]}};

assign a_251_fu_64738_p4 = {{layer12_out_dout[439:418]}};

assign a_252_fu_64748_p4 = {{layer12_out_dout[461:440]}};

assign a_253_fu_64758_p4 = {{layer12_out_dout[483:462]}};

assign a_254_fu_64768_p4 = {{layer12_out_dout[505:484]}};

assign a_255_fu_64778_p4 = {{layer12_out_dout[527:506]}};

assign a_256_fu_64788_p4 = {{layer12_out_dout[549:528]}};

assign a_257_fu_64798_p4 = {{layer12_out_dout[571:550]}};

assign a_258_fu_64808_p4 = {{layer12_out_dout[593:572]}};

assign a_259_fu_64818_p4 = {{layer12_out_dout[615:594]}};

assign a_260_fu_64828_p4 = {{layer12_out_dout[637:616]}};

assign a_261_fu_64838_p4 = {{layer12_out_dout[659:638]}};

assign a_262_fu_64848_p4 = {{layer12_out_dout[681:660]}};

assign a_263_fu_64858_p4 = {{layer12_out_dout[703:682]}};

assign a_264_fu_64568_p4 = {{layer12_out_dout[43:22]}};

assign a_fu_64564_p1 = layer12_out_dout[21:0];

assign add_ln41_251_fu_65028_p2 = ($signed(sext_ln41_fu_64982_p1) + $signed(zext_ln41_251_fu_65024_p1));

assign add_ln41_252_fu_65113_p2 = (trunc_ln41_247_fu_65061_p4 + zext_ln41_252_fu_65109_p1);

assign add_ln41_253_fu_65198_p2 = (trunc_ln41_248_fu_65146_p4 + zext_ln41_253_fu_65194_p1);

assign add_ln41_254_fu_65283_p2 = (trunc_ln41_249_fu_65231_p4 + zext_ln41_254_fu_65279_p1);

assign add_ln41_255_fu_65368_p2 = (trunc_ln41_250_fu_65316_p4 + zext_ln41_255_fu_65364_p1);

assign add_ln41_256_fu_65453_p2 = (trunc_ln41_251_fu_65401_p4 + zext_ln41_256_fu_65449_p1);

assign add_ln41_257_fu_65538_p2 = (trunc_ln41_252_fu_65486_p4 + zext_ln41_257_fu_65534_p1);

assign add_ln41_258_fu_65623_p2 = (trunc_ln41_253_fu_65571_p4 + zext_ln41_258_fu_65619_p1);

assign add_ln41_259_fu_65708_p2 = (trunc_ln41_254_fu_65656_p4 + zext_ln41_259_fu_65704_p1);

assign add_ln41_260_fu_65793_p2 = (trunc_ln41_255_fu_65741_p4 + zext_ln41_260_fu_65789_p1);

assign add_ln41_261_fu_65878_p2 = (trunc_ln41_256_fu_65826_p4 + zext_ln41_261_fu_65874_p1);

assign add_ln41_262_fu_65963_p2 = (trunc_ln41_257_fu_65911_p4 + zext_ln41_262_fu_65959_p1);

assign add_ln41_263_fu_66048_p2 = (trunc_ln41_258_fu_65996_p4 + zext_ln41_263_fu_66044_p1);

assign add_ln41_264_fu_66133_p2 = (trunc_ln41_259_fu_66081_p4 + zext_ln41_264_fu_66129_p1);

assign add_ln41_265_fu_66218_p2 = (trunc_ln41_260_fu_66166_p4 + zext_ln41_265_fu_66214_p1);

assign add_ln41_266_fu_66303_p2 = (trunc_ln41_261_fu_66251_p4 + zext_ln41_266_fu_66299_p1);

assign add_ln41_267_fu_66388_p2 = (trunc_ln41_262_fu_66336_p4 + zext_ln41_267_fu_66384_p1);

assign add_ln41_268_fu_68316_p2 = (trunc_ln41_263_fu_68264_p4 + zext_ln41_268_fu_68312_p1);

assign add_ln41_269_fu_66483_p2 = (trunc_ln41_264_fu_66431_p4 + zext_ln41_269_fu_66479_p1);

assign add_ln41_270_fu_66568_p2 = (trunc_ln41_265_fu_66516_p4 + zext_ln41_270_fu_66564_p1);

assign add_ln41_271_fu_66653_p2 = (trunc_ln41_266_fu_66601_p4 + zext_ln41_271_fu_66649_p1);

assign add_ln41_272_fu_66738_p2 = (trunc_ln41_267_fu_66686_p4 + zext_ln41_272_fu_66734_p1);

assign add_ln41_273_fu_66823_p2 = (trunc_ln41_268_fu_66771_p4 + zext_ln41_273_fu_66819_p1);

assign add_ln41_274_fu_66908_p2 = (trunc_ln41_269_fu_66856_p4 + zext_ln41_274_fu_66904_p1);

assign add_ln41_275_fu_66993_p2 = (trunc_ln41_270_fu_66941_p4 + zext_ln41_275_fu_66989_p1);

assign add_ln41_276_fu_67078_p2 = (trunc_ln41_271_fu_67026_p4 + zext_ln41_276_fu_67074_p1);

assign add_ln41_277_fu_67163_p2 = (trunc_ln41_272_fu_67111_p4 + zext_ln41_277_fu_67159_p1);

assign add_ln41_278_fu_67248_p2 = (trunc_ln41_273_fu_67196_p4 + zext_ln41_278_fu_67244_p1);

assign add_ln41_279_fu_67333_p2 = (trunc_ln41_274_fu_67281_p4 + zext_ln41_279_fu_67329_p1);

assign add_ln41_280_fu_67418_p2 = (trunc_ln41_275_fu_67366_p4 + zext_ln41_280_fu_67414_p1);

assign add_ln41_281_fu_67503_p2 = (trunc_ln41_276_fu_67451_p4 + zext_ln41_281_fu_67499_p1);

assign add_ln41_fu_64939_p2 = (trunc_ln_fu_64887_p4 + zext_ln41_fu_64935_p1);

assign add_ln42_252_fu_64958_p2 = (mul_ln42_240_fu_632_p2 + 31'd1207296);

assign add_ln42_253_fu_65047_p2 = ($signed(mul_ln42_241_fu_720_p2) + $signed(32'd4293983232));

assign add_ln42_254_fu_65132_p2 = (mul_ln42_242_fu_370_p2 + 32'd1353728);

assign add_ln42_255_fu_65217_p2 = (mul_ln42_243_fu_784_p2 + 32'd894976);

assign add_ln42_256_fu_65302_p2 = (mul_ln42_244_fu_793_p2 + 32'd1210368);

assign add_ln42_257_fu_65387_p2 = (mul_ln42_245_fu_605_p2 + 32'd1120256);

assign add_ln42_258_fu_65472_p2 = (mul_ln42_246_fu_749_p2 + 32'd1492992);

assign add_ln42_259_fu_65557_p2 = ($signed(mul_ln42_247_fu_345_p2) + $signed(32'd4294773760));

assign add_ln42_260_fu_65642_p2 = (mul_ln42_248_fu_611_p2 + 32'd900096);

assign add_ln42_261_fu_65727_p2 = (mul_ln42_249_fu_369_p2 + 32'd40960);

assign add_ln42_262_fu_65812_p2 = ($signed(mul_ln42_250_fu_756_p2) + $signed(32'd4293723136));

assign add_ln42_263_fu_65897_p2 = ($signed(mul_ln42_251_fu_846_p2) + $signed(32'd4294845440));

assign add_ln42_264_fu_65982_p2 = ($signed(mul_ln42_252_fu_442_p2) + $signed(32'd4294171648));

assign add_ln42_265_fu_66067_p2 = (mul_ln42_253_fu_613_p2 + 32'd1643520);

assign add_ln42_266_fu_66152_p2 = ($signed(mul_ln42_254_fu_425_p2) + $signed(32'd4294732800));

assign add_ln42_267_fu_66237_p2 = (mul_ln42_255_fu_438_p2 + 32'd1032192);

assign add_ln42_268_fu_66322_p2 = (mul_ln42_256_fu_835_p2 + 32'd1215488);

assign add_ln42_269_fu_68250_p2 = (add_ln42_283_fu_68244_p2 + 32'd943104);

assign add_ln42_270_fu_66417_p2 = (mul_ln42_257_fu_431_p2 + 32'd1309696);

assign add_ln42_271_fu_66502_p2 = (mul_ln42_258_fu_603_p2 + 32'd287744);

assign add_ln42_272_fu_66587_p2 = ($signed(mul_ln42_259_fu_618_p2) + $signed(32'd4294321152));

assign add_ln42_273_fu_66672_p2 = (mul_ln42_260_fu_666_p2 + 32'd222208);

assign add_ln42_274_fu_66757_p2 = (mul_ln42_261_fu_343_p2 + 32'd926720);

assign add_ln42_275_fu_66842_p2 = (mul_ln42_262_fu_636_p2 + 32'd756736);

assign add_ln42_276_fu_66927_p2 = (mul_ln42_263_fu_579_p2 + 32'd1413120);

assign add_ln42_277_fu_67012_p2 = (mul_ln42_264_fu_673_p2 + 32'd2000896);

assign add_ln42_278_fu_67097_p2 = (mul_ln42_265_fu_655_p2 + 32'd1278976);

assign add_ln42_279_fu_67182_p2 = (mul_ln42_266_fu_624_p2 + 32'd1336320);

assign add_ln42_280_fu_67267_p2 = (mul_ln42_267_fu_376_p2 + 32'd168960);

assign add_ln42_281_fu_67352_p2 = (mul_ln42_268_fu_342_p2 + 32'd816128);

assign add_ln42_282_fu_67437_p2 = (mul_ln42_269_fu_716_p2 + 32'd320512);

assign add_ln42_283_fu_68244_p2 = ($signed(sext_ln42_269_fu_68229_p1) + $signed(sext_ln42_283_fu_68240_p1));

assign add_ln42_fu_64873_p2 = ($signed(mul_ln42_fu_447_p2) + $signed(32'd4294557696));

assign and_ln41_899_fu_67546_p2 = (xor_ln41_fu_67520_p2 & or_ln41_763_fu_67541_p2);

assign and_ln41_900_fu_65018_p2 = (tmp_1254_fu_64986_p3 & or_ln41_765_fu_65012_p2);

assign and_ln41_901_fu_67585_p2 = (xor_ln41_1037_fu_67559_p2 & or_ln41_766_fu_67580_p2);

assign and_ln41_902_fu_65103_p2 = (tmp_1258_fu_65071_p3 & or_ln41_768_fu_65097_p2);

assign and_ln41_903_fu_67624_p2 = (xor_ln41_1040_fu_67598_p2 & or_ln41_769_fu_67619_p2);

assign and_ln41_904_fu_65188_p2 = (tmp_1262_fu_65156_p3 & or_ln41_771_fu_65182_p2);

assign and_ln41_905_fu_67663_p2 = (xor_ln41_1043_fu_67637_p2 & or_ln41_772_fu_67658_p2);

assign and_ln41_906_fu_65273_p2 = (tmp_1266_fu_65241_p3 & or_ln41_774_fu_65267_p2);

assign and_ln41_907_fu_67702_p2 = (xor_ln41_1046_fu_67676_p2 & or_ln41_775_fu_67697_p2);

assign and_ln41_908_fu_65358_p2 = (tmp_1270_fu_65326_p3 & or_ln41_777_fu_65352_p2);

assign and_ln41_909_fu_67741_p2 = (xor_ln41_1049_fu_67715_p2 & or_ln41_778_fu_67736_p2);

assign and_ln41_910_fu_65443_p2 = (tmp_1274_fu_65411_p3 & or_ln41_780_fu_65437_p2);

assign and_ln41_911_fu_67780_p2 = (xor_ln41_1052_fu_67754_p2 & or_ln41_781_fu_67775_p2);

assign and_ln41_912_fu_65528_p2 = (tmp_1278_fu_65496_p3 & or_ln41_783_fu_65522_p2);

assign and_ln41_913_fu_67819_p2 = (xor_ln41_1055_fu_67793_p2 & or_ln41_784_fu_67814_p2);

assign and_ln41_914_fu_65613_p2 = (tmp_1282_fu_65581_p3 & or_ln41_786_fu_65607_p2);

assign and_ln41_915_fu_67858_p2 = (xor_ln41_1058_fu_67832_p2 & or_ln41_787_fu_67853_p2);

assign and_ln41_916_fu_65698_p2 = (tmp_1286_fu_65666_p3 & or_ln41_789_fu_65692_p2);

assign and_ln41_917_fu_67897_p2 = (xor_ln41_1061_fu_67871_p2 & or_ln41_790_fu_67892_p2);

assign and_ln41_918_fu_65783_p2 = (tmp_1290_fu_65751_p3 & or_ln41_792_fu_65777_p2);

assign and_ln41_919_fu_67936_p2 = (xor_ln41_1064_fu_67910_p2 & or_ln41_793_fu_67931_p2);

assign and_ln41_920_fu_65868_p2 = (tmp_1294_fu_65836_p3 & or_ln41_795_fu_65862_p2);

assign and_ln41_921_fu_67975_p2 = (xor_ln41_1067_fu_67949_p2 & or_ln41_796_fu_67970_p2);

assign and_ln41_922_fu_65953_p2 = (tmp_1298_fu_65921_p3 & or_ln41_798_fu_65947_p2);

assign and_ln41_923_fu_68014_p2 = (xor_ln41_1070_fu_67988_p2 & or_ln41_799_fu_68009_p2);

assign and_ln41_924_fu_66038_p2 = (tmp_1302_fu_66006_p3 & or_ln41_801_fu_66032_p2);

assign and_ln41_925_fu_68053_p2 = (xor_ln41_1073_fu_68027_p2 & or_ln41_802_fu_68048_p2);

assign and_ln41_926_fu_66123_p2 = (tmp_1306_fu_66091_p3 & or_ln41_804_fu_66117_p2);

assign and_ln41_927_fu_68092_p2 = (xor_ln41_1076_fu_68066_p2 & or_ln41_805_fu_68087_p2);

assign and_ln41_928_fu_66208_p2 = (tmp_1310_fu_66176_p3 & or_ln41_807_fu_66202_p2);

assign and_ln41_929_fu_68131_p2 = (xor_ln41_1079_fu_68105_p2 & or_ln41_808_fu_68126_p2);

assign and_ln41_930_fu_66293_p2 = (tmp_1314_fu_66261_p3 & or_ln41_810_fu_66287_p2);

assign and_ln41_931_fu_68170_p2 = (xor_ln41_1082_fu_68144_p2 & or_ln41_811_fu_68165_p2);

assign and_ln41_932_fu_66378_p2 = (tmp_1318_fu_66346_p3 & or_ln41_813_fu_66372_p2);

assign and_ln41_933_fu_68209_p2 = (xor_ln41_1085_fu_68183_p2 & or_ln41_814_fu_68204_p2);

assign and_ln41_934_fu_68306_p2 = (tmp_1325_fu_68274_p3 & or_ln41_816_fu_68300_p2);

assign and_ln41_935_fu_68360_p2 = (xor_ln41_1088_fu_68330_p2 & or_ln41_817_fu_68354_p2);

assign and_ln41_936_fu_66473_p2 = (tmp_1329_fu_66441_p3 & or_ln41_819_fu_66467_p2);

assign and_ln41_937_fu_68400_p2 = (xor_ln41_1091_fu_68374_p2 & or_ln41_820_fu_68395_p2);

assign and_ln41_938_fu_66558_p2 = (tmp_1333_fu_66526_p3 & or_ln41_822_fu_66552_p2);

assign and_ln41_939_fu_68439_p2 = (xor_ln41_1094_fu_68413_p2 & or_ln41_823_fu_68434_p2);

assign and_ln41_940_fu_66643_p2 = (tmp_1337_fu_66611_p3 & or_ln41_825_fu_66637_p2);

assign and_ln41_941_fu_68478_p2 = (xor_ln41_1097_fu_68452_p2 & or_ln41_826_fu_68473_p2);

assign and_ln41_942_fu_66728_p2 = (tmp_1341_fu_66696_p3 & or_ln41_828_fu_66722_p2);

assign and_ln41_943_fu_68517_p2 = (xor_ln41_1100_fu_68491_p2 & or_ln41_829_fu_68512_p2);

assign and_ln41_944_fu_66813_p2 = (tmp_1345_fu_66781_p3 & or_ln41_831_fu_66807_p2);

assign and_ln41_945_fu_68556_p2 = (xor_ln41_1103_fu_68530_p2 & or_ln41_832_fu_68551_p2);

assign and_ln41_946_fu_66898_p2 = (tmp_1349_fu_66866_p3 & or_ln41_834_fu_66892_p2);

assign and_ln41_947_fu_68595_p2 = (xor_ln41_1106_fu_68569_p2 & or_ln41_835_fu_68590_p2);

assign and_ln41_948_fu_66983_p2 = (tmp_1353_fu_66951_p3 & or_ln41_837_fu_66977_p2);

assign and_ln41_949_fu_68634_p2 = (xor_ln41_1109_fu_68608_p2 & or_ln41_838_fu_68629_p2);

assign and_ln41_950_fu_67068_p2 = (tmp_1357_fu_67036_p3 & or_ln41_840_fu_67062_p2);

assign and_ln41_951_fu_68673_p2 = (xor_ln41_1112_fu_68647_p2 & or_ln41_841_fu_68668_p2);

assign and_ln41_952_fu_67153_p2 = (tmp_1361_fu_67121_p3 & or_ln41_843_fu_67147_p2);

assign and_ln41_953_fu_68712_p2 = (xor_ln41_1115_fu_68686_p2 & or_ln41_844_fu_68707_p2);

assign and_ln41_954_fu_67238_p2 = (tmp_1365_fu_67206_p3 & or_ln41_846_fu_67232_p2);

assign and_ln41_955_fu_68751_p2 = (xor_ln41_1118_fu_68725_p2 & or_ln41_847_fu_68746_p2);

assign and_ln41_956_fu_67323_p2 = (tmp_1369_fu_67291_p3 & or_ln41_849_fu_67317_p2);

assign and_ln41_957_fu_68790_p2 = (xor_ln41_1121_fu_68764_p2 & or_ln41_850_fu_68785_p2);

assign and_ln41_958_fu_67408_p2 = (tmp_1373_fu_67376_p3 & or_ln41_852_fu_67402_p2);

assign and_ln41_959_fu_68829_p2 = (xor_ln41_1124_fu_68803_p2 & or_ln41_853_fu_68824_p2);

assign and_ln41_960_fu_67493_p2 = (tmp_1377_fu_67461_p3 & or_ln41_855_fu_67487_p2);

assign and_ln41_961_fu_68868_p2 = (xor_ln41_1127_fu_68842_p2 & or_ln41_856_fu_68863_p2);

assign and_ln41_fu_64929_p2 = (tmp_1250_fu_64897_p3 & or_ln41_fu_64923_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (layer12_out_empty_n == 1'b0) | (ap_start_int == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = (layer13_out_full_n == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = internal_ap_ready;

assign i_fu_68950_p2 = (i_021_fu_324 + 8'd1);

assign icmp_ln25_fu_68956_p2 = ((i_021_fu_324 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln41_379_fu_64998_p2 = ((trunc_ln41_313_fu_64994_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_380_fu_65083_p2 = ((trunc_ln41_314_fu_65079_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_381_fu_65168_p2 = ((trunc_ln41_315_fu_65164_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_382_fu_65253_p2 = ((trunc_ln41_316_fu_65249_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_383_fu_65338_p2 = ((trunc_ln41_317_fu_65334_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_384_fu_65423_p2 = ((trunc_ln41_318_fu_65419_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_385_fu_65508_p2 = ((trunc_ln41_319_fu_65504_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_386_fu_65593_p2 = ((trunc_ln41_320_fu_65589_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_387_fu_65678_p2 = ((trunc_ln41_321_fu_65674_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_388_fu_65763_p2 = ((trunc_ln41_322_fu_65759_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_389_fu_65848_p2 = ((trunc_ln41_323_fu_65844_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_390_fu_65933_p2 = ((trunc_ln41_324_fu_65929_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_391_fu_66018_p2 = ((trunc_ln41_325_fu_66014_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_392_fu_66103_p2 = ((trunc_ln41_326_fu_66099_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_393_fu_66188_p2 = ((trunc_ln41_327_fu_66184_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_394_fu_66273_p2 = ((trunc_ln41_328_fu_66269_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_395_fu_66358_p2 = ((trunc_ln41_329_fu_66354_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_396_fu_68286_p2 = ((trunc_ln41_330_fu_68282_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_397_fu_66453_p2 = ((trunc_ln41_331_fu_66449_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_398_fu_66538_p2 = ((trunc_ln41_332_fu_66534_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_399_fu_66623_p2 = ((trunc_ln41_333_fu_66619_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_400_fu_66708_p2 = ((trunc_ln41_334_fu_66704_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_401_fu_66793_p2 = ((trunc_ln41_335_fu_66789_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_402_fu_66878_p2 = ((trunc_ln41_336_fu_66874_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_403_fu_66963_p2 = ((trunc_ln41_337_fu_66959_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_404_fu_67048_p2 = ((trunc_ln41_338_fu_67044_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_405_fu_67133_p2 = ((trunc_ln41_339_fu_67129_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_406_fu_67218_p2 = ((trunc_ln41_340_fu_67214_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_407_fu_67303_p2 = ((trunc_ln41_341_fu_67299_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_408_fu_67388_p2 = ((trunc_ln41_342_fu_67384_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_409_fu_67473_p2 = ((trunc_ln41_343_fu_67469_p1 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_64909_p2 = ((trunc_ln41_fu_64905_p1 != 9'd0) ? 1'b1 : 1'b0);

assign layer13_out_din = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{select_ln41_547_fu_68874_p3}, {select_ln41_546_fu_68835_p3}}, {select_ln41_545_fu_68796_p3}}, {select_ln41_544_fu_68757_p3}}, {select_ln41_543_fu_68718_p3}}, {select_ln41_542_fu_68679_p3}}, {select_ln41_541_fu_68640_p3}}, {select_ln41_540_fu_68601_p3}}, {select_ln41_539_fu_68562_p3}}, {select_ln41_538_fu_68523_p3}}, {select_ln41_537_fu_68484_p3}}, {select_ln41_536_fu_68445_p3}}, {select_ln41_535_fu_68406_p3}}, {select_ln41_534_fu_68366_p3}}, {select_ln41_533_fu_68215_p3}}, {select_ln41_532_fu_68176_p3}}, {select_ln41_531_fu_68137_p3}}, {select_ln41_530_fu_68098_p3}}, {select_ln41_529_fu_68059_p3}}, {select_ln41_528_fu_68020_p3}}, {select_ln41_527_fu_67981_p3}}, {select_ln41_526_fu_67942_p3}}, {select_ln41_525_fu_67903_p3}}, {select_ln41_524_fu_67864_p3}}, {select_ln41_523_fu_67825_p3}}, {select_ln41_522_fu_67786_p3}}, {select_ln41_521_fu_67747_p3}}, {select_ln41_520_fu_67708_p3}}, {select_ln41_519_fu_67669_p3}}, {select_ln41_518_fu_67630_p3}}, {select_ln41_517_fu_67591_p3}}, {select_ln41_fu_67552_p3}};

assign mul_ln42_240_fu_632_p1 = 31'd499;

assign mul_ln42_241_fu_720_p1 = 32'd540;

assign mul_ln42_242_fu_370_p1 = 32'd687;

assign mul_ln42_243_fu_784_p1 = 32'd725;

assign mul_ln42_244_fu_793_p1 = 32'd523;

assign mul_ln42_245_fu_605_p1 = 32'd752;

assign mul_ln42_246_fu_749_p1 = 32'd685;

assign mul_ln42_247_fu_345_p1 = 32'd617;

assign mul_ln42_248_fu_611_p1 = 32'd603;

assign mul_ln42_249_fu_369_p1 = 32'd613;

assign mul_ln42_250_fu_756_p1 = 32'd637;

assign mul_ln42_251_fu_846_p1 = 32'd586;

assign mul_ln42_252_fu_442_p1 = 32'd655;

assign mul_ln42_253_fu_613_p1 = 32'd641;

assign mul_ln42_254_fu_425_p1 = 32'd587;

assign mul_ln42_255_fu_438_p1 = 32'd662;

assign mul_ln42_256_fu_835_p1 = 32'd590;

assign mul_ln42_257_fu_431_p1 = 32'd560;

assign mul_ln42_258_fu_603_p1 = 32'd724;

assign mul_ln42_259_fu_618_p1 = 32'd641;

assign mul_ln42_260_fu_666_p1 = 32'd569;

assign mul_ln42_261_fu_343_p1 = 32'd672;

assign mul_ln42_262_fu_636_p1 = 32'd656;

assign mul_ln42_263_fu_579_p1 = 32'd582;

assign mul_ln42_264_fu_673_p1 = 32'd579;

assign mul_ln42_265_fu_655_p1 = 32'd608;

assign mul_ln42_266_fu_624_p1 = 32'd658;

assign mul_ln42_267_fu_376_p1 = 32'd658;

assign mul_ln42_268_fu_342_p1 = 32'd635;

assign mul_ln42_269_fu_716_p1 = 32'd524;

assign mul_ln42_fu_447_p1 = 32'd643;

assign or_ln41_763_fu_67541_p2 = (xor_ln41_1036_fu_67535_p2 | tmp_1252_reg_68985);

assign or_ln41_765_fu_65012_p2 = (tmp_1255_fu_65004_p3 | icmp_ln41_379_fu_64998_p2);

assign or_ln41_766_fu_67580_p2 = (xor_ln41_1039_fu_67574_p2 | tmp_1256_reg_69002);

assign or_ln41_768_fu_65097_p2 = (tmp_1259_fu_65089_p3 | icmp_ln41_380_fu_65083_p2);

assign or_ln41_769_fu_67619_p2 = (xor_ln41_1042_fu_67613_p2 | tmp_1260_reg_69019);

assign or_ln41_771_fu_65182_p2 = (tmp_1263_fu_65174_p3 | icmp_ln41_381_fu_65168_p2);

assign or_ln41_772_fu_67658_p2 = (xor_ln41_1045_fu_67652_p2 | tmp_1264_reg_69036);

assign or_ln41_773_fu_67525_p2 = (xor_ln41_fu_67520_p2 | tmp_1252_reg_68985);

assign or_ln41_774_fu_65267_p2 = (tmp_1267_fu_65259_p3 | icmp_ln41_382_fu_65253_p2);

assign or_ln41_775_fu_67697_p2 = (xor_ln41_1048_fu_67691_p2 | tmp_1268_reg_69053);

assign or_ln41_776_fu_67564_p2 = (xor_ln41_1037_fu_67559_p2 | tmp_1256_reg_69002);

assign or_ln41_777_fu_65352_p2 = (tmp_1271_fu_65344_p3 | icmp_ln41_383_fu_65338_p2);

assign or_ln41_778_fu_67736_p2 = (xor_ln41_1051_fu_67730_p2 | tmp_1272_reg_69070);

assign or_ln41_779_fu_67603_p2 = (xor_ln41_1040_fu_67598_p2 | tmp_1260_reg_69019);

assign or_ln41_780_fu_65437_p2 = (tmp_1275_fu_65429_p3 | icmp_ln41_384_fu_65423_p2);

assign or_ln41_781_fu_67775_p2 = (xor_ln41_1054_fu_67769_p2 | tmp_1276_reg_69087);

assign or_ln41_782_fu_67642_p2 = (xor_ln41_1043_fu_67637_p2 | tmp_1264_reg_69036);

assign or_ln41_783_fu_65522_p2 = (tmp_1279_fu_65514_p3 | icmp_ln41_385_fu_65508_p2);

assign or_ln41_784_fu_67814_p2 = (xor_ln41_1057_fu_67808_p2 | tmp_1280_reg_69104);

assign or_ln41_785_fu_67681_p2 = (xor_ln41_1046_fu_67676_p2 | tmp_1268_reg_69053);

assign or_ln41_786_fu_65607_p2 = (tmp_1283_fu_65599_p3 | icmp_ln41_386_fu_65593_p2);

assign or_ln41_787_fu_67853_p2 = (xor_ln41_1060_fu_67847_p2 | tmp_1284_reg_69121);

assign or_ln41_788_fu_67720_p2 = (xor_ln41_1049_fu_67715_p2 | tmp_1272_reg_69070);

assign or_ln41_789_fu_65692_p2 = (tmp_1287_fu_65684_p3 | icmp_ln41_387_fu_65678_p2);

assign or_ln41_790_fu_67892_p2 = (xor_ln41_1063_fu_67886_p2 | tmp_1288_reg_69138);

assign or_ln41_791_fu_67759_p2 = (xor_ln41_1052_fu_67754_p2 | tmp_1276_reg_69087);

assign or_ln41_792_fu_65777_p2 = (tmp_1291_fu_65769_p3 | icmp_ln41_388_fu_65763_p2);

assign or_ln41_793_fu_67931_p2 = (xor_ln41_1066_fu_67925_p2 | tmp_1292_reg_69155);

assign or_ln41_794_fu_67798_p2 = (xor_ln41_1055_fu_67793_p2 | tmp_1280_reg_69104);

assign or_ln41_795_fu_65862_p2 = (tmp_1295_fu_65854_p3 | icmp_ln41_389_fu_65848_p2);

assign or_ln41_796_fu_67970_p2 = (xor_ln41_1069_fu_67964_p2 | tmp_1296_reg_69172);

assign or_ln41_797_fu_67837_p2 = (xor_ln41_1058_fu_67832_p2 | tmp_1284_reg_69121);

assign or_ln41_798_fu_65947_p2 = (tmp_1299_fu_65939_p3 | icmp_ln41_390_fu_65933_p2);

assign or_ln41_799_fu_68009_p2 = (xor_ln41_1072_fu_68003_p2 | tmp_1300_reg_69189);

assign or_ln41_800_fu_67876_p2 = (xor_ln41_1061_fu_67871_p2 | tmp_1288_reg_69138);

assign or_ln41_801_fu_66032_p2 = (tmp_1303_fu_66024_p3 | icmp_ln41_391_fu_66018_p2);

assign or_ln41_802_fu_68048_p2 = (xor_ln41_1075_fu_68042_p2 | tmp_1304_reg_69206);

assign or_ln41_803_fu_67915_p2 = (xor_ln41_1064_fu_67910_p2 | tmp_1292_reg_69155);

assign or_ln41_804_fu_66117_p2 = (tmp_1307_fu_66109_p3 | icmp_ln41_392_fu_66103_p2);

assign or_ln41_805_fu_68087_p2 = (xor_ln41_1078_fu_68081_p2 | tmp_1308_reg_69223);

assign or_ln41_806_fu_67954_p2 = (xor_ln41_1067_fu_67949_p2 | tmp_1296_reg_69172);

assign or_ln41_807_fu_66202_p2 = (tmp_1311_fu_66194_p3 | icmp_ln41_393_fu_66188_p2);

assign or_ln41_808_fu_68126_p2 = (xor_ln41_1081_fu_68120_p2 | tmp_1312_reg_69240);

assign or_ln41_809_fu_67993_p2 = (xor_ln41_1070_fu_67988_p2 | tmp_1300_reg_69189);

assign or_ln41_810_fu_66287_p2 = (tmp_1315_fu_66279_p3 | icmp_ln41_394_fu_66273_p2);

assign or_ln41_811_fu_68165_p2 = (xor_ln41_1084_fu_68159_p2 | tmp_1316_reg_69257);

assign or_ln41_812_fu_68032_p2 = (xor_ln41_1073_fu_68027_p2 | tmp_1304_reg_69206);

assign or_ln41_813_fu_66372_p2 = (tmp_1319_fu_66364_p3 | icmp_ln41_395_fu_66358_p2);

assign or_ln41_814_fu_68204_p2 = (xor_ln41_1087_fu_68198_p2 | tmp_1320_reg_69274);

assign or_ln41_815_fu_68071_p2 = (xor_ln41_1076_fu_68066_p2 | tmp_1308_reg_69223);

assign or_ln41_816_fu_68300_p2 = (tmp_1326_fu_68292_p3 | icmp_ln41_396_fu_68286_p2);

assign or_ln41_817_fu_68354_p2 = (xor_ln41_1090_fu_68348_p2 | tmp_1327_fu_68322_p3);

assign or_ln41_818_fu_68110_p2 = (xor_ln41_1079_fu_68105_p2 | tmp_1312_reg_69240);

assign or_ln41_819_fu_66467_p2 = (tmp_1330_fu_66459_p3 | icmp_ln41_397_fu_66453_p2);

assign or_ln41_820_fu_68395_p2 = (xor_ln41_1093_fu_68389_p2 | tmp_1331_reg_69297);

assign or_ln41_821_fu_68149_p2 = (xor_ln41_1082_fu_68144_p2 | tmp_1316_reg_69257);

assign or_ln41_822_fu_66552_p2 = (tmp_1334_fu_66544_p3 | icmp_ln41_398_fu_66538_p2);

assign or_ln41_823_fu_68434_p2 = (xor_ln41_1096_fu_68428_p2 | tmp_1335_reg_69314);

assign or_ln41_824_fu_68188_p2 = (xor_ln41_1085_fu_68183_p2 | tmp_1320_reg_69274);

assign or_ln41_825_fu_66637_p2 = (tmp_1338_fu_66629_p3 | icmp_ln41_399_fu_66623_p2);

assign or_ln41_826_fu_68473_p2 = (xor_ln41_1099_fu_68467_p2 | tmp_1339_reg_69331);

assign or_ln41_827_fu_68336_p2 = (xor_ln41_1088_fu_68330_p2 | tmp_1327_fu_68322_p3);

assign or_ln41_828_fu_66722_p2 = (tmp_1342_fu_66714_p3 | icmp_ln41_400_fu_66708_p2);

assign or_ln41_829_fu_68512_p2 = (xor_ln41_1102_fu_68506_p2 | tmp_1343_reg_69348);

assign or_ln41_830_fu_68379_p2 = (xor_ln41_1091_fu_68374_p2 | tmp_1331_reg_69297);

assign or_ln41_831_fu_66807_p2 = (tmp_1346_fu_66799_p3 | icmp_ln41_401_fu_66793_p2);

assign or_ln41_832_fu_68551_p2 = (xor_ln41_1105_fu_68545_p2 | tmp_1347_reg_69365);

assign or_ln41_833_fu_68418_p2 = (xor_ln41_1094_fu_68413_p2 | tmp_1335_reg_69314);

assign or_ln41_834_fu_66892_p2 = (tmp_1350_fu_66884_p3 | icmp_ln41_402_fu_66878_p2);

assign or_ln41_835_fu_68590_p2 = (xor_ln41_1108_fu_68584_p2 | tmp_1351_reg_69382);

assign or_ln41_836_fu_68457_p2 = (xor_ln41_1097_fu_68452_p2 | tmp_1339_reg_69331);

assign or_ln41_837_fu_66977_p2 = (tmp_1354_fu_66969_p3 | icmp_ln41_403_fu_66963_p2);

assign or_ln41_838_fu_68629_p2 = (xor_ln41_1111_fu_68623_p2 | tmp_1355_reg_69399);

assign or_ln41_839_fu_68496_p2 = (xor_ln41_1100_fu_68491_p2 | tmp_1343_reg_69348);

assign or_ln41_840_fu_67062_p2 = (tmp_1358_fu_67054_p3 | icmp_ln41_404_fu_67048_p2);

assign or_ln41_841_fu_68668_p2 = (xor_ln41_1114_fu_68662_p2 | tmp_1359_reg_69416);

assign or_ln41_842_fu_68535_p2 = (xor_ln41_1103_fu_68530_p2 | tmp_1347_reg_69365);

assign or_ln41_843_fu_67147_p2 = (tmp_1362_fu_67139_p3 | icmp_ln41_405_fu_67133_p2);

assign or_ln41_844_fu_68707_p2 = (xor_ln41_1117_fu_68701_p2 | tmp_1363_reg_69433);

assign or_ln41_845_fu_68574_p2 = (xor_ln41_1106_fu_68569_p2 | tmp_1351_reg_69382);

assign or_ln41_846_fu_67232_p2 = (tmp_1366_fu_67224_p3 | icmp_ln41_406_fu_67218_p2);

assign or_ln41_847_fu_68746_p2 = (xor_ln41_1120_fu_68740_p2 | tmp_1367_reg_69450);

assign or_ln41_848_fu_68613_p2 = (xor_ln41_1109_fu_68608_p2 | tmp_1355_reg_69399);

assign or_ln41_849_fu_67317_p2 = (tmp_1370_fu_67309_p3 | icmp_ln41_407_fu_67303_p2);

assign or_ln41_850_fu_68785_p2 = (xor_ln41_1123_fu_68779_p2 | tmp_1371_reg_69467);

assign or_ln41_851_fu_68652_p2 = (xor_ln41_1112_fu_68647_p2 | tmp_1359_reg_69416);

assign or_ln41_852_fu_67402_p2 = (tmp_1374_fu_67394_p3 | icmp_ln41_408_fu_67388_p2);

assign or_ln41_853_fu_68824_p2 = (xor_ln41_1126_fu_68818_p2 | tmp_1375_reg_69484);

assign or_ln41_854_fu_68691_p2 = (xor_ln41_1115_fu_68686_p2 | tmp_1363_reg_69433);

assign or_ln41_855_fu_67487_p2 = (tmp_1378_fu_67479_p3 | icmp_ln41_409_fu_67473_p2);

assign or_ln41_856_fu_68863_p2 = (xor_ln41_1129_fu_68857_p2 | tmp_1379_reg_69501);

assign or_ln41_857_fu_68730_p2 = (xor_ln41_1118_fu_68725_p2 | tmp_1367_reg_69450);

assign or_ln41_858_fu_68769_p2 = (xor_ln41_1121_fu_68764_p2 | tmp_1371_reg_69467);

assign or_ln41_859_fu_68808_p2 = (xor_ln41_1124_fu_68803_p2 | tmp_1375_reg_69484);

assign or_ln41_860_fu_68847_p2 = (xor_ln41_1127_fu_68842_p2 | tmp_1379_reg_69501);

assign or_ln41_fu_64923_p2 = (tmp_1251_fu_64915_p3 | icmp_ln41_fu_64909_p2);

assign select_ln41_517_fu_67591_p3 = ((and_ln41_901_fu_67585_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_251_reg_68997);

assign select_ln41_518_fu_67630_p3 = ((and_ln41_903_fu_67624_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_252_reg_69014);

assign select_ln41_519_fu_67669_p3 = ((and_ln41_905_fu_67663_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_253_reg_69031);

assign select_ln41_520_fu_67708_p3 = ((and_ln41_907_fu_67702_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_254_reg_69048);

assign select_ln41_521_fu_67747_p3 = ((and_ln41_909_fu_67741_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_255_reg_69065);

assign select_ln41_522_fu_67786_p3 = ((and_ln41_911_fu_67780_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_256_reg_69082);

assign select_ln41_523_fu_67825_p3 = ((and_ln41_913_fu_67819_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_257_reg_69099);

assign select_ln41_524_fu_67864_p3 = ((and_ln41_915_fu_67858_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_258_reg_69116);

assign select_ln41_525_fu_67903_p3 = ((and_ln41_917_fu_67897_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_259_reg_69133);

assign select_ln41_526_fu_67942_p3 = ((and_ln41_919_fu_67936_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_260_reg_69150);

assign select_ln41_527_fu_67981_p3 = ((and_ln41_921_fu_67975_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_261_reg_69167);

assign select_ln41_528_fu_68020_p3 = ((and_ln41_923_fu_68014_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_262_reg_69184);

assign select_ln41_529_fu_68059_p3 = ((and_ln41_925_fu_68053_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_263_reg_69201);

assign select_ln41_530_fu_68098_p3 = ((and_ln41_927_fu_68092_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_264_reg_69218);

assign select_ln41_531_fu_68137_p3 = ((and_ln41_929_fu_68131_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_265_reg_69235);

assign select_ln41_532_fu_68176_p3 = ((and_ln41_931_fu_68170_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_266_reg_69252);

assign select_ln41_533_fu_68215_p3 = ((and_ln41_933_fu_68209_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_267_reg_69269);

assign select_ln41_534_fu_68366_p3 = ((and_ln41_935_fu_68360_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_268_fu_68316_p2);

assign select_ln41_535_fu_68406_p3 = ((and_ln41_937_fu_68400_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_269_reg_69292);

assign select_ln41_536_fu_68445_p3 = ((and_ln41_939_fu_68439_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_270_reg_69309);

assign select_ln41_537_fu_68484_p3 = ((and_ln41_941_fu_68478_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_271_reg_69326);

assign select_ln41_538_fu_68523_p3 = ((and_ln41_943_fu_68517_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_272_reg_69343);

assign select_ln41_539_fu_68562_p3 = ((and_ln41_945_fu_68556_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_273_reg_69360);

assign select_ln41_540_fu_68601_p3 = ((and_ln41_947_fu_68595_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_274_reg_69377);

assign select_ln41_541_fu_68640_p3 = ((and_ln41_949_fu_68634_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_275_reg_69394);

assign select_ln41_542_fu_68679_p3 = ((and_ln41_951_fu_68673_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_276_reg_69411);

assign select_ln41_543_fu_68718_p3 = ((and_ln41_953_fu_68712_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_277_reg_69428);

assign select_ln41_544_fu_68757_p3 = ((and_ln41_955_fu_68751_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_278_reg_69445);

assign select_ln41_545_fu_68796_p3 = ((and_ln41_957_fu_68790_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_279_reg_69462);

assign select_ln41_546_fu_68835_p3 = ((and_ln41_959_fu_68829_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_280_reg_69479);

assign select_ln41_547_fu_68874_p3 = ((and_ln41_961_fu_68868_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_281_reg_69496);

assign select_ln41_fu_67552_p3 = ((and_ln41_899_fu_67546_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln41_reg_68980);

assign sext_ln41_fu_64982_p1 = $signed(trunc_ln41_s_fu_64972_p4);

assign sext_ln42_269_fu_68229_p1 = $signed(tmp_1322_fu_68222_p3);

assign sext_ln42_283_fu_68240_p1 = $signed(tmp_1323_fu_68233_p3);

assign start_out = real_start;

assign tmp_1250_fu_64897_p3 = add_ln42_fu_64873_p2[32'd9];

assign tmp_1251_fu_64915_p3 = add_ln42_fu_64873_p2[32'd10];

assign tmp_1254_fu_64986_p3 = add_ln42_252_fu_64958_p2[32'd9];

assign tmp_1255_fu_65004_p3 = add_ln42_252_fu_64958_p2[32'd10];

assign tmp_1258_fu_65071_p3 = add_ln42_253_fu_65047_p2[32'd9];

assign tmp_1259_fu_65089_p3 = add_ln42_253_fu_65047_p2[32'd10];

assign tmp_1262_fu_65156_p3 = add_ln42_254_fu_65132_p2[32'd9];

assign tmp_1263_fu_65174_p3 = add_ln42_254_fu_65132_p2[32'd10];

assign tmp_1266_fu_65241_p3 = add_ln42_255_fu_65217_p2[32'd9];

assign tmp_1267_fu_65259_p3 = add_ln42_255_fu_65217_p2[32'd10];

assign tmp_1270_fu_65326_p3 = add_ln42_256_fu_65302_p2[32'd9];

assign tmp_1271_fu_65344_p3 = add_ln42_256_fu_65302_p2[32'd10];

assign tmp_1274_fu_65411_p3 = add_ln42_257_fu_65387_p2[32'd9];

assign tmp_1275_fu_65429_p3 = add_ln42_257_fu_65387_p2[32'd10];

assign tmp_1278_fu_65496_p3 = add_ln42_258_fu_65472_p2[32'd9];

assign tmp_1279_fu_65514_p3 = add_ln42_258_fu_65472_p2[32'd10];

assign tmp_1282_fu_65581_p3 = add_ln42_259_fu_65557_p2[32'd9];

assign tmp_1283_fu_65599_p3 = add_ln42_259_fu_65557_p2[32'd10];

assign tmp_1286_fu_65666_p3 = add_ln42_260_fu_65642_p2[32'd9];

assign tmp_1287_fu_65684_p3 = add_ln42_260_fu_65642_p2[32'd10];

assign tmp_1290_fu_65751_p3 = add_ln42_261_fu_65727_p2[32'd9];

assign tmp_1291_fu_65769_p3 = add_ln42_261_fu_65727_p2[32'd10];

assign tmp_1294_fu_65836_p3 = add_ln42_262_fu_65812_p2[32'd9];

assign tmp_1295_fu_65854_p3 = add_ln42_262_fu_65812_p2[32'd10];

assign tmp_1298_fu_65921_p3 = add_ln42_263_fu_65897_p2[32'd9];

assign tmp_1299_fu_65939_p3 = add_ln42_263_fu_65897_p2[32'd10];

assign tmp_1302_fu_66006_p3 = add_ln42_264_fu_65982_p2[32'd9];

assign tmp_1303_fu_66024_p3 = add_ln42_264_fu_65982_p2[32'd10];

assign tmp_1306_fu_66091_p3 = add_ln42_265_fu_66067_p2[32'd9];

assign tmp_1307_fu_66109_p3 = add_ln42_265_fu_66067_p2[32'd10];

assign tmp_1310_fu_66176_p3 = add_ln42_266_fu_66152_p2[32'd9];

assign tmp_1311_fu_66194_p3 = add_ln42_266_fu_66152_p2[32'd10];

assign tmp_1314_fu_66261_p3 = add_ln42_267_fu_66237_p2[32'd9];

assign tmp_1315_fu_66279_p3 = add_ln42_267_fu_66237_p2[32'd10];

assign tmp_1318_fu_66346_p3 = add_ln42_268_fu_66322_p2[32'd9];

assign tmp_1319_fu_66364_p3 = add_ln42_268_fu_66322_p2[32'd10];

assign tmp_1322_fu_68222_p3 = {{tmp_1321_reg_69280}, {9'd0}};

assign tmp_1323_fu_68233_p3 = {{tmp_1321_reg_69280}, {5'd0}};

assign tmp_1324_fu_68256_p3 = add_ln42_269_fu_68250_p2[32'd31];

assign tmp_1325_fu_68274_p3 = add_ln42_269_fu_68250_p2[32'd9];

assign tmp_1326_fu_68292_p3 = add_ln42_269_fu_68250_p2[32'd10];

assign tmp_1327_fu_68322_p3 = add_ln41_268_fu_68316_p2[32'd21];

assign tmp_1329_fu_66441_p3 = add_ln42_270_fu_66417_p2[32'd9];

assign tmp_1330_fu_66459_p3 = add_ln42_270_fu_66417_p2[32'd10];

assign tmp_1333_fu_66526_p3 = add_ln42_271_fu_66502_p2[32'd9];

assign tmp_1334_fu_66544_p3 = add_ln42_271_fu_66502_p2[32'd10];

assign tmp_1337_fu_66611_p3 = add_ln42_272_fu_66587_p2[32'd9];

assign tmp_1338_fu_66629_p3 = add_ln42_272_fu_66587_p2[32'd10];

assign tmp_1341_fu_66696_p3 = add_ln42_273_fu_66672_p2[32'd9];

assign tmp_1342_fu_66714_p3 = add_ln42_273_fu_66672_p2[32'd10];

assign tmp_1345_fu_66781_p3 = add_ln42_274_fu_66757_p2[32'd9];

assign tmp_1346_fu_66799_p3 = add_ln42_274_fu_66757_p2[32'd10];

assign tmp_1349_fu_66866_p3 = add_ln42_275_fu_66842_p2[32'd9];

assign tmp_1350_fu_66884_p3 = add_ln42_275_fu_66842_p2[32'd10];

assign tmp_1353_fu_66951_p3 = add_ln42_276_fu_66927_p2[32'd9];

assign tmp_1354_fu_66969_p3 = add_ln42_276_fu_66927_p2[32'd10];

assign tmp_1357_fu_67036_p3 = add_ln42_277_fu_67012_p2[32'd9];

assign tmp_1358_fu_67054_p3 = add_ln42_277_fu_67012_p2[32'd10];

assign tmp_1361_fu_67121_p3 = add_ln42_278_fu_67097_p2[32'd9];

assign tmp_1362_fu_67139_p3 = add_ln42_278_fu_67097_p2[32'd10];

assign tmp_1365_fu_67206_p3 = add_ln42_279_fu_67182_p2[32'd9];

assign tmp_1366_fu_67224_p3 = add_ln42_279_fu_67182_p2[32'd10];

assign tmp_1369_fu_67291_p3 = add_ln42_280_fu_67267_p2[32'd9];

assign tmp_1370_fu_67309_p3 = add_ln42_280_fu_67267_p2[32'd10];

assign tmp_1373_fu_67376_p3 = add_ln42_281_fu_67352_p2[32'd9];

assign tmp_1374_fu_67394_p3 = add_ln42_281_fu_67352_p2[32'd10];

assign tmp_1377_fu_67461_p3 = add_ln42_282_fu_67437_p2[32'd9];

assign tmp_1378_fu_67479_p3 = add_ln42_282_fu_67437_p2[32'd10];

assign trunc_ln41_247_fu_65061_p4 = {{add_ln42_253_fu_65047_p2[31:10]}};

assign trunc_ln41_248_fu_65146_p4 = {{add_ln42_254_fu_65132_p2[31:10]}};

assign trunc_ln41_249_fu_65231_p4 = {{add_ln42_255_fu_65217_p2[31:10]}};

assign trunc_ln41_250_fu_65316_p4 = {{add_ln42_256_fu_65302_p2[31:10]}};

assign trunc_ln41_251_fu_65401_p4 = {{add_ln42_257_fu_65387_p2[31:10]}};

assign trunc_ln41_252_fu_65486_p4 = {{add_ln42_258_fu_65472_p2[31:10]}};

assign trunc_ln41_253_fu_65571_p4 = {{add_ln42_259_fu_65557_p2[31:10]}};

assign trunc_ln41_254_fu_65656_p4 = {{add_ln42_260_fu_65642_p2[31:10]}};

assign trunc_ln41_255_fu_65741_p4 = {{add_ln42_261_fu_65727_p2[31:10]}};

assign trunc_ln41_256_fu_65826_p4 = {{add_ln42_262_fu_65812_p2[31:10]}};

assign trunc_ln41_257_fu_65911_p4 = {{add_ln42_263_fu_65897_p2[31:10]}};

assign trunc_ln41_258_fu_65996_p4 = {{add_ln42_264_fu_65982_p2[31:10]}};

assign trunc_ln41_259_fu_66081_p4 = {{add_ln42_265_fu_66067_p2[31:10]}};

assign trunc_ln41_260_fu_66166_p4 = {{add_ln42_266_fu_66152_p2[31:10]}};

assign trunc_ln41_261_fu_66251_p4 = {{add_ln42_267_fu_66237_p2[31:10]}};

assign trunc_ln41_262_fu_66336_p4 = {{add_ln42_268_fu_66322_p2[31:10]}};

assign trunc_ln41_263_fu_68264_p4 = {{add_ln42_269_fu_68250_p2[31:10]}};

assign trunc_ln41_264_fu_66431_p4 = {{add_ln42_270_fu_66417_p2[31:10]}};

assign trunc_ln41_265_fu_66516_p4 = {{add_ln42_271_fu_66502_p2[31:10]}};

assign trunc_ln41_266_fu_66601_p4 = {{add_ln42_272_fu_66587_p2[31:10]}};

assign trunc_ln41_267_fu_66686_p4 = {{add_ln42_273_fu_66672_p2[31:10]}};

assign trunc_ln41_268_fu_66771_p4 = {{add_ln42_274_fu_66757_p2[31:10]}};

assign trunc_ln41_269_fu_66856_p4 = {{add_ln42_275_fu_66842_p2[31:10]}};

assign trunc_ln41_270_fu_66941_p4 = {{add_ln42_276_fu_66927_p2[31:10]}};

assign trunc_ln41_271_fu_67026_p4 = {{add_ln42_277_fu_67012_p2[31:10]}};

assign trunc_ln41_272_fu_67111_p4 = {{add_ln42_278_fu_67097_p2[31:10]}};

assign trunc_ln41_273_fu_67196_p4 = {{add_ln42_279_fu_67182_p2[31:10]}};

assign trunc_ln41_274_fu_67281_p4 = {{add_ln42_280_fu_67267_p2[31:10]}};

assign trunc_ln41_275_fu_67366_p4 = {{add_ln42_281_fu_67352_p2[31:10]}};

assign trunc_ln41_276_fu_67451_p4 = {{add_ln42_282_fu_67437_p2[31:10]}};

assign trunc_ln41_313_fu_64994_p1 = add_ln42_252_fu_64958_p2[8:0];

assign trunc_ln41_314_fu_65079_p1 = add_ln42_253_fu_65047_p2[8:0];

assign trunc_ln41_315_fu_65164_p1 = add_ln42_254_fu_65132_p2[8:0];

assign trunc_ln41_316_fu_65249_p1 = add_ln42_255_fu_65217_p2[8:0];

assign trunc_ln41_317_fu_65334_p1 = add_ln42_256_fu_65302_p2[8:0];

assign trunc_ln41_318_fu_65419_p1 = add_ln42_257_fu_65387_p2[8:0];

assign trunc_ln41_319_fu_65504_p1 = add_ln42_258_fu_65472_p2[8:0];

assign trunc_ln41_320_fu_65589_p1 = add_ln42_259_fu_65557_p2[8:0];

assign trunc_ln41_321_fu_65674_p1 = add_ln42_260_fu_65642_p2[8:0];

assign trunc_ln41_322_fu_65759_p1 = add_ln42_261_fu_65727_p2[8:0];

assign trunc_ln41_323_fu_65844_p1 = add_ln42_262_fu_65812_p2[8:0];

assign trunc_ln41_324_fu_65929_p1 = add_ln42_263_fu_65897_p2[8:0];

assign trunc_ln41_325_fu_66014_p1 = add_ln42_264_fu_65982_p2[8:0];

assign trunc_ln41_326_fu_66099_p1 = add_ln42_265_fu_66067_p2[8:0];

assign trunc_ln41_327_fu_66184_p1 = add_ln42_266_fu_66152_p2[8:0];

assign trunc_ln41_328_fu_66269_p1 = add_ln42_267_fu_66237_p2[8:0];

assign trunc_ln41_329_fu_66354_p1 = add_ln42_268_fu_66322_p2[8:0];

assign trunc_ln41_330_fu_68282_p1 = add_ln42_269_fu_68250_p2[8:0];

assign trunc_ln41_331_fu_66449_p1 = add_ln42_270_fu_66417_p2[8:0];

assign trunc_ln41_332_fu_66534_p1 = add_ln42_271_fu_66502_p2[8:0];

assign trunc_ln41_333_fu_66619_p1 = add_ln42_272_fu_66587_p2[8:0];

assign trunc_ln41_334_fu_66704_p1 = add_ln42_273_fu_66672_p2[8:0];

assign trunc_ln41_335_fu_66789_p1 = add_ln42_274_fu_66757_p2[8:0];

assign trunc_ln41_336_fu_66874_p1 = add_ln42_275_fu_66842_p2[8:0];

assign trunc_ln41_337_fu_66959_p1 = add_ln42_276_fu_66927_p2[8:0];

assign trunc_ln41_338_fu_67044_p1 = add_ln42_277_fu_67012_p2[8:0];

assign trunc_ln41_339_fu_67129_p1 = add_ln42_278_fu_67097_p2[8:0];

assign trunc_ln41_340_fu_67214_p1 = add_ln42_279_fu_67182_p2[8:0];

assign trunc_ln41_341_fu_67299_p1 = add_ln42_280_fu_67267_p2[8:0];

assign trunc_ln41_342_fu_67384_p1 = add_ln42_281_fu_67352_p2[8:0];

assign trunc_ln41_343_fu_67469_p1 = add_ln42_282_fu_67437_p2[8:0];

assign trunc_ln41_fu_64905_p1 = add_ln42_fu_64873_p2[8:0];

assign trunc_ln41_s_fu_64972_p4 = {{add_ln42_252_fu_64958_p2[30:10]}};

assign trunc_ln_fu_64887_p4 = {{add_ln42_fu_64873_p2[31:10]}};

assign xor_ln41_1035_fu_67530_p2 = (tmp_reg_68974 ^ or_ln41_773_fu_67525_p2);

assign xor_ln41_1036_fu_67535_p2 = (xor_ln41_1035_fu_67530_p2 ^ 1'd1);

assign xor_ln41_1037_fu_67559_p2 = (tmp_1253_reg_68991 ^ 1'd1);

assign xor_ln41_1038_fu_67569_p2 = (tmp_1253_reg_68991 ^ or_ln41_776_fu_67564_p2);

assign xor_ln41_1039_fu_67574_p2 = (xor_ln41_1038_fu_67569_p2 ^ 1'd1);

assign xor_ln41_1040_fu_67598_p2 = (tmp_1257_reg_69008 ^ 1'd1);

assign xor_ln41_1041_fu_67608_p2 = (tmp_1257_reg_69008 ^ or_ln41_779_fu_67603_p2);

assign xor_ln41_1042_fu_67613_p2 = (xor_ln41_1041_fu_67608_p2 ^ 1'd1);

assign xor_ln41_1043_fu_67637_p2 = (tmp_1261_reg_69025 ^ 1'd1);

assign xor_ln41_1044_fu_67647_p2 = (tmp_1261_reg_69025 ^ or_ln41_782_fu_67642_p2);

assign xor_ln41_1045_fu_67652_p2 = (xor_ln41_1044_fu_67647_p2 ^ 1'd1);

assign xor_ln41_1046_fu_67676_p2 = (tmp_1265_reg_69042 ^ 1'd1);

assign xor_ln41_1047_fu_67686_p2 = (tmp_1265_reg_69042 ^ or_ln41_785_fu_67681_p2);

assign xor_ln41_1048_fu_67691_p2 = (xor_ln41_1047_fu_67686_p2 ^ 1'd1);

assign xor_ln41_1049_fu_67715_p2 = (tmp_1269_reg_69059 ^ 1'd1);

assign xor_ln41_1050_fu_67725_p2 = (tmp_1269_reg_69059 ^ or_ln41_788_fu_67720_p2);

assign xor_ln41_1051_fu_67730_p2 = (xor_ln41_1050_fu_67725_p2 ^ 1'd1);

assign xor_ln41_1052_fu_67754_p2 = (tmp_1273_reg_69076 ^ 1'd1);

assign xor_ln41_1053_fu_67764_p2 = (tmp_1273_reg_69076 ^ or_ln41_791_fu_67759_p2);

assign xor_ln41_1054_fu_67769_p2 = (xor_ln41_1053_fu_67764_p2 ^ 1'd1);

assign xor_ln41_1055_fu_67793_p2 = (tmp_1277_reg_69093 ^ 1'd1);

assign xor_ln41_1056_fu_67803_p2 = (tmp_1277_reg_69093 ^ or_ln41_794_fu_67798_p2);

assign xor_ln41_1057_fu_67808_p2 = (xor_ln41_1056_fu_67803_p2 ^ 1'd1);

assign xor_ln41_1058_fu_67832_p2 = (tmp_1281_reg_69110 ^ 1'd1);

assign xor_ln41_1059_fu_67842_p2 = (tmp_1281_reg_69110 ^ or_ln41_797_fu_67837_p2);

assign xor_ln41_1060_fu_67847_p2 = (xor_ln41_1059_fu_67842_p2 ^ 1'd1);

assign xor_ln41_1061_fu_67871_p2 = (tmp_1285_reg_69127 ^ 1'd1);

assign xor_ln41_1062_fu_67881_p2 = (tmp_1285_reg_69127 ^ or_ln41_800_fu_67876_p2);

assign xor_ln41_1063_fu_67886_p2 = (xor_ln41_1062_fu_67881_p2 ^ 1'd1);

assign xor_ln41_1064_fu_67910_p2 = (tmp_1289_reg_69144 ^ 1'd1);

assign xor_ln41_1065_fu_67920_p2 = (tmp_1289_reg_69144 ^ or_ln41_803_fu_67915_p2);

assign xor_ln41_1066_fu_67925_p2 = (xor_ln41_1065_fu_67920_p2 ^ 1'd1);

assign xor_ln41_1067_fu_67949_p2 = (tmp_1293_reg_69161 ^ 1'd1);

assign xor_ln41_1068_fu_67959_p2 = (tmp_1293_reg_69161 ^ or_ln41_806_fu_67954_p2);

assign xor_ln41_1069_fu_67964_p2 = (xor_ln41_1068_fu_67959_p2 ^ 1'd1);

assign xor_ln41_1070_fu_67988_p2 = (tmp_1297_reg_69178 ^ 1'd1);

assign xor_ln41_1071_fu_67998_p2 = (tmp_1297_reg_69178 ^ or_ln41_809_fu_67993_p2);

assign xor_ln41_1072_fu_68003_p2 = (xor_ln41_1071_fu_67998_p2 ^ 1'd1);

assign xor_ln41_1073_fu_68027_p2 = (tmp_1301_reg_69195 ^ 1'd1);

assign xor_ln41_1074_fu_68037_p2 = (tmp_1301_reg_69195 ^ or_ln41_812_fu_68032_p2);

assign xor_ln41_1075_fu_68042_p2 = (xor_ln41_1074_fu_68037_p2 ^ 1'd1);

assign xor_ln41_1076_fu_68066_p2 = (tmp_1305_reg_69212 ^ 1'd1);

assign xor_ln41_1077_fu_68076_p2 = (tmp_1305_reg_69212 ^ or_ln41_815_fu_68071_p2);

assign xor_ln41_1078_fu_68081_p2 = (xor_ln41_1077_fu_68076_p2 ^ 1'd1);

assign xor_ln41_1079_fu_68105_p2 = (tmp_1309_reg_69229 ^ 1'd1);

assign xor_ln41_1080_fu_68115_p2 = (tmp_1309_reg_69229 ^ or_ln41_818_fu_68110_p2);

assign xor_ln41_1081_fu_68120_p2 = (xor_ln41_1080_fu_68115_p2 ^ 1'd1);

assign xor_ln41_1082_fu_68144_p2 = (tmp_1313_reg_69246 ^ 1'd1);

assign xor_ln41_1083_fu_68154_p2 = (tmp_1313_reg_69246 ^ or_ln41_821_fu_68149_p2);

assign xor_ln41_1084_fu_68159_p2 = (xor_ln41_1083_fu_68154_p2 ^ 1'd1);

assign xor_ln41_1085_fu_68183_p2 = (tmp_1317_reg_69263 ^ 1'd1);

assign xor_ln41_1086_fu_68193_p2 = (tmp_1317_reg_69263 ^ or_ln41_824_fu_68188_p2);

assign xor_ln41_1087_fu_68198_p2 = (xor_ln41_1086_fu_68193_p2 ^ 1'd1);

assign xor_ln41_1088_fu_68330_p2 = (tmp_1324_fu_68256_p3 ^ 1'd1);

assign xor_ln41_1089_fu_68342_p2 = (tmp_1324_fu_68256_p3 ^ or_ln41_827_fu_68336_p2);

assign xor_ln41_1090_fu_68348_p2 = (xor_ln41_1089_fu_68342_p2 ^ 1'd1);

assign xor_ln41_1091_fu_68374_p2 = (tmp_1328_reg_69286 ^ 1'd1);

assign xor_ln41_1092_fu_68384_p2 = (tmp_1328_reg_69286 ^ or_ln41_830_fu_68379_p2);

assign xor_ln41_1093_fu_68389_p2 = (xor_ln41_1092_fu_68384_p2 ^ 1'd1);

assign xor_ln41_1094_fu_68413_p2 = (tmp_1332_reg_69303 ^ 1'd1);

assign xor_ln41_1095_fu_68423_p2 = (tmp_1332_reg_69303 ^ or_ln41_833_fu_68418_p2);

assign xor_ln41_1096_fu_68428_p2 = (xor_ln41_1095_fu_68423_p2 ^ 1'd1);

assign xor_ln41_1097_fu_68452_p2 = (tmp_1336_reg_69320 ^ 1'd1);

assign xor_ln41_1098_fu_68462_p2 = (tmp_1336_reg_69320 ^ or_ln41_836_fu_68457_p2);

assign xor_ln41_1099_fu_68467_p2 = (xor_ln41_1098_fu_68462_p2 ^ 1'd1);

assign xor_ln41_1100_fu_68491_p2 = (tmp_1340_reg_69337 ^ 1'd1);

assign xor_ln41_1101_fu_68501_p2 = (tmp_1340_reg_69337 ^ or_ln41_839_fu_68496_p2);

assign xor_ln41_1102_fu_68506_p2 = (xor_ln41_1101_fu_68501_p2 ^ 1'd1);

assign xor_ln41_1103_fu_68530_p2 = (tmp_1344_reg_69354 ^ 1'd1);

assign xor_ln41_1104_fu_68540_p2 = (tmp_1344_reg_69354 ^ or_ln41_842_fu_68535_p2);

assign xor_ln41_1105_fu_68545_p2 = (xor_ln41_1104_fu_68540_p2 ^ 1'd1);

assign xor_ln41_1106_fu_68569_p2 = (tmp_1348_reg_69371 ^ 1'd1);

assign xor_ln41_1107_fu_68579_p2 = (tmp_1348_reg_69371 ^ or_ln41_845_fu_68574_p2);

assign xor_ln41_1108_fu_68584_p2 = (xor_ln41_1107_fu_68579_p2 ^ 1'd1);

assign xor_ln41_1109_fu_68608_p2 = (tmp_1352_reg_69388 ^ 1'd1);

assign xor_ln41_1110_fu_68618_p2 = (tmp_1352_reg_69388 ^ or_ln41_848_fu_68613_p2);

assign xor_ln41_1111_fu_68623_p2 = (xor_ln41_1110_fu_68618_p2 ^ 1'd1);

assign xor_ln41_1112_fu_68647_p2 = (tmp_1356_reg_69405 ^ 1'd1);

assign xor_ln41_1113_fu_68657_p2 = (tmp_1356_reg_69405 ^ or_ln41_851_fu_68652_p2);

assign xor_ln41_1114_fu_68662_p2 = (xor_ln41_1113_fu_68657_p2 ^ 1'd1);

assign xor_ln41_1115_fu_68686_p2 = (tmp_1360_reg_69422 ^ 1'd1);

assign xor_ln41_1116_fu_68696_p2 = (tmp_1360_reg_69422 ^ or_ln41_854_fu_68691_p2);

assign xor_ln41_1117_fu_68701_p2 = (xor_ln41_1116_fu_68696_p2 ^ 1'd1);

assign xor_ln41_1118_fu_68725_p2 = (tmp_1364_reg_69439 ^ 1'd1);

assign xor_ln41_1119_fu_68735_p2 = (tmp_1364_reg_69439 ^ or_ln41_857_fu_68730_p2);

assign xor_ln41_1120_fu_68740_p2 = (xor_ln41_1119_fu_68735_p2 ^ 1'd1);

assign xor_ln41_1121_fu_68764_p2 = (tmp_1368_reg_69456 ^ 1'd1);

assign xor_ln41_1122_fu_68774_p2 = (tmp_1368_reg_69456 ^ or_ln41_858_fu_68769_p2);

assign xor_ln41_1123_fu_68779_p2 = (xor_ln41_1122_fu_68774_p2 ^ 1'd1);

assign xor_ln41_1124_fu_68803_p2 = (tmp_1372_reg_69473 ^ 1'd1);

assign xor_ln41_1125_fu_68813_p2 = (tmp_1372_reg_69473 ^ or_ln41_859_fu_68808_p2);

assign xor_ln41_1126_fu_68818_p2 = (xor_ln41_1125_fu_68813_p2 ^ 1'd1);

assign xor_ln41_1127_fu_68842_p2 = (tmp_1376_reg_69490 ^ 1'd1);

assign xor_ln41_1128_fu_68852_p2 = (tmp_1376_reg_69490 ^ or_ln41_860_fu_68847_p2);

assign xor_ln41_1129_fu_68857_p2 = (xor_ln41_1128_fu_68852_p2 ^ 1'd1);

assign xor_ln41_fu_67520_p2 = (tmp_reg_68974 ^ 1'd1);

assign zext_ln41_251_fu_65024_p1 = and_ln41_900_fu_65018_p2;

assign zext_ln41_252_fu_65109_p1 = and_ln41_902_fu_65103_p2;

assign zext_ln41_253_fu_65194_p1 = and_ln41_904_fu_65188_p2;

assign zext_ln41_254_fu_65279_p1 = and_ln41_906_fu_65273_p2;

assign zext_ln41_255_fu_65364_p1 = and_ln41_908_fu_65358_p2;

assign zext_ln41_256_fu_65449_p1 = and_ln41_910_fu_65443_p2;

assign zext_ln41_257_fu_65534_p1 = and_ln41_912_fu_65528_p2;

assign zext_ln41_258_fu_65619_p1 = and_ln41_914_fu_65613_p2;

assign zext_ln41_259_fu_65704_p1 = and_ln41_916_fu_65698_p2;

assign zext_ln41_260_fu_65789_p1 = and_ln41_918_fu_65783_p2;

assign zext_ln41_261_fu_65874_p1 = and_ln41_920_fu_65868_p2;

assign zext_ln41_262_fu_65959_p1 = and_ln41_922_fu_65953_p2;

assign zext_ln41_263_fu_66044_p1 = and_ln41_924_fu_66038_p2;

assign zext_ln41_264_fu_66129_p1 = and_ln41_926_fu_66123_p2;

assign zext_ln41_265_fu_66214_p1 = and_ln41_928_fu_66208_p2;

assign zext_ln41_266_fu_66299_p1 = and_ln41_930_fu_66293_p2;

assign zext_ln41_267_fu_66384_p1 = and_ln41_932_fu_66378_p2;

assign zext_ln41_268_fu_68312_p1 = and_ln41_934_fu_68306_p2;

assign zext_ln41_269_fu_66479_p1 = and_ln41_936_fu_66473_p2;

assign zext_ln41_270_fu_66564_p1 = and_ln41_938_fu_66558_p2;

assign zext_ln41_271_fu_66649_p1 = and_ln41_940_fu_66643_p2;

assign zext_ln41_272_fu_66734_p1 = and_ln41_942_fu_66728_p2;

assign zext_ln41_273_fu_66819_p1 = and_ln41_944_fu_66813_p2;

assign zext_ln41_274_fu_66904_p1 = and_ln41_946_fu_66898_p2;

assign zext_ln41_275_fu_66989_p1 = and_ln41_948_fu_66983_p2;

assign zext_ln41_276_fu_67074_p1 = and_ln41_950_fu_67068_p2;

assign zext_ln41_277_fu_67159_p1 = and_ln41_952_fu_67153_p2;

assign zext_ln41_278_fu_67244_p1 = and_ln41_954_fu_67238_p2;

assign zext_ln41_279_fu_67329_p1 = and_ln41_956_fu_67323_p2;

assign zext_ln41_280_fu_67414_p1 = and_ln41_958_fu_67408_p2;

assign zext_ln41_281_fu_67499_p1 = and_ln41_960_fu_67493_p2;

assign zext_ln41_fu_64935_p1 = and_ln41_fu_64929_p2;

endmodule //resnet8_resource_fifo_opt_normalize_array_ap_fixed_32u_array_ap_fixed_22_12_4_0_0_32u_config13_s
