// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module resnet8_resource_fifo_opt_relu_array_ap_fixed_32u_array_ap_fixed_22_12_4_0_0_32u_relu_config20_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer19_out_dout,
        layer19_out_empty_n,
        layer19_out_read,
        layer19_out_num_data_valid,
        layer19_out_fifo_cap,
        layer20_out_din,
        layer20_out_full_n,
        layer20_out_write,
        layer20_out_num_data_valid,
        layer20_out_fifo_cap,
        start_out,
        start_write
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [703:0] layer19_out_dout;
input   layer19_out_empty_n;
output   layer19_out_read;
input  [1:0] layer19_out_num_data_valid;
input  [1:0] layer19_out_fifo_cap;
output  [703:0] layer20_out_din;
input   layer20_out_full_n;
output   layer20_out_write;
input  [1:0] layer20_out_num_data_valid;
input  [1:0] layer20_out_fifo_cap;
output   start_out;
output   start_write;

reg ap_idle;
reg layer19_out_read;
reg layer20_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln41_fu_1536_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer19_out_blk_n;
reg    layer20_out_blk_n;
reg   [7:0] i1_fu_232;
wire   [7:0] i_fu_1530_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_i1_load;
wire   [21:0] trunc_ln44_fu_257_p1;
wire   [0:0] icmp_ln51_fu_885_p2;
wire   [20:0] trunc_ln44_219_fu_261_p1;
wire   [20:0] select_ln51_fu_891_p3;
wire   [21:0] trunc_ln44_127_fu_265_p4;
wire   [0:0] icmp_ln51_127_fu_903_p2;
wire   [20:0] trunc_ln44_s_fu_275_p4;
wire   [20:0] select_ln51_127_fu_909_p3;
wire   [21:0] trunc_ln44_128_fu_285_p4;
wire   [0:0] icmp_ln51_128_fu_921_p2;
wire   [20:0] trunc_ln44_188_fu_295_p4;
wire   [20:0] select_ln51_128_fu_927_p3;
wire   [21:0] trunc_ln44_129_fu_305_p4;
wire   [0:0] icmp_ln51_129_fu_939_p2;
wire   [20:0] trunc_ln44_189_fu_315_p4;
wire   [20:0] select_ln51_129_fu_945_p3;
wire   [21:0] trunc_ln44_130_fu_325_p4;
wire   [0:0] icmp_ln51_130_fu_957_p2;
wire   [20:0] trunc_ln44_190_fu_335_p4;
wire   [20:0] select_ln51_130_fu_963_p3;
wire   [21:0] trunc_ln44_131_fu_345_p4;
wire   [0:0] icmp_ln51_131_fu_975_p2;
wire   [20:0] trunc_ln44_191_fu_355_p4;
wire   [20:0] select_ln51_131_fu_981_p3;
wire   [21:0] trunc_ln44_132_fu_365_p4;
wire   [0:0] icmp_ln51_132_fu_993_p2;
wire   [20:0] trunc_ln44_192_fu_375_p4;
wire   [20:0] select_ln51_132_fu_999_p3;
wire   [21:0] trunc_ln44_133_fu_385_p4;
wire   [0:0] icmp_ln51_133_fu_1011_p2;
wire   [20:0] trunc_ln44_193_fu_395_p4;
wire   [20:0] select_ln51_133_fu_1017_p3;
wire   [21:0] trunc_ln44_134_fu_405_p4;
wire   [0:0] icmp_ln51_134_fu_1029_p2;
wire   [20:0] trunc_ln44_194_fu_415_p4;
wire   [20:0] select_ln51_134_fu_1035_p3;
wire   [21:0] trunc_ln44_135_fu_425_p4;
wire   [0:0] icmp_ln51_135_fu_1047_p2;
wire   [20:0] trunc_ln44_195_fu_435_p4;
wire   [20:0] select_ln51_135_fu_1053_p3;
wire   [21:0] trunc_ln44_136_fu_445_p4;
wire   [0:0] icmp_ln51_136_fu_1065_p2;
wire   [20:0] trunc_ln44_196_fu_455_p4;
wire   [20:0] select_ln51_136_fu_1071_p3;
wire   [21:0] trunc_ln44_137_fu_465_p4;
wire   [0:0] icmp_ln51_137_fu_1083_p2;
wire   [20:0] trunc_ln44_197_fu_475_p4;
wire   [20:0] select_ln51_137_fu_1089_p3;
wire   [21:0] trunc_ln44_138_fu_485_p4;
wire   [0:0] icmp_ln51_138_fu_1101_p2;
wire   [20:0] trunc_ln44_198_fu_495_p4;
wire   [20:0] select_ln51_138_fu_1107_p3;
wire   [21:0] trunc_ln44_139_fu_505_p4;
wire   [0:0] icmp_ln51_139_fu_1119_p2;
wire   [20:0] trunc_ln44_199_fu_515_p4;
wire   [20:0] select_ln51_139_fu_1125_p3;
wire   [21:0] trunc_ln44_140_fu_525_p4;
wire   [0:0] icmp_ln51_140_fu_1137_p2;
wire   [20:0] trunc_ln44_200_fu_535_p4;
wire   [20:0] select_ln51_140_fu_1143_p3;
wire   [21:0] trunc_ln44_141_fu_545_p4;
wire   [0:0] icmp_ln51_141_fu_1155_p2;
wire   [20:0] trunc_ln44_201_fu_555_p4;
wire   [20:0] select_ln51_141_fu_1161_p3;
wire   [21:0] trunc_ln44_142_fu_565_p4;
wire   [0:0] icmp_ln51_142_fu_1173_p2;
wire   [20:0] trunc_ln44_202_fu_575_p4;
wire   [20:0] select_ln51_142_fu_1179_p3;
wire   [21:0] trunc_ln44_143_fu_585_p4;
wire   [0:0] icmp_ln51_143_fu_1191_p2;
wire   [20:0] trunc_ln44_203_fu_595_p4;
wire   [20:0] select_ln51_143_fu_1197_p3;
wire   [21:0] trunc_ln44_144_fu_605_p4;
wire   [0:0] icmp_ln51_144_fu_1209_p2;
wire   [20:0] trunc_ln44_204_fu_615_p4;
wire   [20:0] select_ln51_144_fu_1215_p3;
wire   [21:0] trunc_ln44_145_fu_625_p4;
wire   [0:0] icmp_ln51_145_fu_1227_p2;
wire   [20:0] trunc_ln44_205_fu_635_p4;
wire   [20:0] select_ln51_145_fu_1233_p3;
wire   [21:0] trunc_ln44_146_fu_645_p4;
wire   [0:0] icmp_ln51_146_fu_1245_p2;
wire   [20:0] trunc_ln44_206_fu_655_p4;
wire   [20:0] select_ln51_146_fu_1251_p3;
wire   [21:0] trunc_ln44_147_fu_665_p4;
wire   [0:0] icmp_ln51_147_fu_1263_p2;
wire   [20:0] trunc_ln44_207_fu_675_p4;
wire   [20:0] select_ln51_147_fu_1269_p3;
wire   [21:0] trunc_ln44_148_fu_685_p4;
wire   [0:0] icmp_ln51_148_fu_1281_p2;
wire   [20:0] trunc_ln44_208_fu_695_p4;
wire   [20:0] select_ln51_148_fu_1287_p3;
wire   [21:0] trunc_ln44_149_fu_705_p4;
wire   [0:0] icmp_ln51_149_fu_1299_p2;
wire   [20:0] trunc_ln44_209_fu_715_p4;
wire   [20:0] select_ln51_149_fu_1305_p3;
wire   [21:0] trunc_ln44_150_fu_725_p4;
wire   [0:0] icmp_ln51_150_fu_1317_p2;
wire   [20:0] trunc_ln44_210_fu_735_p4;
wire   [20:0] select_ln51_150_fu_1323_p3;
wire   [21:0] trunc_ln44_151_fu_745_p4;
wire   [0:0] icmp_ln51_151_fu_1335_p2;
wire   [20:0] trunc_ln44_211_fu_755_p4;
wire   [20:0] select_ln51_151_fu_1341_p3;
wire   [21:0] trunc_ln44_152_fu_765_p4;
wire   [0:0] icmp_ln51_152_fu_1353_p2;
wire   [20:0] trunc_ln44_212_fu_775_p4;
wire   [20:0] select_ln51_152_fu_1359_p3;
wire   [21:0] trunc_ln44_153_fu_785_p4;
wire   [0:0] icmp_ln51_153_fu_1371_p2;
wire   [20:0] trunc_ln44_213_fu_795_p4;
wire   [20:0] select_ln51_153_fu_1377_p3;
wire   [21:0] trunc_ln44_154_fu_805_p4;
wire   [0:0] icmp_ln51_154_fu_1389_p2;
wire   [20:0] trunc_ln44_214_fu_815_p4;
wire   [20:0] select_ln51_154_fu_1395_p3;
wire   [21:0] trunc_ln44_155_fu_825_p4;
wire   [0:0] icmp_ln51_155_fu_1407_p2;
wire   [20:0] trunc_ln44_215_fu_835_p4;
wire   [20:0] select_ln51_155_fu_1413_p3;
wire   [21:0] trunc_ln44_156_fu_845_p4;
wire   [0:0] icmp_ln51_156_fu_1425_p2;
wire   [20:0] trunc_ln44_216_fu_855_p4;
wire   [20:0] select_ln51_156_fu_1431_p3;
wire   [21:0] trunc_ln44_157_fu_865_p4;
wire   [0:0] icmp_ln51_157_fu_1443_p2;
wire   [20:0] trunc_ln3_fu_875_p4;
wire   [20:0] select_ln51_157_fu_1449_p3;
wire   [21:0] zext_ln51_154_fu_1439_p1;
wire   [21:0] zext_ln51_153_fu_1421_p1;
wire   [21:0] zext_ln51_152_fu_1403_p1;
wire   [21:0] zext_ln51_151_fu_1385_p1;
wire   [21:0] zext_ln51_150_fu_1367_p1;
wire   [21:0] zext_ln51_149_fu_1349_p1;
wire   [21:0] zext_ln51_148_fu_1331_p1;
wire   [21:0] zext_ln51_147_fu_1313_p1;
wire   [21:0] zext_ln51_146_fu_1295_p1;
wire   [21:0] zext_ln51_145_fu_1277_p1;
wire   [21:0] zext_ln51_144_fu_1259_p1;
wire   [21:0] zext_ln51_143_fu_1241_p1;
wire   [21:0] zext_ln51_142_fu_1223_p1;
wire   [21:0] zext_ln51_141_fu_1205_p1;
wire   [21:0] zext_ln51_140_fu_1187_p1;
wire   [21:0] zext_ln51_139_fu_1169_p1;
wire   [21:0] zext_ln51_138_fu_1151_p1;
wire   [21:0] zext_ln51_137_fu_1133_p1;
wire   [21:0] zext_ln51_136_fu_1115_p1;
wire   [21:0] zext_ln51_135_fu_1097_p1;
wire   [21:0] zext_ln51_134_fu_1079_p1;
wire   [21:0] zext_ln51_133_fu_1061_p1;
wire   [21:0] zext_ln51_132_fu_1043_p1;
wire   [21:0] zext_ln51_131_fu_1025_p1;
wire   [21:0] zext_ln51_130_fu_1007_p1;
wire   [21:0] zext_ln51_129_fu_989_p1;
wire   [21:0] zext_ln51_128_fu_971_p1;
wire   [21:0] zext_ln51_127_fu_953_p1;
wire   [21:0] zext_ln51_126_fu_935_p1;
wire   [21:0] zext_ln51_125_fu_917_p1;
wire   [21:0] zext_ln51_fu_899_p1;
wire   [702:0] or_ln57_s_fu_1457_p33;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
#0 i1_fu_232 = 8'd0;
end

resnet8_resource_fifo_opt_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        i1_fu_232 <= i_fu_1530_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln41_fu_1536_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i1_load = 8'd0;
    end else begin
        ap_sig_allocacmp_i1_load = i1_fu_232;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer19_out_blk_n = layer19_out_empty_n;
    end else begin
        layer19_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        layer19_out_read = 1'b1;
    end else begin
        layer19_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer20_out_blk_n = layer20_out_full_n;
    end else begin
        layer20_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        layer20_out_write = 1'b1;
    end else begin
        layer20_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | (ap_done_reg == 1'b1) | (layer20_out_full_n == 1'b0) | (layer19_out_empty_n == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign i_fu_1530_p2 = (ap_sig_allocacmp_i1_load + 8'd1);

assign icmp_ln41_fu_1536_p2 = ((ap_sig_allocacmp_i1_load == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln51_127_fu_903_p2 = (($signed(trunc_ln44_127_fu_265_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_128_fu_921_p2 = (($signed(trunc_ln44_128_fu_285_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_129_fu_939_p2 = (($signed(trunc_ln44_129_fu_305_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_130_fu_957_p2 = (($signed(trunc_ln44_130_fu_325_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_131_fu_975_p2 = (($signed(trunc_ln44_131_fu_345_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_132_fu_993_p2 = (($signed(trunc_ln44_132_fu_365_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_133_fu_1011_p2 = (($signed(trunc_ln44_133_fu_385_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_134_fu_1029_p2 = (($signed(trunc_ln44_134_fu_405_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_135_fu_1047_p2 = (($signed(trunc_ln44_135_fu_425_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_136_fu_1065_p2 = (($signed(trunc_ln44_136_fu_445_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_137_fu_1083_p2 = (($signed(trunc_ln44_137_fu_465_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_138_fu_1101_p2 = (($signed(trunc_ln44_138_fu_485_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_139_fu_1119_p2 = (($signed(trunc_ln44_139_fu_505_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_140_fu_1137_p2 = (($signed(trunc_ln44_140_fu_525_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_141_fu_1155_p2 = (($signed(trunc_ln44_141_fu_545_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_142_fu_1173_p2 = (($signed(trunc_ln44_142_fu_565_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_143_fu_1191_p2 = (($signed(trunc_ln44_143_fu_585_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_144_fu_1209_p2 = (($signed(trunc_ln44_144_fu_605_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_145_fu_1227_p2 = (($signed(trunc_ln44_145_fu_625_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_146_fu_1245_p2 = (($signed(trunc_ln44_146_fu_645_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_147_fu_1263_p2 = (($signed(trunc_ln44_147_fu_665_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_148_fu_1281_p2 = (($signed(trunc_ln44_148_fu_685_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_149_fu_1299_p2 = (($signed(trunc_ln44_149_fu_705_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_150_fu_1317_p2 = (($signed(trunc_ln44_150_fu_725_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_151_fu_1335_p2 = (($signed(trunc_ln44_151_fu_745_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_152_fu_1353_p2 = (($signed(trunc_ln44_152_fu_765_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_153_fu_1371_p2 = (($signed(trunc_ln44_153_fu_785_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_154_fu_1389_p2 = (($signed(trunc_ln44_154_fu_805_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_155_fu_1407_p2 = (($signed(trunc_ln44_155_fu_825_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_156_fu_1425_p2 = (($signed(trunc_ln44_156_fu_845_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_157_fu_1443_p2 = (($signed(trunc_ln44_157_fu_865_p4) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_885_p2 = (($signed(trunc_ln44_fu_257_p1) > $signed(22'd0)) ? 1'b1 : 1'b0);

assign layer20_out_din = or_ln57_s_fu_1457_p33;

assign or_ln57_s_fu_1457_p33 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{select_ln51_157_fu_1449_p3}, {zext_ln51_154_fu_1439_p1}}, {zext_ln51_153_fu_1421_p1}}, {zext_ln51_152_fu_1403_p1}}, {zext_ln51_151_fu_1385_p1}}, {zext_ln51_150_fu_1367_p1}}, {zext_ln51_149_fu_1349_p1}}, {zext_ln51_148_fu_1331_p1}}, {zext_ln51_147_fu_1313_p1}}, {zext_ln51_146_fu_1295_p1}}, {zext_ln51_145_fu_1277_p1}}, {zext_ln51_144_fu_1259_p1}}, {zext_ln51_143_fu_1241_p1}}, {zext_ln51_142_fu_1223_p1}}, {zext_ln51_141_fu_1205_p1}}, {zext_ln51_140_fu_1187_p1}}, {zext_ln51_139_fu_1169_p1}}, {zext_ln51_138_fu_1151_p1}}, {zext_ln51_137_fu_1133_p1}}, {zext_ln51_136_fu_1115_p1}}, {zext_ln51_135_fu_1097_p1}}, {zext_ln51_134_fu_1079_p1}}, {zext_ln51_133_fu_1061_p1}}, {zext_ln51_132_fu_1043_p1}}, {zext_ln51_131_fu_1025_p1}}, {zext_ln51_130_fu_1007_p1}}, {zext_ln51_129_fu_989_p1}}, {zext_ln51_128_fu_971_p1}}, {zext_ln51_127_fu_953_p1}}, {zext_ln51_126_fu_935_p1}}, {zext_ln51_125_fu_917_p1}}, {zext_ln51_fu_899_p1}};

assign select_ln51_127_fu_909_p3 = ((icmp_ln51_127_fu_903_p2[0:0] == 1'b1) ? trunc_ln44_s_fu_275_p4 : 21'd0);

assign select_ln51_128_fu_927_p3 = ((icmp_ln51_128_fu_921_p2[0:0] == 1'b1) ? trunc_ln44_188_fu_295_p4 : 21'd0);

assign select_ln51_129_fu_945_p3 = ((icmp_ln51_129_fu_939_p2[0:0] == 1'b1) ? trunc_ln44_189_fu_315_p4 : 21'd0);

assign select_ln51_130_fu_963_p3 = ((icmp_ln51_130_fu_957_p2[0:0] == 1'b1) ? trunc_ln44_190_fu_335_p4 : 21'd0);

assign select_ln51_131_fu_981_p3 = ((icmp_ln51_131_fu_975_p2[0:0] == 1'b1) ? trunc_ln44_191_fu_355_p4 : 21'd0);

assign select_ln51_132_fu_999_p3 = ((icmp_ln51_132_fu_993_p2[0:0] == 1'b1) ? trunc_ln44_192_fu_375_p4 : 21'd0);

assign select_ln51_133_fu_1017_p3 = ((icmp_ln51_133_fu_1011_p2[0:0] == 1'b1) ? trunc_ln44_193_fu_395_p4 : 21'd0);

assign select_ln51_134_fu_1035_p3 = ((icmp_ln51_134_fu_1029_p2[0:0] == 1'b1) ? trunc_ln44_194_fu_415_p4 : 21'd0);

assign select_ln51_135_fu_1053_p3 = ((icmp_ln51_135_fu_1047_p2[0:0] == 1'b1) ? trunc_ln44_195_fu_435_p4 : 21'd0);

assign select_ln51_136_fu_1071_p3 = ((icmp_ln51_136_fu_1065_p2[0:0] == 1'b1) ? trunc_ln44_196_fu_455_p4 : 21'd0);

assign select_ln51_137_fu_1089_p3 = ((icmp_ln51_137_fu_1083_p2[0:0] == 1'b1) ? trunc_ln44_197_fu_475_p4 : 21'd0);

assign select_ln51_138_fu_1107_p3 = ((icmp_ln51_138_fu_1101_p2[0:0] == 1'b1) ? trunc_ln44_198_fu_495_p4 : 21'd0);

assign select_ln51_139_fu_1125_p3 = ((icmp_ln51_139_fu_1119_p2[0:0] == 1'b1) ? trunc_ln44_199_fu_515_p4 : 21'd0);

assign select_ln51_140_fu_1143_p3 = ((icmp_ln51_140_fu_1137_p2[0:0] == 1'b1) ? trunc_ln44_200_fu_535_p4 : 21'd0);

assign select_ln51_141_fu_1161_p3 = ((icmp_ln51_141_fu_1155_p2[0:0] == 1'b1) ? trunc_ln44_201_fu_555_p4 : 21'd0);

assign select_ln51_142_fu_1179_p3 = ((icmp_ln51_142_fu_1173_p2[0:0] == 1'b1) ? trunc_ln44_202_fu_575_p4 : 21'd0);

assign select_ln51_143_fu_1197_p3 = ((icmp_ln51_143_fu_1191_p2[0:0] == 1'b1) ? trunc_ln44_203_fu_595_p4 : 21'd0);

assign select_ln51_144_fu_1215_p3 = ((icmp_ln51_144_fu_1209_p2[0:0] == 1'b1) ? trunc_ln44_204_fu_615_p4 : 21'd0);

assign select_ln51_145_fu_1233_p3 = ((icmp_ln51_145_fu_1227_p2[0:0] == 1'b1) ? trunc_ln44_205_fu_635_p4 : 21'd0);

assign select_ln51_146_fu_1251_p3 = ((icmp_ln51_146_fu_1245_p2[0:0] == 1'b1) ? trunc_ln44_206_fu_655_p4 : 21'd0);

assign select_ln51_147_fu_1269_p3 = ((icmp_ln51_147_fu_1263_p2[0:0] == 1'b1) ? trunc_ln44_207_fu_675_p4 : 21'd0);

assign select_ln51_148_fu_1287_p3 = ((icmp_ln51_148_fu_1281_p2[0:0] == 1'b1) ? trunc_ln44_208_fu_695_p4 : 21'd0);

assign select_ln51_149_fu_1305_p3 = ((icmp_ln51_149_fu_1299_p2[0:0] == 1'b1) ? trunc_ln44_209_fu_715_p4 : 21'd0);

assign select_ln51_150_fu_1323_p3 = ((icmp_ln51_150_fu_1317_p2[0:0] == 1'b1) ? trunc_ln44_210_fu_735_p4 : 21'd0);

assign select_ln51_151_fu_1341_p3 = ((icmp_ln51_151_fu_1335_p2[0:0] == 1'b1) ? trunc_ln44_211_fu_755_p4 : 21'd0);

assign select_ln51_152_fu_1359_p3 = ((icmp_ln51_152_fu_1353_p2[0:0] == 1'b1) ? trunc_ln44_212_fu_775_p4 : 21'd0);

assign select_ln51_153_fu_1377_p3 = ((icmp_ln51_153_fu_1371_p2[0:0] == 1'b1) ? trunc_ln44_213_fu_795_p4 : 21'd0);

assign select_ln51_154_fu_1395_p3 = ((icmp_ln51_154_fu_1389_p2[0:0] == 1'b1) ? trunc_ln44_214_fu_815_p4 : 21'd0);

assign select_ln51_155_fu_1413_p3 = ((icmp_ln51_155_fu_1407_p2[0:0] == 1'b1) ? trunc_ln44_215_fu_835_p4 : 21'd0);

assign select_ln51_156_fu_1431_p3 = ((icmp_ln51_156_fu_1425_p2[0:0] == 1'b1) ? trunc_ln44_216_fu_855_p4 : 21'd0);

assign select_ln51_157_fu_1449_p3 = ((icmp_ln51_157_fu_1443_p2[0:0] == 1'b1) ? trunc_ln3_fu_875_p4 : 21'd0);

assign select_ln51_fu_891_p3 = ((icmp_ln51_fu_885_p2[0:0] == 1'b1) ? trunc_ln44_219_fu_261_p1 : 21'd0);

assign start_out = real_start;

assign trunc_ln3_fu_875_p4 = {{layer19_out_dout[702:682]}};

assign trunc_ln44_127_fu_265_p4 = {{layer19_out_dout[43:22]}};

assign trunc_ln44_128_fu_285_p4 = {{layer19_out_dout[65:44]}};

assign trunc_ln44_129_fu_305_p4 = {{layer19_out_dout[87:66]}};

assign trunc_ln44_130_fu_325_p4 = {{layer19_out_dout[109:88]}};

assign trunc_ln44_131_fu_345_p4 = {{layer19_out_dout[131:110]}};

assign trunc_ln44_132_fu_365_p4 = {{layer19_out_dout[153:132]}};

assign trunc_ln44_133_fu_385_p4 = {{layer19_out_dout[175:154]}};

assign trunc_ln44_134_fu_405_p4 = {{layer19_out_dout[197:176]}};

assign trunc_ln44_135_fu_425_p4 = {{layer19_out_dout[219:198]}};

assign trunc_ln44_136_fu_445_p4 = {{layer19_out_dout[241:220]}};

assign trunc_ln44_137_fu_465_p4 = {{layer19_out_dout[263:242]}};

assign trunc_ln44_138_fu_485_p4 = {{layer19_out_dout[285:264]}};

assign trunc_ln44_139_fu_505_p4 = {{layer19_out_dout[307:286]}};

assign trunc_ln44_140_fu_525_p4 = {{layer19_out_dout[329:308]}};

assign trunc_ln44_141_fu_545_p4 = {{layer19_out_dout[351:330]}};

assign trunc_ln44_142_fu_565_p4 = {{layer19_out_dout[373:352]}};

assign trunc_ln44_143_fu_585_p4 = {{layer19_out_dout[395:374]}};

assign trunc_ln44_144_fu_605_p4 = {{layer19_out_dout[417:396]}};

assign trunc_ln44_145_fu_625_p4 = {{layer19_out_dout[439:418]}};

assign trunc_ln44_146_fu_645_p4 = {{layer19_out_dout[461:440]}};

assign trunc_ln44_147_fu_665_p4 = {{layer19_out_dout[483:462]}};

assign trunc_ln44_148_fu_685_p4 = {{layer19_out_dout[505:484]}};

assign trunc_ln44_149_fu_705_p4 = {{layer19_out_dout[527:506]}};

assign trunc_ln44_150_fu_725_p4 = {{layer19_out_dout[549:528]}};

assign trunc_ln44_151_fu_745_p4 = {{layer19_out_dout[571:550]}};

assign trunc_ln44_152_fu_765_p4 = {{layer19_out_dout[593:572]}};

assign trunc_ln44_153_fu_785_p4 = {{layer19_out_dout[615:594]}};

assign trunc_ln44_154_fu_805_p4 = {{layer19_out_dout[637:616]}};

assign trunc_ln44_155_fu_825_p4 = {{layer19_out_dout[659:638]}};

assign trunc_ln44_156_fu_845_p4 = {{layer19_out_dout[681:660]}};

assign trunc_ln44_157_fu_865_p4 = {{layer19_out_dout[703:682]}};

assign trunc_ln44_188_fu_295_p4 = {{layer19_out_dout[64:44]}};

assign trunc_ln44_189_fu_315_p4 = {{layer19_out_dout[86:66]}};

assign trunc_ln44_190_fu_335_p4 = {{layer19_out_dout[108:88]}};

assign trunc_ln44_191_fu_355_p4 = {{layer19_out_dout[130:110]}};

assign trunc_ln44_192_fu_375_p4 = {{layer19_out_dout[152:132]}};

assign trunc_ln44_193_fu_395_p4 = {{layer19_out_dout[174:154]}};

assign trunc_ln44_194_fu_415_p4 = {{layer19_out_dout[196:176]}};

assign trunc_ln44_195_fu_435_p4 = {{layer19_out_dout[218:198]}};

assign trunc_ln44_196_fu_455_p4 = {{layer19_out_dout[240:220]}};

assign trunc_ln44_197_fu_475_p4 = {{layer19_out_dout[262:242]}};

assign trunc_ln44_198_fu_495_p4 = {{layer19_out_dout[284:264]}};

assign trunc_ln44_199_fu_515_p4 = {{layer19_out_dout[306:286]}};

assign trunc_ln44_200_fu_535_p4 = {{layer19_out_dout[328:308]}};

assign trunc_ln44_201_fu_555_p4 = {{layer19_out_dout[350:330]}};

assign trunc_ln44_202_fu_575_p4 = {{layer19_out_dout[372:352]}};

assign trunc_ln44_203_fu_595_p4 = {{layer19_out_dout[394:374]}};

assign trunc_ln44_204_fu_615_p4 = {{layer19_out_dout[416:396]}};

assign trunc_ln44_205_fu_635_p4 = {{layer19_out_dout[438:418]}};

assign trunc_ln44_206_fu_655_p4 = {{layer19_out_dout[460:440]}};

assign trunc_ln44_207_fu_675_p4 = {{layer19_out_dout[482:462]}};

assign trunc_ln44_208_fu_695_p4 = {{layer19_out_dout[504:484]}};

assign trunc_ln44_209_fu_715_p4 = {{layer19_out_dout[526:506]}};

assign trunc_ln44_210_fu_735_p4 = {{layer19_out_dout[548:528]}};

assign trunc_ln44_211_fu_755_p4 = {{layer19_out_dout[570:550]}};

assign trunc_ln44_212_fu_775_p4 = {{layer19_out_dout[592:572]}};

assign trunc_ln44_213_fu_795_p4 = {{layer19_out_dout[614:594]}};

assign trunc_ln44_214_fu_815_p4 = {{layer19_out_dout[636:616]}};

assign trunc_ln44_215_fu_835_p4 = {{layer19_out_dout[658:638]}};

assign trunc_ln44_216_fu_855_p4 = {{layer19_out_dout[680:660]}};

assign trunc_ln44_219_fu_261_p1 = layer19_out_dout[20:0];

assign trunc_ln44_fu_257_p1 = layer19_out_dout[21:0];

assign trunc_ln44_s_fu_275_p4 = {{layer19_out_dout[42:22]}};

assign zext_ln51_125_fu_917_p1 = select_ln51_127_fu_909_p3;

assign zext_ln51_126_fu_935_p1 = select_ln51_128_fu_927_p3;

assign zext_ln51_127_fu_953_p1 = select_ln51_129_fu_945_p3;

assign zext_ln51_128_fu_971_p1 = select_ln51_130_fu_963_p3;

assign zext_ln51_129_fu_989_p1 = select_ln51_131_fu_981_p3;

assign zext_ln51_130_fu_1007_p1 = select_ln51_132_fu_999_p3;

assign zext_ln51_131_fu_1025_p1 = select_ln51_133_fu_1017_p3;

assign zext_ln51_132_fu_1043_p1 = select_ln51_134_fu_1035_p3;

assign zext_ln51_133_fu_1061_p1 = select_ln51_135_fu_1053_p3;

assign zext_ln51_134_fu_1079_p1 = select_ln51_136_fu_1071_p3;

assign zext_ln51_135_fu_1097_p1 = select_ln51_137_fu_1089_p3;

assign zext_ln51_136_fu_1115_p1 = select_ln51_138_fu_1107_p3;

assign zext_ln51_137_fu_1133_p1 = select_ln51_139_fu_1125_p3;

assign zext_ln51_138_fu_1151_p1 = select_ln51_140_fu_1143_p3;

assign zext_ln51_139_fu_1169_p1 = select_ln51_141_fu_1161_p3;

assign zext_ln51_140_fu_1187_p1 = select_ln51_142_fu_1179_p3;

assign zext_ln51_141_fu_1205_p1 = select_ln51_143_fu_1197_p3;

assign zext_ln51_142_fu_1223_p1 = select_ln51_144_fu_1215_p3;

assign zext_ln51_143_fu_1241_p1 = select_ln51_145_fu_1233_p3;

assign zext_ln51_144_fu_1259_p1 = select_ln51_146_fu_1251_p3;

assign zext_ln51_145_fu_1277_p1 = select_ln51_147_fu_1269_p3;

assign zext_ln51_146_fu_1295_p1 = select_ln51_148_fu_1287_p3;

assign zext_ln51_147_fu_1313_p1 = select_ln51_149_fu_1305_p3;

assign zext_ln51_148_fu_1331_p1 = select_ln51_150_fu_1323_p3;

assign zext_ln51_149_fu_1349_p1 = select_ln51_151_fu_1341_p3;

assign zext_ln51_150_fu_1367_p1 = select_ln51_152_fu_1359_p3;

assign zext_ln51_151_fu_1385_p1 = select_ln51_153_fu_1377_p3;

assign zext_ln51_152_fu_1403_p1 = select_ln51_154_fu_1395_p3;

assign zext_ln51_153_fu_1421_p1 = select_ln51_155_fu_1413_p3;

assign zext_ln51_154_fu_1439_p1 = select_ln51_156_fu_1431_p3;

assign zext_ln51_fu_899_p1 = select_ln51_fu_891_p3;

endmodule //resnet8_resource_fifo_opt_relu_array_ap_fixed_32u_array_ap_fixed_22_12_4_0_0_32u_relu_config20_s
