// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module resnet8_resource_fifo_opt_add_array_array_array_ap_fixed_22_12_4_0_0_16u_config10_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer9_out_dout,
        layer9_out_empty_n,
        layer9_out_read,
        layer9_out_num_data_valid,
        layer9_out_fifo_cap,
        layer32_cpy2_dout,
        layer32_cpy2_empty_n,
        layer32_cpy2_read,
        layer32_cpy2_num_data_valid,
        layer32_cpy2_fifo_cap,
        layer10_out_din,
        layer10_out_full_n,
        layer10_out_write,
        layer10_out_num_data_valid,
        layer10_out_fifo_cap,
        start_out,
        start_write
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [351:0] layer9_out_dout;
input   layer9_out_empty_n;
output   layer9_out_read;
input  [1:0] layer9_out_num_data_valid;
input  [1:0] layer9_out_fifo_cap;
input  [351:0] layer32_cpy2_dout;
input   layer32_cpy2_empty_n;
output   layer32_cpy2_read;
input  [11:0] layer32_cpy2_num_data_valid;
input  [11:0] layer32_cpy2_fifo_cap;
output  [351:0] layer10_out_din;
input   layer10_out_full_n;
output   layer10_out_write;
input  [1:0] layer10_out_num_data_valid;
input  [1:0] layer10_out_fifo_cap;
output   start_out;
output   start_write;

reg ap_idle;
reg layer9_out_read;
reg layer32_cpy2_read;
reg layer10_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln15_fu_1616_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer9_out_blk_n;
reg    layer32_cpy2_blk_n;
reg    layer10_out_blk_n;
reg   [9:0] i1_fu_114;
wire   [9:0] i_fu_1610_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_i1_load;
wire  signed [21:0] trunc_ln18_fu_145_p1;
wire  signed [21:0] trunc_ln19_fu_299_p1;
wire  signed [22:0] sext_ln26_191_fu_457_p1;
wire  signed [22:0] sext_ln26_fu_453_p1;
wire   [22:0] add_ln26_191_fu_467_p2;
wire   [21:0] add_ln26_fu_461_p2;
wire   [0:0] tmp_fu_473_p3;
wire   [0:0] tmp_6124_fu_481_p3;
wire   [0:0] xor_ln26_fu_489_p2;
wire   [0:0] and_ln26_fu_495_p2;
wire   [0:0] xor_ln26_191_fu_501_p2;
wire   [21:0] select_ln26_fu_507_p3;
wire  signed [21:0] trunc_ln18_s_fu_149_p4;
wire  signed [21:0] trunc_ln19_s_fu_303_p4;
wire  signed [22:0] sext_ln26_193_fu_527_p1;
wire  signed [22:0] sext_ln26_192_fu_523_p1;
wire   [22:0] add_ln26_193_fu_537_p2;
wire   [21:0] add_ln26_192_fu_531_p2;
wire   [0:0] tmp_6125_fu_543_p3;
wire   [0:0] tmp_6126_fu_551_p3;
wire   [0:0] xor_ln26_192_fu_559_p2;
wire   [0:0] and_ln26_95_fu_565_p2;
wire   [0:0] xor_ln26_193_fu_571_p2;
wire   [21:0] select_ln26_192_fu_577_p3;
wire  signed [21:0] trunc_ln18_31_fu_159_p4;
wire  signed [21:0] trunc_ln19_31_fu_313_p4;
wire  signed [22:0] sext_ln26_195_fu_597_p1;
wire  signed [22:0] sext_ln26_194_fu_593_p1;
wire   [22:0] add_ln26_195_fu_607_p2;
wire   [21:0] add_ln26_194_fu_601_p2;
wire   [0:0] tmp_6127_fu_613_p3;
wire   [0:0] tmp_6128_fu_621_p3;
wire   [0:0] xor_ln26_194_fu_629_p2;
wire   [0:0] and_ln26_96_fu_635_p2;
wire   [0:0] xor_ln26_195_fu_641_p2;
wire   [21:0] select_ln26_194_fu_647_p3;
wire  signed [21:0] trunc_ln18_32_fu_169_p4;
wire  signed [21:0] trunc_ln19_32_fu_323_p4;
wire  signed [22:0] sext_ln26_197_fu_667_p1;
wire  signed [22:0] sext_ln26_196_fu_663_p1;
wire   [22:0] add_ln26_197_fu_677_p2;
wire   [21:0] add_ln26_196_fu_671_p2;
wire   [0:0] tmp_6129_fu_683_p3;
wire   [0:0] tmp_6130_fu_691_p3;
wire   [0:0] xor_ln26_196_fu_699_p2;
wire   [0:0] and_ln26_97_fu_705_p2;
wire   [0:0] xor_ln26_197_fu_711_p2;
wire   [21:0] select_ln26_196_fu_717_p3;
wire  signed [21:0] trunc_ln18_33_fu_179_p4;
wire  signed [21:0] trunc_ln19_33_fu_333_p4;
wire  signed [22:0] sext_ln26_199_fu_737_p1;
wire  signed [22:0] sext_ln26_198_fu_733_p1;
wire   [22:0] add_ln26_199_fu_747_p2;
wire   [21:0] add_ln26_198_fu_741_p2;
wire   [0:0] tmp_6131_fu_753_p3;
wire   [0:0] tmp_6132_fu_761_p3;
wire   [0:0] xor_ln26_198_fu_769_p2;
wire   [0:0] and_ln26_98_fu_775_p2;
wire   [0:0] xor_ln26_199_fu_781_p2;
wire   [21:0] select_ln26_198_fu_787_p3;
wire  signed [21:0] trunc_ln18_34_fu_189_p4;
wire  signed [21:0] trunc_ln19_34_fu_343_p4;
wire  signed [22:0] sext_ln26_201_fu_807_p1;
wire  signed [22:0] sext_ln26_200_fu_803_p1;
wire   [22:0] add_ln26_201_fu_817_p2;
wire   [21:0] add_ln26_200_fu_811_p2;
wire   [0:0] tmp_6133_fu_823_p3;
wire   [0:0] tmp_6134_fu_831_p3;
wire   [0:0] xor_ln26_200_fu_839_p2;
wire   [0:0] and_ln26_99_fu_845_p2;
wire   [0:0] xor_ln26_201_fu_851_p2;
wire   [21:0] select_ln26_200_fu_857_p3;
wire  signed [21:0] trunc_ln18_35_fu_199_p4;
wire  signed [21:0] trunc_ln19_35_fu_353_p4;
wire  signed [22:0] sext_ln26_203_fu_877_p1;
wire  signed [22:0] sext_ln26_202_fu_873_p1;
wire   [22:0] add_ln26_203_fu_887_p2;
wire   [21:0] add_ln26_202_fu_881_p2;
wire   [0:0] tmp_6135_fu_893_p3;
wire   [0:0] tmp_6136_fu_901_p3;
wire   [0:0] xor_ln26_202_fu_909_p2;
wire   [0:0] and_ln26_100_fu_915_p2;
wire   [0:0] xor_ln26_203_fu_921_p2;
wire   [21:0] select_ln26_202_fu_927_p3;
wire  signed [21:0] trunc_ln18_36_fu_209_p4;
wire  signed [21:0] trunc_ln19_36_fu_363_p4;
wire  signed [22:0] sext_ln26_205_fu_947_p1;
wire  signed [22:0] sext_ln26_204_fu_943_p1;
wire   [22:0] add_ln26_205_fu_957_p2;
wire   [21:0] add_ln26_204_fu_951_p2;
wire   [0:0] tmp_6137_fu_963_p3;
wire   [0:0] tmp_6138_fu_971_p3;
wire   [0:0] xor_ln26_204_fu_979_p2;
wire   [0:0] and_ln26_101_fu_985_p2;
wire   [0:0] xor_ln26_205_fu_991_p2;
wire   [21:0] select_ln26_204_fu_997_p3;
wire  signed [21:0] trunc_ln18_37_fu_219_p4;
wire  signed [21:0] trunc_ln19_37_fu_373_p4;
wire  signed [22:0] sext_ln26_207_fu_1017_p1;
wire  signed [22:0] sext_ln26_206_fu_1013_p1;
wire   [22:0] add_ln26_207_fu_1027_p2;
wire   [21:0] add_ln26_206_fu_1021_p2;
wire   [0:0] tmp_6139_fu_1033_p3;
wire   [0:0] tmp_6140_fu_1041_p3;
wire   [0:0] xor_ln26_206_fu_1049_p2;
wire   [0:0] and_ln26_102_fu_1055_p2;
wire   [0:0] xor_ln26_207_fu_1061_p2;
wire   [21:0] select_ln26_206_fu_1067_p3;
wire  signed [21:0] trunc_ln18_38_fu_229_p4;
wire  signed [21:0] trunc_ln19_38_fu_383_p4;
wire  signed [22:0] sext_ln26_209_fu_1087_p1;
wire  signed [22:0] sext_ln26_208_fu_1083_p1;
wire   [22:0] add_ln26_209_fu_1097_p2;
wire   [21:0] add_ln26_208_fu_1091_p2;
wire   [0:0] tmp_6141_fu_1103_p3;
wire   [0:0] tmp_6142_fu_1111_p3;
wire   [0:0] xor_ln26_208_fu_1119_p2;
wire   [0:0] and_ln26_103_fu_1125_p2;
wire   [0:0] xor_ln26_209_fu_1131_p2;
wire   [21:0] select_ln26_208_fu_1137_p3;
wire  signed [21:0] trunc_ln18_39_fu_239_p4;
wire  signed [21:0] trunc_ln19_39_fu_393_p4;
wire  signed [22:0] sext_ln26_211_fu_1157_p1;
wire  signed [22:0] sext_ln26_210_fu_1153_p1;
wire   [22:0] add_ln26_211_fu_1167_p2;
wire   [21:0] add_ln26_210_fu_1161_p2;
wire   [0:0] tmp_6143_fu_1173_p3;
wire   [0:0] tmp_6144_fu_1181_p3;
wire   [0:0] xor_ln26_210_fu_1189_p2;
wire   [0:0] and_ln26_104_fu_1195_p2;
wire   [0:0] xor_ln26_211_fu_1201_p2;
wire   [21:0] select_ln26_210_fu_1207_p3;
wire  signed [21:0] trunc_ln18_40_fu_249_p4;
wire  signed [21:0] trunc_ln19_40_fu_403_p4;
wire  signed [22:0] sext_ln26_213_fu_1227_p1;
wire  signed [22:0] sext_ln26_212_fu_1223_p1;
wire   [22:0] add_ln26_213_fu_1237_p2;
wire   [21:0] add_ln26_212_fu_1231_p2;
wire   [0:0] tmp_6145_fu_1243_p3;
wire   [0:0] tmp_6146_fu_1251_p3;
wire   [0:0] xor_ln26_212_fu_1259_p2;
wire   [0:0] and_ln26_105_fu_1265_p2;
wire   [0:0] xor_ln26_213_fu_1271_p2;
wire   [21:0] select_ln26_212_fu_1277_p3;
wire  signed [21:0] trunc_ln18_41_fu_259_p4;
wire  signed [21:0] trunc_ln19_41_fu_413_p4;
wire  signed [22:0] sext_ln26_215_fu_1297_p1;
wire  signed [22:0] sext_ln26_214_fu_1293_p1;
wire   [22:0] add_ln26_215_fu_1307_p2;
wire   [21:0] add_ln26_214_fu_1301_p2;
wire   [0:0] tmp_6147_fu_1313_p3;
wire   [0:0] tmp_6148_fu_1321_p3;
wire   [0:0] xor_ln26_214_fu_1329_p2;
wire   [0:0] and_ln26_106_fu_1335_p2;
wire   [0:0] xor_ln26_215_fu_1341_p2;
wire   [21:0] select_ln26_214_fu_1347_p3;
wire  signed [21:0] trunc_ln18_42_fu_269_p4;
wire  signed [21:0] trunc_ln19_42_fu_423_p4;
wire  signed [22:0] sext_ln26_217_fu_1367_p1;
wire  signed [22:0] sext_ln26_216_fu_1363_p1;
wire   [22:0] add_ln26_217_fu_1377_p2;
wire   [21:0] add_ln26_216_fu_1371_p2;
wire   [0:0] tmp_6149_fu_1383_p3;
wire   [0:0] tmp_6150_fu_1391_p3;
wire   [0:0] xor_ln26_216_fu_1399_p2;
wire   [0:0] and_ln26_107_fu_1405_p2;
wire   [0:0] xor_ln26_217_fu_1411_p2;
wire   [21:0] select_ln26_216_fu_1417_p3;
wire  signed [21:0] trunc_ln18_43_fu_279_p4;
wire  signed [21:0] trunc_ln19_43_fu_433_p4;
wire  signed [22:0] sext_ln26_219_fu_1437_p1;
wire  signed [22:0] sext_ln26_218_fu_1433_p1;
wire   [22:0] add_ln26_219_fu_1447_p2;
wire   [21:0] add_ln26_218_fu_1441_p2;
wire   [0:0] tmp_6151_fu_1453_p3;
wire   [0:0] tmp_6152_fu_1461_p3;
wire   [0:0] xor_ln26_218_fu_1469_p2;
wire   [0:0] and_ln26_108_fu_1475_p2;
wire   [0:0] xor_ln26_219_fu_1481_p2;
wire   [21:0] select_ln26_218_fu_1487_p3;
wire  signed [21:0] trunc_ln18_44_fu_289_p4;
wire  signed [21:0] trunc_ln19_44_fu_443_p4;
wire  signed [22:0] sext_ln26_221_fu_1507_p1;
wire  signed [22:0] sext_ln26_220_fu_1503_p1;
wire   [22:0] add_ln26_221_fu_1517_p2;
wire   [21:0] add_ln26_220_fu_1511_p2;
wire   [0:0] tmp_6153_fu_1523_p3;
wire   [0:0] tmp_6154_fu_1531_p3;
wire   [0:0] xor_ln26_220_fu_1539_p2;
wire   [0:0] and_ln26_109_fu_1545_p2;
wire   [0:0] xor_ln26_221_fu_1551_p2;
wire   [21:0] select_ln26_220_fu_1557_p3;
wire   [21:0] select_ln26_221_fu_1565_p3;
wire   [21:0] select_ln26_219_fu_1495_p3;
wire   [21:0] select_ln26_217_fu_1425_p3;
wire   [21:0] select_ln26_215_fu_1355_p3;
wire   [21:0] select_ln26_213_fu_1285_p3;
wire   [21:0] select_ln26_211_fu_1215_p3;
wire   [21:0] select_ln26_209_fu_1145_p3;
wire   [21:0] select_ln26_207_fu_1075_p3;
wire   [21:0] select_ln26_205_fu_1005_p3;
wire   [21:0] select_ln26_203_fu_935_p3;
wire   [21:0] select_ln26_201_fu_865_p3;
wire   [21:0] select_ln26_199_fu_795_p3;
wire   [21:0] select_ln26_197_fu_725_p3;
wire   [21:0] select_ln26_195_fu_655_p3;
wire   [21:0] select_ln26_193_fu_585_p3;
wire   [21:0] select_ln26_191_fu_515_p3;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
#0 i1_fu_114 = 10'd0;
end

resnet8_resource_fifo_opt_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        i1_fu_114 <= i_fu_1610_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln15_fu_1616_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i1_load = 10'd0;
    end else begin
        ap_sig_allocacmp_i1_load = i1_fu_114;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer10_out_blk_n = layer10_out_full_n;
    end else begin
        layer10_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        layer10_out_write = 1'b1;
    end else begin
        layer10_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer32_cpy2_blk_n = layer32_cpy2_empty_n;
    end else begin
        layer32_cpy2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        layer32_cpy2_read = 1'b1;
    end else begin
        layer32_cpy2_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer9_out_blk_n = layer9_out_empty_n;
    end else begin
        layer9_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        layer9_out_read = 1'b1;
    end else begin
        layer9_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln26_191_fu_467_p2 = ($signed(sext_ln26_191_fu_457_p1) + $signed(sext_ln26_fu_453_p1));

assign add_ln26_192_fu_531_p2 = ($signed(trunc_ln19_s_fu_303_p4) + $signed(trunc_ln18_s_fu_149_p4));

assign add_ln26_193_fu_537_p2 = ($signed(sext_ln26_193_fu_527_p1) + $signed(sext_ln26_192_fu_523_p1));

assign add_ln26_194_fu_601_p2 = ($signed(trunc_ln19_31_fu_313_p4) + $signed(trunc_ln18_31_fu_159_p4));

assign add_ln26_195_fu_607_p2 = ($signed(sext_ln26_195_fu_597_p1) + $signed(sext_ln26_194_fu_593_p1));

assign add_ln26_196_fu_671_p2 = ($signed(trunc_ln19_32_fu_323_p4) + $signed(trunc_ln18_32_fu_169_p4));

assign add_ln26_197_fu_677_p2 = ($signed(sext_ln26_197_fu_667_p1) + $signed(sext_ln26_196_fu_663_p1));

assign add_ln26_198_fu_741_p2 = ($signed(trunc_ln19_33_fu_333_p4) + $signed(trunc_ln18_33_fu_179_p4));

assign add_ln26_199_fu_747_p2 = ($signed(sext_ln26_199_fu_737_p1) + $signed(sext_ln26_198_fu_733_p1));

assign add_ln26_200_fu_811_p2 = ($signed(trunc_ln19_34_fu_343_p4) + $signed(trunc_ln18_34_fu_189_p4));

assign add_ln26_201_fu_817_p2 = ($signed(sext_ln26_201_fu_807_p1) + $signed(sext_ln26_200_fu_803_p1));

assign add_ln26_202_fu_881_p2 = ($signed(trunc_ln19_35_fu_353_p4) + $signed(trunc_ln18_35_fu_199_p4));

assign add_ln26_203_fu_887_p2 = ($signed(sext_ln26_203_fu_877_p1) + $signed(sext_ln26_202_fu_873_p1));

assign add_ln26_204_fu_951_p2 = ($signed(trunc_ln19_36_fu_363_p4) + $signed(trunc_ln18_36_fu_209_p4));

assign add_ln26_205_fu_957_p2 = ($signed(sext_ln26_205_fu_947_p1) + $signed(sext_ln26_204_fu_943_p1));

assign add_ln26_206_fu_1021_p2 = ($signed(trunc_ln19_37_fu_373_p4) + $signed(trunc_ln18_37_fu_219_p4));

assign add_ln26_207_fu_1027_p2 = ($signed(sext_ln26_207_fu_1017_p1) + $signed(sext_ln26_206_fu_1013_p1));

assign add_ln26_208_fu_1091_p2 = ($signed(trunc_ln19_38_fu_383_p4) + $signed(trunc_ln18_38_fu_229_p4));

assign add_ln26_209_fu_1097_p2 = ($signed(sext_ln26_209_fu_1087_p1) + $signed(sext_ln26_208_fu_1083_p1));

assign add_ln26_210_fu_1161_p2 = ($signed(trunc_ln19_39_fu_393_p4) + $signed(trunc_ln18_39_fu_239_p4));

assign add_ln26_211_fu_1167_p2 = ($signed(sext_ln26_211_fu_1157_p1) + $signed(sext_ln26_210_fu_1153_p1));

assign add_ln26_212_fu_1231_p2 = ($signed(trunc_ln19_40_fu_403_p4) + $signed(trunc_ln18_40_fu_249_p4));

assign add_ln26_213_fu_1237_p2 = ($signed(sext_ln26_213_fu_1227_p1) + $signed(sext_ln26_212_fu_1223_p1));

assign add_ln26_214_fu_1301_p2 = ($signed(trunc_ln19_41_fu_413_p4) + $signed(trunc_ln18_41_fu_259_p4));

assign add_ln26_215_fu_1307_p2 = ($signed(sext_ln26_215_fu_1297_p1) + $signed(sext_ln26_214_fu_1293_p1));

assign add_ln26_216_fu_1371_p2 = ($signed(trunc_ln19_42_fu_423_p4) + $signed(trunc_ln18_42_fu_269_p4));

assign add_ln26_217_fu_1377_p2 = ($signed(sext_ln26_217_fu_1367_p1) + $signed(sext_ln26_216_fu_1363_p1));

assign add_ln26_218_fu_1441_p2 = ($signed(trunc_ln19_43_fu_433_p4) + $signed(trunc_ln18_43_fu_279_p4));

assign add_ln26_219_fu_1447_p2 = ($signed(sext_ln26_219_fu_1437_p1) + $signed(sext_ln26_218_fu_1433_p1));

assign add_ln26_220_fu_1511_p2 = ($signed(trunc_ln19_44_fu_443_p4) + $signed(trunc_ln18_44_fu_289_p4));

assign add_ln26_221_fu_1517_p2 = ($signed(sext_ln26_221_fu_1507_p1) + $signed(sext_ln26_220_fu_1503_p1));

assign add_ln26_fu_461_p2 = ($signed(trunc_ln19_fu_299_p1) + $signed(trunc_ln18_fu_145_p1));

assign and_ln26_100_fu_915_p2 = (xor_ln26_202_fu_909_p2 & tmp_6136_fu_901_p3);

assign and_ln26_101_fu_985_p2 = (xor_ln26_204_fu_979_p2 & tmp_6138_fu_971_p3);

assign and_ln26_102_fu_1055_p2 = (xor_ln26_206_fu_1049_p2 & tmp_6140_fu_1041_p3);

assign and_ln26_103_fu_1125_p2 = (xor_ln26_208_fu_1119_p2 & tmp_6142_fu_1111_p3);

assign and_ln26_104_fu_1195_p2 = (xor_ln26_210_fu_1189_p2 & tmp_6144_fu_1181_p3);

assign and_ln26_105_fu_1265_p2 = (xor_ln26_212_fu_1259_p2 & tmp_6146_fu_1251_p3);

assign and_ln26_106_fu_1335_p2 = (xor_ln26_214_fu_1329_p2 & tmp_6148_fu_1321_p3);

assign and_ln26_107_fu_1405_p2 = (xor_ln26_216_fu_1399_p2 & tmp_6150_fu_1391_p3);

assign and_ln26_108_fu_1475_p2 = (xor_ln26_218_fu_1469_p2 & tmp_6152_fu_1461_p3);

assign and_ln26_109_fu_1545_p2 = (xor_ln26_220_fu_1539_p2 & tmp_6154_fu_1531_p3);

assign and_ln26_95_fu_565_p2 = (xor_ln26_192_fu_559_p2 & tmp_6126_fu_551_p3);

assign and_ln26_96_fu_635_p2 = (xor_ln26_194_fu_629_p2 & tmp_6128_fu_621_p3);

assign and_ln26_97_fu_705_p2 = (xor_ln26_196_fu_699_p2 & tmp_6130_fu_691_p3);

assign and_ln26_98_fu_775_p2 = (xor_ln26_198_fu_769_p2 & tmp_6132_fu_761_p3);

assign and_ln26_99_fu_845_p2 = (xor_ln26_200_fu_839_p2 & tmp_6134_fu_831_p3);

assign and_ln26_fu_495_p2 = (xor_ln26_fu_489_p2 & tmp_6124_fu_481_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (layer10_out_full_n == 1'b0) | (layer32_cpy2_empty_n == 1'b0) | (layer9_out_empty_n == 1'b0) | (ap_start_int == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign i_fu_1610_p2 = (ap_sig_allocacmp_i1_load + 10'd1);

assign icmp_ln15_fu_1616_p2 = ((ap_sig_allocacmp_i1_load == 10'd1023) ? 1'b1 : 1'b0);

assign layer10_out_din = {{{{{{{{{{{{{{{{select_ln26_221_fu_1565_p3}, {select_ln26_219_fu_1495_p3}}, {select_ln26_217_fu_1425_p3}}, {select_ln26_215_fu_1355_p3}}, {select_ln26_213_fu_1285_p3}}, {select_ln26_211_fu_1215_p3}}, {select_ln26_209_fu_1145_p3}}, {select_ln26_207_fu_1075_p3}}, {select_ln26_205_fu_1005_p3}}, {select_ln26_203_fu_935_p3}}, {select_ln26_201_fu_865_p3}}, {select_ln26_199_fu_795_p3}}, {select_ln26_197_fu_725_p3}}, {select_ln26_195_fu_655_p3}}, {select_ln26_193_fu_585_p3}}, {select_ln26_191_fu_515_p3}};

assign select_ln26_191_fu_515_p3 = ((xor_ln26_191_fu_501_p2[0:0] == 1'b1) ? select_ln26_fu_507_p3 : add_ln26_fu_461_p2);

assign select_ln26_192_fu_577_p3 = ((and_ln26_95_fu_565_p2[0:0] == 1'b1) ? 22'd2097151 : 22'd2097152);

assign select_ln26_193_fu_585_p3 = ((xor_ln26_193_fu_571_p2[0:0] == 1'b1) ? select_ln26_192_fu_577_p3 : add_ln26_192_fu_531_p2);

assign select_ln26_194_fu_647_p3 = ((and_ln26_96_fu_635_p2[0:0] == 1'b1) ? 22'd2097151 : 22'd2097152);

assign select_ln26_195_fu_655_p3 = ((xor_ln26_195_fu_641_p2[0:0] == 1'b1) ? select_ln26_194_fu_647_p3 : add_ln26_194_fu_601_p2);

assign select_ln26_196_fu_717_p3 = ((and_ln26_97_fu_705_p2[0:0] == 1'b1) ? 22'd2097151 : 22'd2097152);

assign select_ln26_197_fu_725_p3 = ((xor_ln26_197_fu_711_p2[0:0] == 1'b1) ? select_ln26_196_fu_717_p3 : add_ln26_196_fu_671_p2);

assign select_ln26_198_fu_787_p3 = ((and_ln26_98_fu_775_p2[0:0] == 1'b1) ? 22'd2097151 : 22'd2097152);

assign select_ln26_199_fu_795_p3 = ((xor_ln26_199_fu_781_p2[0:0] == 1'b1) ? select_ln26_198_fu_787_p3 : add_ln26_198_fu_741_p2);

assign select_ln26_200_fu_857_p3 = ((and_ln26_99_fu_845_p2[0:0] == 1'b1) ? 22'd2097151 : 22'd2097152);

assign select_ln26_201_fu_865_p3 = ((xor_ln26_201_fu_851_p2[0:0] == 1'b1) ? select_ln26_200_fu_857_p3 : add_ln26_200_fu_811_p2);

assign select_ln26_202_fu_927_p3 = ((and_ln26_100_fu_915_p2[0:0] == 1'b1) ? 22'd2097151 : 22'd2097152);

assign select_ln26_203_fu_935_p3 = ((xor_ln26_203_fu_921_p2[0:0] == 1'b1) ? select_ln26_202_fu_927_p3 : add_ln26_202_fu_881_p2);

assign select_ln26_204_fu_997_p3 = ((and_ln26_101_fu_985_p2[0:0] == 1'b1) ? 22'd2097151 : 22'd2097152);

assign select_ln26_205_fu_1005_p3 = ((xor_ln26_205_fu_991_p2[0:0] == 1'b1) ? select_ln26_204_fu_997_p3 : add_ln26_204_fu_951_p2);

assign select_ln26_206_fu_1067_p3 = ((and_ln26_102_fu_1055_p2[0:0] == 1'b1) ? 22'd2097151 : 22'd2097152);

assign select_ln26_207_fu_1075_p3 = ((xor_ln26_207_fu_1061_p2[0:0] == 1'b1) ? select_ln26_206_fu_1067_p3 : add_ln26_206_fu_1021_p2);

assign select_ln26_208_fu_1137_p3 = ((and_ln26_103_fu_1125_p2[0:0] == 1'b1) ? 22'd2097151 : 22'd2097152);

assign select_ln26_209_fu_1145_p3 = ((xor_ln26_209_fu_1131_p2[0:0] == 1'b1) ? select_ln26_208_fu_1137_p3 : add_ln26_208_fu_1091_p2);

assign select_ln26_210_fu_1207_p3 = ((and_ln26_104_fu_1195_p2[0:0] == 1'b1) ? 22'd2097151 : 22'd2097152);

assign select_ln26_211_fu_1215_p3 = ((xor_ln26_211_fu_1201_p2[0:0] == 1'b1) ? select_ln26_210_fu_1207_p3 : add_ln26_210_fu_1161_p2);

assign select_ln26_212_fu_1277_p3 = ((and_ln26_105_fu_1265_p2[0:0] == 1'b1) ? 22'd2097151 : 22'd2097152);

assign select_ln26_213_fu_1285_p3 = ((xor_ln26_213_fu_1271_p2[0:0] == 1'b1) ? select_ln26_212_fu_1277_p3 : add_ln26_212_fu_1231_p2);

assign select_ln26_214_fu_1347_p3 = ((and_ln26_106_fu_1335_p2[0:0] == 1'b1) ? 22'd2097151 : 22'd2097152);

assign select_ln26_215_fu_1355_p3 = ((xor_ln26_215_fu_1341_p2[0:0] == 1'b1) ? select_ln26_214_fu_1347_p3 : add_ln26_214_fu_1301_p2);

assign select_ln26_216_fu_1417_p3 = ((and_ln26_107_fu_1405_p2[0:0] == 1'b1) ? 22'd2097151 : 22'd2097152);

assign select_ln26_217_fu_1425_p3 = ((xor_ln26_217_fu_1411_p2[0:0] == 1'b1) ? select_ln26_216_fu_1417_p3 : add_ln26_216_fu_1371_p2);

assign select_ln26_218_fu_1487_p3 = ((and_ln26_108_fu_1475_p2[0:0] == 1'b1) ? 22'd2097151 : 22'd2097152);

assign select_ln26_219_fu_1495_p3 = ((xor_ln26_219_fu_1481_p2[0:0] == 1'b1) ? select_ln26_218_fu_1487_p3 : add_ln26_218_fu_1441_p2);

assign select_ln26_220_fu_1557_p3 = ((and_ln26_109_fu_1545_p2[0:0] == 1'b1) ? 22'd2097151 : 22'd2097152);

assign select_ln26_221_fu_1565_p3 = ((xor_ln26_221_fu_1551_p2[0:0] == 1'b1) ? select_ln26_220_fu_1557_p3 : add_ln26_220_fu_1511_p2);

assign select_ln26_fu_507_p3 = ((and_ln26_fu_495_p2[0:0] == 1'b1) ? 22'd2097151 : 22'd2097152);

assign sext_ln26_191_fu_457_p1 = trunc_ln19_fu_299_p1;

assign sext_ln26_192_fu_523_p1 = trunc_ln18_s_fu_149_p4;

assign sext_ln26_193_fu_527_p1 = trunc_ln19_s_fu_303_p4;

assign sext_ln26_194_fu_593_p1 = trunc_ln18_31_fu_159_p4;

assign sext_ln26_195_fu_597_p1 = trunc_ln19_31_fu_313_p4;

assign sext_ln26_196_fu_663_p1 = trunc_ln18_32_fu_169_p4;

assign sext_ln26_197_fu_667_p1 = trunc_ln19_32_fu_323_p4;

assign sext_ln26_198_fu_733_p1 = trunc_ln18_33_fu_179_p4;

assign sext_ln26_199_fu_737_p1 = trunc_ln19_33_fu_333_p4;

assign sext_ln26_200_fu_803_p1 = trunc_ln18_34_fu_189_p4;

assign sext_ln26_201_fu_807_p1 = trunc_ln19_34_fu_343_p4;

assign sext_ln26_202_fu_873_p1 = trunc_ln18_35_fu_199_p4;

assign sext_ln26_203_fu_877_p1 = trunc_ln19_35_fu_353_p4;

assign sext_ln26_204_fu_943_p1 = trunc_ln18_36_fu_209_p4;

assign sext_ln26_205_fu_947_p1 = trunc_ln19_36_fu_363_p4;

assign sext_ln26_206_fu_1013_p1 = trunc_ln18_37_fu_219_p4;

assign sext_ln26_207_fu_1017_p1 = trunc_ln19_37_fu_373_p4;

assign sext_ln26_208_fu_1083_p1 = trunc_ln18_38_fu_229_p4;

assign sext_ln26_209_fu_1087_p1 = trunc_ln19_38_fu_383_p4;

assign sext_ln26_210_fu_1153_p1 = trunc_ln18_39_fu_239_p4;

assign sext_ln26_211_fu_1157_p1 = trunc_ln19_39_fu_393_p4;

assign sext_ln26_212_fu_1223_p1 = trunc_ln18_40_fu_249_p4;

assign sext_ln26_213_fu_1227_p1 = trunc_ln19_40_fu_403_p4;

assign sext_ln26_214_fu_1293_p1 = trunc_ln18_41_fu_259_p4;

assign sext_ln26_215_fu_1297_p1 = trunc_ln19_41_fu_413_p4;

assign sext_ln26_216_fu_1363_p1 = trunc_ln18_42_fu_269_p4;

assign sext_ln26_217_fu_1367_p1 = trunc_ln19_42_fu_423_p4;

assign sext_ln26_218_fu_1433_p1 = trunc_ln18_43_fu_279_p4;

assign sext_ln26_219_fu_1437_p1 = trunc_ln19_43_fu_433_p4;

assign sext_ln26_220_fu_1503_p1 = trunc_ln18_44_fu_289_p4;

assign sext_ln26_221_fu_1507_p1 = trunc_ln19_44_fu_443_p4;

assign sext_ln26_fu_453_p1 = trunc_ln18_fu_145_p1;

assign start_out = real_start;

assign tmp_6124_fu_481_p3 = add_ln26_fu_461_p2[32'd21];

assign tmp_6125_fu_543_p3 = add_ln26_193_fu_537_p2[32'd22];

assign tmp_6126_fu_551_p3 = add_ln26_192_fu_531_p2[32'd21];

assign tmp_6127_fu_613_p3 = add_ln26_195_fu_607_p2[32'd22];

assign tmp_6128_fu_621_p3 = add_ln26_194_fu_601_p2[32'd21];

assign tmp_6129_fu_683_p3 = add_ln26_197_fu_677_p2[32'd22];

assign tmp_6130_fu_691_p3 = add_ln26_196_fu_671_p2[32'd21];

assign tmp_6131_fu_753_p3 = add_ln26_199_fu_747_p2[32'd22];

assign tmp_6132_fu_761_p3 = add_ln26_198_fu_741_p2[32'd21];

assign tmp_6133_fu_823_p3 = add_ln26_201_fu_817_p2[32'd22];

assign tmp_6134_fu_831_p3 = add_ln26_200_fu_811_p2[32'd21];

assign tmp_6135_fu_893_p3 = add_ln26_203_fu_887_p2[32'd22];

assign tmp_6136_fu_901_p3 = add_ln26_202_fu_881_p2[32'd21];

assign tmp_6137_fu_963_p3 = add_ln26_205_fu_957_p2[32'd22];

assign tmp_6138_fu_971_p3 = add_ln26_204_fu_951_p2[32'd21];

assign tmp_6139_fu_1033_p3 = add_ln26_207_fu_1027_p2[32'd22];

assign tmp_6140_fu_1041_p3 = add_ln26_206_fu_1021_p2[32'd21];

assign tmp_6141_fu_1103_p3 = add_ln26_209_fu_1097_p2[32'd22];

assign tmp_6142_fu_1111_p3 = add_ln26_208_fu_1091_p2[32'd21];

assign tmp_6143_fu_1173_p3 = add_ln26_211_fu_1167_p2[32'd22];

assign tmp_6144_fu_1181_p3 = add_ln26_210_fu_1161_p2[32'd21];

assign tmp_6145_fu_1243_p3 = add_ln26_213_fu_1237_p2[32'd22];

assign tmp_6146_fu_1251_p3 = add_ln26_212_fu_1231_p2[32'd21];

assign tmp_6147_fu_1313_p3 = add_ln26_215_fu_1307_p2[32'd22];

assign tmp_6148_fu_1321_p3 = add_ln26_214_fu_1301_p2[32'd21];

assign tmp_6149_fu_1383_p3 = add_ln26_217_fu_1377_p2[32'd22];

assign tmp_6150_fu_1391_p3 = add_ln26_216_fu_1371_p2[32'd21];

assign tmp_6151_fu_1453_p3 = add_ln26_219_fu_1447_p2[32'd22];

assign tmp_6152_fu_1461_p3 = add_ln26_218_fu_1441_p2[32'd21];

assign tmp_6153_fu_1523_p3 = add_ln26_221_fu_1517_p2[32'd22];

assign tmp_6154_fu_1531_p3 = add_ln26_220_fu_1511_p2[32'd21];

assign tmp_fu_473_p3 = add_ln26_191_fu_467_p2[32'd22];

assign trunc_ln18_31_fu_159_p4 = {{layer9_out_dout[65:44]}};

assign trunc_ln18_32_fu_169_p4 = {{layer9_out_dout[87:66]}};

assign trunc_ln18_33_fu_179_p4 = {{layer9_out_dout[109:88]}};

assign trunc_ln18_34_fu_189_p4 = {{layer9_out_dout[131:110]}};

assign trunc_ln18_35_fu_199_p4 = {{layer9_out_dout[153:132]}};

assign trunc_ln18_36_fu_209_p4 = {{layer9_out_dout[175:154]}};

assign trunc_ln18_37_fu_219_p4 = {{layer9_out_dout[197:176]}};

assign trunc_ln18_38_fu_229_p4 = {{layer9_out_dout[219:198]}};

assign trunc_ln18_39_fu_239_p4 = {{layer9_out_dout[241:220]}};

assign trunc_ln18_40_fu_249_p4 = {{layer9_out_dout[263:242]}};

assign trunc_ln18_41_fu_259_p4 = {{layer9_out_dout[285:264]}};

assign trunc_ln18_42_fu_269_p4 = {{layer9_out_dout[307:286]}};

assign trunc_ln18_43_fu_279_p4 = {{layer9_out_dout[329:308]}};

assign trunc_ln18_44_fu_289_p4 = {{layer9_out_dout[351:330]}};

assign trunc_ln18_fu_145_p1 = layer9_out_dout[21:0];

assign trunc_ln18_s_fu_149_p4 = {{layer9_out_dout[43:22]}};

assign trunc_ln19_31_fu_313_p4 = {{layer32_cpy2_dout[65:44]}};

assign trunc_ln19_32_fu_323_p4 = {{layer32_cpy2_dout[87:66]}};

assign trunc_ln19_33_fu_333_p4 = {{layer32_cpy2_dout[109:88]}};

assign trunc_ln19_34_fu_343_p4 = {{layer32_cpy2_dout[131:110]}};

assign trunc_ln19_35_fu_353_p4 = {{layer32_cpy2_dout[153:132]}};

assign trunc_ln19_36_fu_363_p4 = {{layer32_cpy2_dout[175:154]}};

assign trunc_ln19_37_fu_373_p4 = {{layer32_cpy2_dout[197:176]}};

assign trunc_ln19_38_fu_383_p4 = {{layer32_cpy2_dout[219:198]}};

assign trunc_ln19_39_fu_393_p4 = {{layer32_cpy2_dout[241:220]}};

assign trunc_ln19_40_fu_403_p4 = {{layer32_cpy2_dout[263:242]}};

assign trunc_ln19_41_fu_413_p4 = {{layer32_cpy2_dout[285:264]}};

assign trunc_ln19_42_fu_423_p4 = {{layer32_cpy2_dout[307:286]}};

assign trunc_ln19_43_fu_433_p4 = {{layer32_cpy2_dout[329:308]}};

assign trunc_ln19_44_fu_443_p4 = {{layer32_cpy2_dout[351:330]}};

assign trunc_ln19_fu_299_p1 = layer32_cpy2_dout[21:0];

assign trunc_ln19_s_fu_303_p4 = {{layer32_cpy2_dout[43:22]}};

assign xor_ln26_191_fu_501_p2 = (tmp_fu_473_p3 ^ tmp_6124_fu_481_p3);

assign xor_ln26_192_fu_559_p2 = (tmp_6125_fu_543_p3 ^ 1'd1);

assign xor_ln26_193_fu_571_p2 = (tmp_6126_fu_551_p3 ^ tmp_6125_fu_543_p3);

assign xor_ln26_194_fu_629_p2 = (tmp_6127_fu_613_p3 ^ 1'd1);

assign xor_ln26_195_fu_641_p2 = (tmp_6128_fu_621_p3 ^ tmp_6127_fu_613_p3);

assign xor_ln26_196_fu_699_p2 = (tmp_6129_fu_683_p3 ^ 1'd1);

assign xor_ln26_197_fu_711_p2 = (tmp_6130_fu_691_p3 ^ tmp_6129_fu_683_p3);

assign xor_ln26_198_fu_769_p2 = (tmp_6131_fu_753_p3 ^ 1'd1);

assign xor_ln26_199_fu_781_p2 = (tmp_6132_fu_761_p3 ^ tmp_6131_fu_753_p3);

assign xor_ln26_200_fu_839_p2 = (tmp_6133_fu_823_p3 ^ 1'd1);

assign xor_ln26_201_fu_851_p2 = (tmp_6134_fu_831_p3 ^ tmp_6133_fu_823_p3);

assign xor_ln26_202_fu_909_p2 = (tmp_6135_fu_893_p3 ^ 1'd1);

assign xor_ln26_203_fu_921_p2 = (tmp_6136_fu_901_p3 ^ tmp_6135_fu_893_p3);

assign xor_ln26_204_fu_979_p2 = (tmp_6137_fu_963_p3 ^ 1'd1);

assign xor_ln26_205_fu_991_p2 = (tmp_6138_fu_971_p3 ^ tmp_6137_fu_963_p3);

assign xor_ln26_206_fu_1049_p2 = (tmp_6139_fu_1033_p3 ^ 1'd1);

assign xor_ln26_207_fu_1061_p2 = (tmp_6140_fu_1041_p3 ^ tmp_6139_fu_1033_p3);

assign xor_ln26_208_fu_1119_p2 = (tmp_6141_fu_1103_p3 ^ 1'd1);

assign xor_ln26_209_fu_1131_p2 = (tmp_6142_fu_1111_p3 ^ tmp_6141_fu_1103_p3);

assign xor_ln26_210_fu_1189_p2 = (tmp_6143_fu_1173_p3 ^ 1'd1);

assign xor_ln26_211_fu_1201_p2 = (tmp_6144_fu_1181_p3 ^ tmp_6143_fu_1173_p3);

assign xor_ln26_212_fu_1259_p2 = (tmp_6145_fu_1243_p3 ^ 1'd1);

assign xor_ln26_213_fu_1271_p2 = (tmp_6146_fu_1251_p3 ^ tmp_6145_fu_1243_p3);

assign xor_ln26_214_fu_1329_p2 = (tmp_6147_fu_1313_p3 ^ 1'd1);

assign xor_ln26_215_fu_1341_p2 = (tmp_6148_fu_1321_p3 ^ tmp_6147_fu_1313_p3);

assign xor_ln26_216_fu_1399_p2 = (tmp_6149_fu_1383_p3 ^ 1'd1);

assign xor_ln26_217_fu_1411_p2 = (tmp_6150_fu_1391_p3 ^ tmp_6149_fu_1383_p3);

assign xor_ln26_218_fu_1469_p2 = (tmp_6151_fu_1453_p3 ^ 1'd1);

assign xor_ln26_219_fu_1481_p2 = (tmp_6152_fu_1461_p3 ^ tmp_6151_fu_1453_p3);

assign xor_ln26_220_fu_1539_p2 = (tmp_6153_fu_1523_p3 ^ 1'd1);

assign xor_ln26_221_fu_1551_p2 = (tmp_6154_fu_1531_p3 ^ tmp_6153_fu_1523_p3);

assign xor_ln26_fu_489_p2 = (tmp_fu_473_p3 ^ 1'd1);

endmodule //resnet8_resource_fifo_opt_add_array_array_array_ap_fixed_22_12_4_0_0_16u_config10_s
