// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module resnet8_resource_fifo_opt_conv_2d_cl_array_array_ap_fixed_22_12_4_0_0_32u_config15_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer39_out_dout,
        layer39_out_empty_n,
        layer39_out_read,
        layer39_out_num_data_valid,
        layer39_out_fifo_cap,
        layer15_out_din,
        layer15_out_full_n,
        layer15_out_write,
        layer15_out_num_data_valid,
        layer15_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [703:0] layer39_out_dout;
input   layer39_out_empty_n;
output   layer39_out_read;
input  [6:0] layer39_out_num_data_valid;
input  [6:0] layer39_out_fifo_cap;
output  [703:0] layer15_out_din;
input   layer15_out_full_n;
output   layer15_out_write;
input  [1:0] layer15_out_num_data_valid;
input  [1:0] layer15_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer39_out_read;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer39_out_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln52_fu_1644_p2;
wire   [21:0] trunc_ln58_fu_1656_p1;
reg   [21:0] trunc_ln58_reg_2017;
reg    ap_block_state2;
reg   [21:0] trunc_ln58_s_reg_2022;
reg   [21:0] trunc_ln58_591_reg_2027;
reg   [21:0] trunc_ln58_592_reg_2032;
reg   [21:0] trunc_ln58_593_reg_2037;
reg   [21:0] trunc_ln58_594_reg_2042;
reg   [21:0] trunc_ln58_595_reg_2047;
reg   [21:0] trunc_ln58_596_reg_2052;
reg   [21:0] trunc_ln58_597_reg_2057;
reg   [21:0] trunc_ln58_598_reg_2062;
reg   [21:0] trunc_ln58_599_reg_2067;
reg   [21:0] trunc_ln58_600_reg_2072;
reg   [21:0] trunc_ln58_601_reg_2077;
reg   [21:0] trunc_ln58_602_reg_2082;
reg   [21:0] trunc_ln58_603_reg_2087;
reg   [21:0] trunc_ln58_604_reg_2092;
reg   [21:0] trunc_ln58_605_reg_2097;
reg   [21:0] trunc_ln58_606_reg_2102;
reg   [21:0] trunc_ln58_607_reg_2107;
reg   [21:0] trunc_ln58_608_reg_2112;
reg   [21:0] trunc_ln58_609_reg_2117;
reg   [21:0] trunc_ln58_610_reg_2122;
reg   [21:0] trunc_ln58_611_reg_2127;
reg   [21:0] trunc_ln58_612_reg_2132;
reg   [21:0] trunc_ln58_613_reg_2137;
reg   [21:0] trunc_ln58_614_reg_2142;
reg   [21:0] trunc_ln58_615_reg_2147;
reg   [21:0] trunc_ln58_616_reg_2152;
reg   [21:0] trunc_ln58_617_reg_2157;
reg   [21:0] trunc_ln58_618_reg_2162;
reg   [21:0] trunc_ln58_619_reg_2167;
reg   [21:0] trunc_ln58_620_reg_2172;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_32u_config15_s_fu_884_ap_start;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_32u_config15_s_fu_884_ap_done;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_32u_config15_s_fu_884_ap_idle;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_32u_config15_s_fu_884_ap_ready;
wire   [703:0] grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_32u_config15_s_fu_884_layer15_out_din;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_32u_config15_s_fu_884_layer15_out_write;
reg    grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_32u_config15_s_fu_884_ap_start_reg;
reg    ap_block_state2_ignore_call35;
wire    ap_CS_fsm_state3;
reg   [8:0] indvar_flatten_fu_874;
wire   [8:0] add_ln52_fu_1650_p2;
reg    ap_block_state1;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_32u_config15_s_fu_884_ap_start_reg = 1'b0;
#0 indvar_flatten_fu_874 = 9'd0;
end

resnet8_resource_fifo_opt_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_32u_config15_s grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_32u_config15_s_fu_884(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_32u_config15_s_fu_884_ap_start),
    .ap_done(grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_32u_config15_s_fu_884_ap_done),
    .ap_idle(grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_32u_config15_s_fu_884_ap_idle),
    .ap_ready(grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_32u_config15_s_fu_884_ap_ready),
    .p_read(trunc_ln58_reg_2017),
    .p_read1(trunc_ln58_s_reg_2022),
    .p_read2(trunc_ln58_591_reg_2027),
    .p_read3(trunc_ln58_592_reg_2032),
    .p_read4(trunc_ln58_593_reg_2037),
    .p_read5(trunc_ln58_594_reg_2042),
    .p_read6(trunc_ln58_595_reg_2047),
    .p_read7(trunc_ln58_596_reg_2052),
    .p_read8(trunc_ln58_597_reg_2057),
    .p_read9(trunc_ln58_598_reg_2062),
    .p_read10(trunc_ln58_599_reg_2067),
    .p_read11(trunc_ln58_600_reg_2072),
    .p_read12(trunc_ln58_601_reg_2077),
    .p_read13(trunc_ln58_602_reg_2082),
    .p_read14(trunc_ln58_603_reg_2087),
    .p_read15(trunc_ln58_604_reg_2092),
    .p_read16(trunc_ln58_605_reg_2097),
    .p_read17(trunc_ln58_606_reg_2102),
    .p_read18(trunc_ln58_607_reg_2107),
    .p_read19(trunc_ln58_608_reg_2112),
    .p_read20(trunc_ln58_609_reg_2117),
    .p_read21(trunc_ln58_610_reg_2122),
    .p_read22(trunc_ln58_611_reg_2127),
    .p_read23(trunc_ln58_612_reg_2132),
    .p_read24(trunc_ln58_613_reg_2137),
    .p_read25(trunc_ln58_614_reg_2142),
    .p_read26(trunc_ln58_615_reg_2147),
    .p_read27(trunc_ln58_616_reg_2152),
    .p_read28(trunc_ln58_617_reg_2157),
    .p_read29(trunc_ln58_618_reg_2162),
    .p_read30(trunc_ln58_619_reg_2167),
    .p_read31(trunc_ln58_620_reg_2172),
    .layer15_out_din(grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_32u_config15_s_fu_884_layer15_out_din),
    .layer15_out_full_n(layer15_out_full_n),
    .layer15_out_write(grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_32u_config15_s_fu_884_layer15_out_write),
    .layer15_out_num_data_valid(2'd0),
    .layer15_out_fifo_cap(2'd0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_1644_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_32u_config15_s_fu_884_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state2_ignore_call35) & (icmp_ln52_fu_1644_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_32u_config15_s_fu_884_ap_start_reg <= 1'b1;
        end else if ((grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_32u_config15_s_fu_884_ap_ready == 1'b1)) begin
            grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_32u_config15_s_fu_884_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_fu_874 <= 9'd0;
    end else if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_1644_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        indvar_flatten_fu_874 <= add_ln52_fu_1650_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
        trunc_ln58_591_reg_2027 <= {{layer39_out_dout[65:44]}};
        trunc_ln58_592_reg_2032 <= {{layer39_out_dout[87:66]}};
        trunc_ln58_593_reg_2037 <= {{layer39_out_dout[109:88]}};
        trunc_ln58_594_reg_2042 <= {{layer39_out_dout[131:110]}};
        trunc_ln58_595_reg_2047 <= {{layer39_out_dout[153:132]}};
        trunc_ln58_596_reg_2052 <= {{layer39_out_dout[175:154]}};
        trunc_ln58_597_reg_2057 <= {{layer39_out_dout[197:176]}};
        trunc_ln58_598_reg_2062 <= {{layer39_out_dout[219:198]}};
        trunc_ln58_599_reg_2067 <= {{layer39_out_dout[241:220]}};
        trunc_ln58_600_reg_2072 <= {{layer39_out_dout[263:242]}};
        trunc_ln58_601_reg_2077 <= {{layer39_out_dout[285:264]}};
        trunc_ln58_602_reg_2082 <= {{layer39_out_dout[307:286]}};
        trunc_ln58_603_reg_2087 <= {{layer39_out_dout[329:308]}};
        trunc_ln58_604_reg_2092 <= {{layer39_out_dout[351:330]}};
        trunc_ln58_605_reg_2097 <= {{layer39_out_dout[373:352]}};
        trunc_ln58_606_reg_2102 <= {{layer39_out_dout[395:374]}};
        trunc_ln58_607_reg_2107 <= {{layer39_out_dout[417:396]}};
        trunc_ln58_608_reg_2112 <= {{layer39_out_dout[439:418]}};
        trunc_ln58_609_reg_2117 <= {{layer39_out_dout[461:440]}};
        trunc_ln58_610_reg_2122 <= {{layer39_out_dout[483:462]}};
        trunc_ln58_611_reg_2127 <= {{layer39_out_dout[505:484]}};
        trunc_ln58_612_reg_2132 <= {{layer39_out_dout[527:506]}};
        trunc_ln58_613_reg_2137 <= {{layer39_out_dout[549:528]}};
        trunc_ln58_614_reg_2142 <= {{layer39_out_dout[571:550]}};
        trunc_ln58_615_reg_2147 <= {{layer39_out_dout[593:572]}};
        trunc_ln58_616_reg_2152 <= {{layer39_out_dout[615:594]}};
        trunc_ln58_617_reg_2157 <= {{layer39_out_dout[637:616]}};
        trunc_ln58_618_reg_2162 <= {{layer39_out_dout[659:638]}};
        trunc_ln58_619_reg_2167 <= {{layer39_out_dout[681:660]}};
        trunc_ln58_620_reg_2172 <= {{layer39_out_dout[703:682]}};
        trunc_ln58_reg_2017 <= trunc_ln58_fu_1656_p1;
        trunc_ln58_s_reg_2022 <= {{layer39_out_dout[43:22]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_32u_config15_s_fu_884_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_1644_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_1644_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln52_fu_1644_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer39_out_blk_n = layer39_out_empty_n;
    end else begin
        layer39_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_1644_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer39_out_read = 1'b1;
    end else begin
        layer39_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_1644_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_1644_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_32u_config15_s_fu_884_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln52_fu_1650_p2 = (indvar_flatten_fu_874 + 9'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2 = ((icmp_ln52_fu_1644_p2 == 1'd0) & (layer39_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_ignore_call35 = ((icmp_ln52_fu_1644_p2 == 1'd0) & (layer39_out_empty_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_32u_config15_s_fu_884_ap_start = grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_32u_config15_s_fu_884_ap_start_reg;

assign icmp_ln52_fu_1644_p2 = ((indvar_flatten_fu_874 == 9'd324) ? 1'b1 : 1'b0);

assign layer15_out_din = grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_32u_config15_s_fu_884_layer15_out_din;

assign layer15_out_write = grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_32u_config15_s_fu_884_layer15_out_write;

assign start_out = real_start;

assign trunc_ln58_fu_1656_p1 = layer39_out_dout[21:0];

endmodule //resnet8_resource_fifo_opt_conv_2d_cl_array_array_ap_fixed_22_12_4_0_0_32u_config15_s
