// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module resnet8_resource_fifo_opt_conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_22_12_4_0_0_16u_config8_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer37_out_dout,
        layer37_out_empty_n,
        layer37_out_read,
        layer37_out_num_data_valid,
        layer37_out_fifo_cap,
        layer8_out_din,
        layer8_out_full_n,
        layer8_out_write,
        layer8_out_num_data_valid,
        layer8_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [351:0] layer37_out_dout;
input   layer37_out_empty_n;
output   layer37_out_read;
input  [7:0] layer37_out_num_data_valid;
input  [7:0] layer37_out_fifo_cap;
output  [351:0] layer8_out_din;
input   layer8_out_full_n;
output   layer8_out_write;
input  [1:0] layer8_out_num_data_valid;
input  [1:0] layer8_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer37_out_read;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer37_out_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln52_fu_860_p2;
wire   [21:0] trunc_ln58_fu_872_p1;
reg   [21:0] trunc_ln58_reg_1057;
reg    ap_block_state2;
reg   [21:0] trunc_ln58_s_reg_1062;
reg   [21:0] trunc_ln58_499_reg_1067;
reg   [21:0] trunc_ln58_500_reg_1072;
reg   [21:0] trunc_ln58_501_reg_1077;
reg   [21:0] trunc_ln58_502_reg_1082;
reg   [21:0] trunc_ln58_503_reg_1087;
reg   [21:0] trunc_ln58_504_reg_1092;
reg   [21:0] trunc_ln58_505_reg_1097;
reg   [21:0] trunc_ln58_506_reg_1102;
reg   [21:0] trunc_ln58_507_reg_1107;
reg   [21:0] trunc_ln58_508_reg_1112;
reg   [21:0] trunc_ln58_509_reg_1117;
reg   [21:0] trunc_ln58_510_reg_1122;
reg   [21:0] trunc_ln58_511_reg_1127;
reg   [21:0] trunc_ln58_512_reg_1132;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_16u_config8_s_fu_468_ap_start;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_16u_config8_s_fu_468_ap_done;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_16u_config8_s_fu_468_ap_idle;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_16u_config8_s_fu_468_ap_ready;
wire   [351:0] grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_16u_config8_s_fu_468_layer8_out_din;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_16u_config8_s_fu_468_layer8_out_write;
reg    grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_16u_config8_s_fu_468_ap_start_reg;
reg    ap_block_state2_ignore_call19;
wire    ap_CS_fsm_state3;
reg   [10:0] indvar_flatten_fu_458;
wire   [10:0] add_ln52_fu_866_p2;
reg    ap_block_state1;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_16u_config8_s_fu_468_ap_start_reg = 1'b0;
#0 indvar_flatten_fu_458 = 11'd0;
end

resnet8_resource_fifo_opt_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_16u_config8_s grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_16u_config8_s_fu_468(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_16u_config8_s_fu_468_ap_start),
    .ap_done(grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_16u_config8_s_fu_468_ap_done),
    .ap_idle(grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_16u_config8_s_fu_468_ap_idle),
    .ap_ready(grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_16u_config8_s_fu_468_ap_ready),
    .p_read(trunc_ln58_reg_1057),
    .p_read1(trunc_ln58_s_reg_1062),
    .p_read2(trunc_ln58_499_reg_1067),
    .p_read3(trunc_ln58_500_reg_1072),
    .p_read4(trunc_ln58_501_reg_1077),
    .p_read5(trunc_ln58_502_reg_1082),
    .p_read6(trunc_ln58_503_reg_1087),
    .p_read7(trunc_ln58_504_reg_1092),
    .p_read8(trunc_ln58_505_reg_1097),
    .p_read9(trunc_ln58_506_reg_1102),
    .p_read10(trunc_ln58_507_reg_1107),
    .p_read11(trunc_ln58_508_reg_1112),
    .p_read12(trunc_ln58_509_reg_1117),
    .p_read13(trunc_ln58_510_reg_1122),
    .p_read14(trunc_ln58_511_reg_1127),
    .p_read15(trunc_ln58_512_reg_1132),
    .layer8_out_din(grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_16u_config8_s_fu_468_layer8_out_din),
    .layer8_out_full_n(layer8_out_full_n),
    .layer8_out_write(grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_16u_config8_s_fu_468_layer8_out_write),
    .layer8_out_num_data_valid(2'd0),
    .layer8_out_fifo_cap(2'd0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_860_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_16u_config8_s_fu_468_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state2_ignore_call19) & (icmp_ln52_fu_860_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_16u_config8_s_fu_468_ap_start_reg <= 1'b1;
        end else if ((grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_16u_config8_s_fu_468_ap_ready == 1'b1)) begin
            grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_16u_config8_s_fu_468_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_fu_458 <= 11'd0;
    end else if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_860_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        indvar_flatten_fu_458 <= add_ln52_fu_866_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
        trunc_ln58_499_reg_1067 <= {{layer37_out_dout[65:44]}};
        trunc_ln58_500_reg_1072 <= {{layer37_out_dout[87:66]}};
        trunc_ln58_501_reg_1077 <= {{layer37_out_dout[109:88]}};
        trunc_ln58_502_reg_1082 <= {{layer37_out_dout[131:110]}};
        trunc_ln58_503_reg_1087 <= {{layer37_out_dout[153:132]}};
        trunc_ln58_504_reg_1092 <= {{layer37_out_dout[175:154]}};
        trunc_ln58_505_reg_1097 <= {{layer37_out_dout[197:176]}};
        trunc_ln58_506_reg_1102 <= {{layer37_out_dout[219:198]}};
        trunc_ln58_507_reg_1107 <= {{layer37_out_dout[241:220]}};
        trunc_ln58_508_reg_1112 <= {{layer37_out_dout[263:242]}};
        trunc_ln58_509_reg_1117 <= {{layer37_out_dout[285:264]}};
        trunc_ln58_510_reg_1122 <= {{layer37_out_dout[307:286]}};
        trunc_ln58_511_reg_1127 <= {{layer37_out_dout[329:308]}};
        trunc_ln58_512_reg_1132 <= {{layer37_out_dout[351:330]}};
        trunc_ln58_reg_1057 <= trunc_ln58_fu_872_p1;
        trunc_ln58_s_reg_1062 <= {{layer37_out_dout[43:22]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_16u_config8_s_fu_468_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_860_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_860_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln52_fu_860_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer37_out_blk_n = layer37_out_empty_n;
    end else begin
        layer37_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_860_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer37_out_read = 1'b1;
    end else begin
        layer37_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_860_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_860_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_16u_config8_s_fu_468_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln52_fu_866_p2 = (indvar_flatten_fu_458 + 11'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2 = ((icmp_ln52_fu_860_p2 == 1'd0) & (layer37_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_ignore_call19 = ((icmp_ln52_fu_860_p2 == 1'd0) & (layer37_out_empty_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_16u_config8_s_fu_468_ap_start = grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_16u_config8_s_fu_468_ap_start_reg;

assign icmp_ln52_fu_860_p2 = ((indvar_flatten_fu_458 == 11'd1156) ? 1'b1 : 1'b0);

assign layer8_out_din = grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_16u_config8_s_fu_468_layer8_out_din;

assign layer8_out_write = grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_16u_config8_s_fu_468_layer8_out_write;

assign start_out = real_start;

assign trunc_ln58_fu_872_p1 = layer37_out_dout[21:0];

endmodule //resnet8_resource_fifo_opt_conv_2d_cl_array_ap_fixed_16u_array_ap_fixed_22_12_4_0_0_16u_config8_s
