// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module resnet8_resource_fifo_opt_conv_2d_cl_array_array_ap_fixed_22_12_4_0_0_64u_config24_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer41_out_dout,
        layer41_out_empty_n,
        layer41_out_read,
        layer41_out_num_data_valid,
        layer41_out_fifo_cap,
        layer24_out_din,
        layer24_out_full_n,
        layer24_out_write,
        layer24_out_num_data_valid,
        layer24_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [1407:0] layer41_out_dout;
input   layer41_out_empty_n;
output   layer41_out_read;
input  [5:0] layer41_out_num_data_valid;
input  [5:0] layer41_out_fifo_cap;
output  [1407:0] layer24_out_din;
input   layer24_out_full_n;
output   layer24_out_write;
input  [1:0] layer24_out_num_data_valid;
input  [1:0] layer24_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer41_out_read;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer41_out_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln52_fu_3212_p2;
wire   [21:0] trunc_ln58_fu_3224_p1;
reg   [21:0] trunc_ln58_reg_3937;
reg    ap_block_state2;
reg   [21:0] trunc_ln58_499_reg_3942;
reg   [21:0] trunc_ln58_500_reg_3947;
reg   [21:0] trunc_ln58_501_reg_3952;
reg   [21:0] trunc_ln58_502_reg_3957;
reg   [21:0] trunc_ln58_503_reg_3962;
reg   [21:0] trunc_ln58_504_reg_3967;
reg   [21:0] trunc_ln58_505_reg_3972;
reg   [21:0] trunc_ln58_506_reg_3977;
reg   [21:0] trunc_ln58_507_reg_3982;
reg   [21:0] trunc_ln58_508_reg_3987;
reg   [21:0] trunc_ln58_509_reg_3992;
reg   [21:0] trunc_ln58_510_reg_3997;
reg   [21:0] trunc_ln58_511_reg_4002;
reg   [21:0] trunc_ln58_512_reg_4007;
reg   [21:0] trunc_ln58_513_reg_4012;
reg   [21:0] trunc_ln58_514_reg_4017;
reg   [21:0] trunc_ln58_515_reg_4022;
reg   [21:0] trunc_ln58_516_reg_4027;
reg   [21:0] trunc_ln58_517_reg_4032;
reg   [21:0] trunc_ln58_518_reg_4037;
reg   [21:0] trunc_ln58_519_reg_4042;
reg   [21:0] trunc_ln58_520_reg_4047;
reg   [21:0] trunc_ln58_521_reg_4052;
reg   [21:0] trunc_ln58_522_reg_4057;
reg   [21:0] trunc_ln58_523_reg_4062;
reg   [21:0] trunc_ln58_524_reg_4067;
reg   [21:0] trunc_ln58_525_reg_4072;
reg   [21:0] trunc_ln58_526_reg_4077;
reg   [21:0] trunc_ln58_s_reg_4082;
reg   [21:0] trunc_ln58_527_reg_4087;
reg   [21:0] trunc_ln58_528_reg_4092;
reg   [21:0] trunc_ln58_529_reg_4097;
reg   [21:0] trunc_ln58_530_reg_4102;
reg   [21:0] trunc_ln58_531_reg_4107;
reg   [21:0] trunc_ln58_532_reg_4112;
reg   [21:0] trunc_ln58_533_reg_4117;
reg   [21:0] trunc_ln58_534_reg_4122;
reg   [21:0] trunc_ln58_535_reg_4127;
reg   [21:0] trunc_ln58_536_reg_4132;
reg   [21:0] trunc_ln58_537_reg_4137;
reg   [21:0] trunc_ln58_538_reg_4142;
reg   [21:0] trunc_ln58_539_reg_4147;
reg   [21:0] trunc_ln58_540_reg_4152;
reg   [21:0] trunc_ln58_541_reg_4157;
reg   [21:0] trunc_ln58_542_reg_4162;
reg   [21:0] trunc_ln58_543_reg_4167;
reg   [21:0] trunc_ln58_544_reg_4172;
reg   [21:0] trunc_ln58_545_reg_4177;
reg   [21:0] trunc_ln58_546_reg_4182;
reg   [21:0] trunc_ln58_547_reg_4187;
reg   [21:0] trunc_ln58_548_reg_4192;
reg   [21:0] trunc_ln58_549_reg_4197;
reg   [21:0] trunc_ln58_550_reg_4202;
reg   [21:0] trunc_ln58_551_reg_4207;
reg   [21:0] trunc_ln58_552_reg_4212;
reg   [21:0] trunc_ln58_553_reg_4217;
reg   [21:0] trunc_ln58_554_reg_4222;
reg   [21:0] trunc_ln58_555_reg_4227;
reg   [21:0] trunc_ln58_556_reg_4232;
reg   [21:0] trunc_ln58_557_reg_4237;
reg   [21:0] trunc_ln58_558_reg_4242;
reg   [21:0] trunc_ln58_559_reg_4247;
reg   [21:0] trunc_ln58_560_reg_4252;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_64u_config24_s_fu_1716_ap_start;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_64u_config24_s_fu_1716_ap_done;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_64u_config24_s_fu_1716_ap_idle;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_64u_config24_s_fu_1716_ap_ready;
wire   [1407:0] grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_64u_config24_s_fu_1716_layer24_out_din;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_64u_config24_s_fu_1716_layer24_out_write;
reg    grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_64u_config24_s_fu_1716_ap_start_reg;
reg    ap_block_state2_ignore_call67;
wire    ap_CS_fsm_state3;
reg   [6:0] indvar_flatten_fu_1706;
wire   [6:0] add_ln52_fu_3218_p2;
reg    ap_block_state1;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_64u_config24_s_fu_1716_ap_start_reg = 1'b0;
#0 indvar_flatten_fu_1706 = 7'd0;
end

resnet8_resource_fifo_opt_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_64u_config24_s grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_64u_config24_s_fu_1716(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_64u_config24_s_fu_1716_ap_start),
    .ap_done(grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_64u_config24_s_fu_1716_ap_done),
    .ap_idle(grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_64u_config24_s_fu_1716_ap_idle),
    .ap_ready(grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_64u_config24_s_fu_1716_ap_ready),
    .p_read(trunc_ln58_reg_3937),
    .p_read1(trunc_ln58_499_reg_3942),
    .p_read2(trunc_ln58_500_reg_3947),
    .p_read3(trunc_ln58_501_reg_3952),
    .p_read4(trunc_ln58_502_reg_3957),
    .p_read5(trunc_ln58_503_reg_3962),
    .p_read6(trunc_ln58_504_reg_3967),
    .p_read7(trunc_ln58_505_reg_3972),
    .p_read8(trunc_ln58_506_reg_3977),
    .p_read9(trunc_ln58_507_reg_3982),
    .p_read10(trunc_ln58_508_reg_3987),
    .p_read11(trunc_ln58_509_reg_3992),
    .p_read12(trunc_ln58_510_reg_3997),
    .p_read13(trunc_ln58_511_reg_4002),
    .p_read14(trunc_ln58_512_reg_4007),
    .p_read15(trunc_ln58_513_reg_4012),
    .p_read16(trunc_ln58_514_reg_4017),
    .p_read17(trunc_ln58_515_reg_4022),
    .p_read18(trunc_ln58_516_reg_4027),
    .p_read19(trunc_ln58_517_reg_4032),
    .p_read20(trunc_ln58_518_reg_4037),
    .p_read21(trunc_ln58_519_reg_4042),
    .p_read22(trunc_ln58_520_reg_4047),
    .p_read23(trunc_ln58_521_reg_4052),
    .p_read24(trunc_ln58_522_reg_4057),
    .p_read25(trunc_ln58_523_reg_4062),
    .p_read26(trunc_ln58_524_reg_4067),
    .p_read27(trunc_ln58_525_reg_4072),
    .p_read28(trunc_ln58_526_reg_4077),
    .p_read29(trunc_ln58_s_reg_4082),
    .p_read30(trunc_ln58_527_reg_4087),
    .p_read31(trunc_ln58_528_reg_4092),
    .p_read32(trunc_ln58_529_reg_4097),
    .p_read33(trunc_ln58_530_reg_4102),
    .p_read34(trunc_ln58_531_reg_4107),
    .p_read35(trunc_ln58_532_reg_4112),
    .p_read36(trunc_ln58_533_reg_4117),
    .p_read37(trunc_ln58_534_reg_4122),
    .p_read38(trunc_ln58_535_reg_4127),
    .p_read39(trunc_ln58_536_reg_4132),
    .p_read40(trunc_ln58_537_reg_4137),
    .p_read41(trunc_ln58_538_reg_4142),
    .p_read42(trunc_ln58_539_reg_4147),
    .p_read43(trunc_ln58_540_reg_4152),
    .p_read44(trunc_ln58_541_reg_4157),
    .p_read45(trunc_ln58_542_reg_4162),
    .p_read46(trunc_ln58_543_reg_4167),
    .p_read47(trunc_ln58_544_reg_4172),
    .p_read48(trunc_ln58_545_reg_4177),
    .p_read49(trunc_ln58_546_reg_4182),
    .p_read50(trunc_ln58_547_reg_4187),
    .p_read51(trunc_ln58_548_reg_4192),
    .p_read52(trunc_ln58_549_reg_4197),
    .p_read53(trunc_ln58_550_reg_4202),
    .p_read54(trunc_ln58_551_reg_4207),
    .p_read55(trunc_ln58_552_reg_4212),
    .p_read56(trunc_ln58_553_reg_4217),
    .p_read57(trunc_ln58_554_reg_4222),
    .p_read58(trunc_ln58_555_reg_4227),
    .p_read59(trunc_ln58_556_reg_4232),
    .p_read60(trunc_ln58_557_reg_4237),
    .p_read61(trunc_ln58_558_reg_4242),
    .p_read62(trunc_ln58_559_reg_4247),
    .p_read63(trunc_ln58_560_reg_4252),
    .layer24_out_din(grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_64u_config24_s_fu_1716_layer24_out_din),
    .layer24_out_full_n(layer24_out_full_n),
    .layer24_out_write(grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_64u_config24_s_fu_1716_layer24_out_write),
    .layer24_out_num_data_valid(2'd0),
    .layer24_out_fifo_cap(2'd0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_3212_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_64u_config24_s_fu_1716_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state2_ignore_call67) & (icmp_ln52_fu_3212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_64u_config24_s_fu_1716_ap_start_reg <= 1'b1;
        end else if ((grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_64u_config24_s_fu_1716_ap_ready == 1'b1)) begin
            grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_64u_config24_s_fu_1716_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_fu_1706 <= 7'd0;
    end else if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_3212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        indvar_flatten_fu_1706 <= add_ln52_fu_3218_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
        trunc_ln58_499_reg_3942 <= {{layer41_out_dout[43:22]}};
        trunc_ln58_500_reg_3947 <= {{layer41_out_dout[65:44]}};
        trunc_ln58_501_reg_3952 <= {{layer41_out_dout[87:66]}};
        trunc_ln58_502_reg_3957 <= {{layer41_out_dout[109:88]}};
        trunc_ln58_503_reg_3962 <= {{layer41_out_dout[131:110]}};
        trunc_ln58_504_reg_3967 <= {{layer41_out_dout[153:132]}};
        trunc_ln58_505_reg_3972 <= {{layer41_out_dout[175:154]}};
        trunc_ln58_506_reg_3977 <= {{layer41_out_dout[197:176]}};
        trunc_ln58_507_reg_3982 <= {{layer41_out_dout[219:198]}};
        trunc_ln58_508_reg_3987 <= {{layer41_out_dout[241:220]}};
        trunc_ln58_509_reg_3992 <= {{layer41_out_dout[263:242]}};
        trunc_ln58_510_reg_3997 <= {{layer41_out_dout[285:264]}};
        trunc_ln58_511_reg_4002 <= {{layer41_out_dout[307:286]}};
        trunc_ln58_512_reg_4007 <= {{layer41_out_dout[329:308]}};
        trunc_ln58_513_reg_4012 <= {{layer41_out_dout[351:330]}};
        trunc_ln58_514_reg_4017 <= {{layer41_out_dout[373:352]}};
        trunc_ln58_515_reg_4022 <= {{layer41_out_dout[395:374]}};
        trunc_ln58_516_reg_4027 <= {{layer41_out_dout[417:396]}};
        trunc_ln58_517_reg_4032 <= {{layer41_out_dout[439:418]}};
        trunc_ln58_518_reg_4037 <= {{layer41_out_dout[461:440]}};
        trunc_ln58_519_reg_4042 <= {{layer41_out_dout[483:462]}};
        trunc_ln58_520_reg_4047 <= {{layer41_out_dout[505:484]}};
        trunc_ln58_521_reg_4052 <= {{layer41_out_dout[527:506]}};
        trunc_ln58_522_reg_4057 <= {{layer41_out_dout[549:528]}};
        trunc_ln58_523_reg_4062 <= {{layer41_out_dout[571:550]}};
        trunc_ln58_524_reg_4067 <= {{layer41_out_dout[593:572]}};
        trunc_ln58_525_reg_4072 <= {{layer41_out_dout[615:594]}};
        trunc_ln58_526_reg_4077 <= {{layer41_out_dout[637:616]}};
        trunc_ln58_527_reg_4087 <= {{layer41_out_dout[681:660]}};
        trunc_ln58_528_reg_4092 <= {{layer41_out_dout[703:682]}};
        trunc_ln58_529_reg_4097 <= {{layer41_out_dout[725:704]}};
        trunc_ln58_530_reg_4102 <= {{layer41_out_dout[747:726]}};
        trunc_ln58_531_reg_4107 <= {{layer41_out_dout[769:748]}};
        trunc_ln58_532_reg_4112 <= {{layer41_out_dout[791:770]}};
        trunc_ln58_533_reg_4117 <= {{layer41_out_dout[813:792]}};
        trunc_ln58_534_reg_4122 <= {{layer41_out_dout[835:814]}};
        trunc_ln58_535_reg_4127 <= {{layer41_out_dout[857:836]}};
        trunc_ln58_536_reg_4132 <= {{layer41_out_dout[879:858]}};
        trunc_ln58_537_reg_4137 <= {{layer41_out_dout[901:880]}};
        trunc_ln58_538_reg_4142 <= {{layer41_out_dout[923:902]}};
        trunc_ln58_539_reg_4147 <= {{layer41_out_dout[945:924]}};
        trunc_ln58_540_reg_4152 <= {{layer41_out_dout[967:946]}};
        trunc_ln58_541_reg_4157 <= {{layer41_out_dout[989:968]}};
        trunc_ln58_542_reg_4162 <= {{layer41_out_dout[1011:990]}};
        trunc_ln58_543_reg_4167 <= {{layer41_out_dout[1033:1012]}};
        trunc_ln58_544_reg_4172 <= {{layer41_out_dout[1055:1034]}};
        trunc_ln58_545_reg_4177 <= {{layer41_out_dout[1077:1056]}};
        trunc_ln58_546_reg_4182 <= {{layer41_out_dout[1099:1078]}};
        trunc_ln58_547_reg_4187 <= {{layer41_out_dout[1121:1100]}};
        trunc_ln58_548_reg_4192 <= {{layer41_out_dout[1143:1122]}};
        trunc_ln58_549_reg_4197 <= {{layer41_out_dout[1165:1144]}};
        trunc_ln58_550_reg_4202 <= {{layer41_out_dout[1187:1166]}};
        trunc_ln58_551_reg_4207 <= {{layer41_out_dout[1209:1188]}};
        trunc_ln58_552_reg_4212 <= {{layer41_out_dout[1231:1210]}};
        trunc_ln58_553_reg_4217 <= {{layer41_out_dout[1253:1232]}};
        trunc_ln58_554_reg_4222 <= {{layer41_out_dout[1275:1254]}};
        trunc_ln58_555_reg_4227 <= {{layer41_out_dout[1297:1276]}};
        trunc_ln58_556_reg_4232 <= {{layer41_out_dout[1319:1298]}};
        trunc_ln58_557_reg_4237 <= {{layer41_out_dout[1341:1320]}};
        trunc_ln58_558_reg_4242 <= {{layer41_out_dout[1363:1342]}};
        trunc_ln58_559_reg_4247 <= {{layer41_out_dout[1385:1364]}};
        trunc_ln58_560_reg_4252 <= {{layer41_out_dout[1407:1386]}};
        trunc_ln58_reg_3937 <= trunc_ln58_fu_3224_p1;
        trunc_ln58_s_reg_4082 <= {{layer41_out_dout[659:638]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_64u_config24_s_fu_1716_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_3212_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_3212_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln52_fu_3212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer41_out_blk_n = layer41_out_empty_n;
    end else begin
        layer41_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_3212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer41_out_read = 1'b1;
    end else begin
        layer41_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_3212_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state2) & (icmp_ln52_fu_3212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_64u_config24_s_fu_1716_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln52_fu_3218_p2 = (indvar_flatten_fu_1706 + 7'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2 = ((icmp_ln52_fu_3212_p2 == 1'd0) & (layer41_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_ignore_call67 = ((icmp_ln52_fu_3212_p2 == 1'd0) & (layer41_out_empty_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_64u_config24_s_fu_1716_ap_start = grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_64u_config24_s_fu_1716_ap_start_reg;

assign icmp_ln52_fu_3212_p2 = ((indvar_flatten_fu_1706 == 7'd100) ? 1'b1 : 1'b0);

assign layer24_out_din = grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_64u_config24_s_fu_1716_layer24_out_din;

assign layer24_out_write = grp_compute_output_buffer_2d_array_array_ap_fixed_22_12_4_0_0_64u_config24_s_fu_1716_layer24_out_write;

assign start_out = real_start;

assign trunc_ln58_fu_3224_p1 = layer41_out_dout[21:0];

endmodule //resnet8_resource_fifo_opt_conv_2d_cl_array_array_ap_fixed_22_12_4_0_0_64u_config24_s
